Force value rendering and validation check after the clear button click (T818673)
DevExpress/DevExtreme pull request #10114
Opened 2019-10-09 18:12 UTC by alexander-kotov-dx

2019-10-10 10:35 UTC, DokaRus reviewed
lgtm

2019-10-10 10:35 UTC, DokaRus submitted a review, later dismissed

2019-10-10 13:02 UTC, mrjohn0011 requested changes
There are no tests

2019-10-11 10:04 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets.editors/numberBoxParts/common.tests.js
> +        instance._inputIsInvalid = () => true;
```js
sinon.stub(instance, "_inputIsInvalid ", () => true);
<...>
instance._inputIsInvalid.restore();
```

2019-10-11 10:05 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets.editors/numberBoxParts/common.tests.js
> +        const $input = $element.find(".dx-texteditor-input");
```suggestion
        const $input = $element.find(`.${INPUT_CLASS}`);
```

2019-10-11 10:59 UTC, DokaRus approved these changes

2019-10-11 12:33 UTC, mrjohn0011 approved these changes

2019-10-11 12:44 UTC, merged