Support css classes duplication from the overlay elementAttr option to the overlay wrapper (T824150)
DevExpress/DevExtreme pull request #10350
Opened 2019-10-25 13:41 UTC by alexander-kotov-dx

2019-10-28 08:22 UTC, mrjohn0011 submitted a review, later dismissed

2019-10-28 11:21 UTC, San4es requested changes

2019-10-28 11:21 UTC, San4es commented on js/ui/overlay/ui.overlay.js
> +    _moveElementClassesToWrapper: function(options) {
_moveElementClassesToWrapper -> _copyElementClassesToWrapper/_cloneElementClassesToWrapper?

2019-10-28 11:21 UTC, San4es commented on testing/tests/DevExpress.ui.widgets/overlay.tests.js
> +                class: "something another"
-> "some-class another-class"?

2019-10-28 11:21 UTC, San4es commented on testing/tests/DevExpress.ui.widgets/overlay.tests.js
> +    test("changed css classes from the overlay elementAttr should be used for the wrapper", (assert) => {
-> "CSS classes changes via elementAttr should be applied to the wrapper"

2019-10-31 09:49 UTC, San4es approved these changes
LGTM

2019-10-31 11:29 UTC, ksercs approved these changes

2019-10-31 12:16 UTC, San4es commented
We discussed this case with @alexander-kotov-dx, @NickMitrokhin, @LexDX, and found that this change can lead to unexpected behavior, so we decided not to add it to our component. We will improve our API in the future and add something like the 'wrapperAttr' option to handle similar cases.

2019-10-31 12:16 UTC, closed without merging