DataGrid: Fix placeholder was wider than grid if horizontal scroll exists (T830034)
DevExpress/DevExtreme pull request #10704
Opened 2019-11-19 16:06 UTC by jtoming830

2019-11-20 06:49 UTC, vconst requested changes
Fix the problem in Sortable widget because user can drag custom items in scrollable with horizontal scroll.
Also check dragging when horizontal scroll position is not zero.

2019-11-28 11:53 UTC, vconst requested changes

2019-11-28 11:53 UTC, vconst commented on js/ui/draggable.js
> +        that.verticalScrollHelper && that.verticalScrollHelper.updateScrollable(allObjects, mousePosition);
Add "_" prefix to verticalScrollHelper  and horizontalScrollHelper because they are not public

2019-12-03 14:56 UTC, vconst approved these changes

2019-12-04 09:04 UTC, Alyar666 approved these changes

2019-12-04 09:58 UTC, merged