Renovation: EventsStrategy refactor
DevExpress/DevExtreme pull request #10875
Opened 2019-11-28 09:47 UTC by LazyLahtak

Replace `on` and `off` methods from components to EventsStrategy.
Correct doc comments for `on` and `off` methods.
Rename `setEventsStrategy` method.

Refactor of #10524

2019-11-28 13:12 UTC, IlyaKhD requested changes
What is the aim of declaring inheritance?
Declarations (TS especially) should fit JS part, and there is no inheritance in the JS part, right?

I mean these:

```
@name DevicesObject 
@inherits EventsStrategy
```
```
@name Store
@inherits EventsStrategy
```
etc.

2019-11-28 13:30 UTC, LazyLahtak commented
> What is the aim of declaring inheritance?

It is a try to avoid multiple [doc comments](https://github.com/DevExpress/DevExtreme/pull/10875/files#diff-8ae7d11679885a2279672087e53958b3R38-R81). But if we declare it in the EventsStrategy, we should bound it with components. We decided to declare inheritance.

2019-11-29 10:25 UTC, IlyaKhD commented
LGTM

2019-12-02 10:17 UTC, churkin approved these changes

2019-12-02 11:43 UTC, IlyaKhD approved these changes

2019-12-02 11:44 UTC, merged