PivotGrid: Fix error occurs when filtering values by using Field Chooser (T836053)
DevExpress/DevExtreme pull request #10942
Opened 2019-12-03 10:53 UTC by jtoming830

2019-12-11 08:07 UTC, vconst requested changes

2019-12-11 08:07 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.pivotGrid/store.remote.tests.js
> +            { dataField: "OrderDate", groupInterval: "quarter", dataType: "date" },
Change "quarter" to "year" because Date group usually starts from year

2019-12-13 06:44 UTC, vconst approved these changes

2019-12-13 13:07 UTC, AntonSermyazhko approved these changes

2019-12-13 13:10 UTC, merged