DataGrid - The widget incorrectly renders borders of the last column's header cell if native scrolling is enabled (T838716)
DevExpress/DevExtreme pull request #11057
Opened 2019-12-11 11:43 UTC by igormalzew

2019-12-17 13:25 UTC, vconst requested changes

2019-12-17 13:25 UTC, vconst commented on js/ui/grid_core/ui.grid_core.grid_view.js
> +            that._columnHeadersView && that._columnHeadersView.toggleScrollerBorder(vScrollbarWidth);
Make toggleScrollerBorder private by adding prefix "_" and call it inside setScrollerSpacing. Small public API is better.

2019-12-17 14:41 UTC, igormalzew commented on js/ui/grid_core/ui.grid_core.grid_view.js
> +            that._columnHeadersView && that._columnHeadersView.toggleScrollerBorder(vScrollbarWidth);
Done

2019-12-19 14:36 UTC, vconst approved these changes

2019-12-19 14:40 UTC, jtoming830 approved these changes

2019-12-19 14:43 UTC, merged