Fix T506859: dxScheduler renders recurrent events incorrectly when a number of occurrences is selected
DevExpress/DevExtreme pull request #111
Opened 2017-05-12 11:08 UTC by Yarovaya

2017-05-12 11:23 UTC, KsyushaM requested changes

2017-05-12 11:23 UTC, KsyushaM commented on js/ui/scheduler/utils.recurrence.js
> +var checker = function(currentDate, i, config) {
Please, rename "checker" to "checkDate" for example

2017-05-12 12:00 UTC, lukyanovas requested changes

2017-05-12 12:00 UTC, lukyanovas commented on testing/tests/DevExpress.ui.widgets.scheduler/utils.recurrence.tests.js
> +QUnit.test('getDatesByRecurrence should handle strings with COUNT & BYDAY', function(assert) {
Please, add tests for cases in which dates are limited with "COUNT" rule.

2017-05-15 07:30 UTC, lukyanovas approved these changes

2017-05-15 07:31 UTC, KsyushaM approved these changes

2017-05-15 07:36 UTC, merged