DataGrid: Fix validation error disappears when a new portion of data is loaded during scrolling (T838674)
DevExpress/DevExtreme pull request #11114
Opened 2019-12-13 13:55 UTC by jtoming830

2019-12-19 14:41 UTC, vconst submitted a review, later dismissed

2019-12-25 11:48 UTC, vconst requested changes

2019-12-25 11:48 UTC, vconst commented on js/ui/grid_core/ui.grid_core.validating.js
> +                let isVisibleColumn = brokenRule.column && brokenRule.column.visible && brokenRule.column.groupIndex === undefined;
Change 
`brokenRule.column.groupIndex === undefined`
to
`!brokenRule.column.type`

because the showWhenGrouped option can be enabled in column.

2019-12-25 16:50 UTC, vconst approved these changes

2019-12-26 06:17 UTC, igormalzew approved these changes

2019-12-26 08:43 UTC, merged