DataGrid - The detail view cannot be expanded after switching to the edit mode (T845240)
DevExpress/DevExtreme pull request #11160
Opened 2019-12-17 13:00 UTC by igormalzew

2019-12-18 08:29 UTC, jtoming830 requested changes

2019-12-18 08:29 UTC, jtoming830 commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    return eventName === startEditAction && allowEditing && editingController.editCell(e.rowIndex, columnIndex) || allowEditing && editingController.isEditRow(e.rowIndex);
cherry pick changes from the main pull request

2019-12-19 14:33 UTC, AntonSermyazhko approved these changes

2019-12-19 14:36 UTC, jtoming830 approved these changes

2019-12-19 14:36 UTC, merged