DataGrid: Fix filter row was losing focus after changing filterValue (T657041)
DevExpress/DevExtreme pull request #11259
Opened 2019-12-23 11:54 UTC by jtoming830

2019-12-24 07:52 UTC, vconst requested changes

2019-12-24 07:52 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +    assert.ok($filterRowEditor.find(':focus').length, 'focus');
$filterRowEditor.is(':focus') will be better

2019-12-24 07:52 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +    assert.equal(onOptionChanged.callCount, 4, 'onOptionChanged call count');
Why is callCount 4? Is it important for this test?

2019-12-24 09:54 UTC, vconst approved these changes

2019-12-26 15:59 UTC, Alyar666 approved these changes

2019-12-27 13:05 UTC, merged