DataGrid: Fix the E1037 error that the widget does not show (T846113)
DevExpress/DevExtreme pull request #11264
Opened 2019-12-23 12:58 UTC by Alyar666

See https://devexpress.com/issue=T846113

2019-12-23 13:25 UTC, vconst requested changes

2019-12-23 13:25 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataController.tests.js
>  QUnit.test('Exception when CustomStore returns plain data and remote grouping enabled', function(assert) {
Change test name because exception does not occur after fix

2019-12-23 13:25 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataController.tests.js
>  QUnit.test('Exception when CustomStore returns groups without items', function(assert) {
Change test name because exception does not occur after fix

2019-12-24 08:33 UTC, jtoming830 submitted a review, later dismissed

2019-12-25 07:30 UTC, vconst approved these changes

2019-12-25 07:47 UTC, merged