Renovation: odata/query_adapter es6 refactoring
DevExpress/DevExtreme pull request #11389
Opened 2019-12-31 12:02 UTC by LazyLahtak

Part of refactoring odata/* components

(In plans - get rid of odata/mixins)

2020-01-09 08:20 UTC, churkin requested changes

2020-01-09 08:20 UTC, churkin commented on js/data/odata/query_adapter.js
> +    const hasSlice = () => {
Use one line function definition for simple lambdas
```javascript
const hasSlice = () => _skip || _take !== undefined;
```

2020-01-09 08:20 UTC, churkin commented on js/data/odata/query_adapter.js
> +        optimize(tasks) {
```javascript
optimize:  tryLiftSelect,
```

2020-01-09 08:20 UTC, churkin commented on js/data/odata/query_adapter.js
>                      url: url,
`url,`

2020-01-09 08:20 UTC, churkin commented on js/data/odata/query_adapter.js
> +        count() {
```javascript
count: () => _countQuery = true,
```

2020-01-09 10:12 UTC, MaximKudriavtsev commented on js/data/odata/query_adapter.js
> +            return `${prop} ${op} ${val}`;
Also `(prop, val) => ${prop} ${op} ${val}`

2020-01-09 13:05 UTC, MaximKudriavtsev approved these changes

2020-01-13 07:38 UTC, LazyLahtak commented
Ready to review

2020-01-17 05:47 UTC, churkin approved these changes

2020-01-17 06:49 UTC, merged