Fix compound keys comparison (T852818)
DevExpress/DevExtreme pull request #11572
Opened 2020-01-17 15:12 UTC by dxvladislavvolkov

2020-01-20 09:30 UTC, nightskylark commented on js/data/utils.js
>  const keysEqual = function(keyExpr, key1, key2) {
The `keyExpr` variable was not used in a comparison since the method was written (4c89bcaff145 in hg). @AlekseyMartynov , can you explain, why?

2020-01-22 10:19 UTC, nightskylark requested changes

2020-01-22 10:19 UTC, nightskylark commented on js/core/utils/common.js
> +const equalByValue = function(object1, object2, depth, strict) {
```suggestion
const equalByValue = function(object1, object2, depth = 0, strict = true) {
```

2020-01-22 10:58 UTC, nightskylark submitted a review, later dismissed

2020-01-22 12:28 UTC, nightskylark submitted a review, later dismissed

2020-01-22 12:53 UTC, AlekseyMartynov approved these changes

2020-01-22 13:57 UTC, merged