PivotGrid: Fix texts.emptyValue was not working (T852897)
DevExpress/DevExtreme pull request #11671
Opened 2020-01-23 14:02 UTC by jtoming830

2020-01-23 15:39 UTC, roman-simionov approved these changes

2020-01-23 15:42 UTC, roman-simionov requested changes

2020-01-23 15:42 UTC, roman-simionov commented on js/ui/pivot_grid/ui.pivot_grid.field_chooser_base.js
> +                                    data.forEach((element) => {
move up `that.option('headerFilter.texts.emptyValue')` from cycle

2020-01-24 10:31 UTC, roman-simionov approved these changes

2020-01-24 11:16 UTC, vconst approved these changes

2020-01-24 11:17 UTC, merged