Draggable: fix clone had incorrect direction if rtlEnabled (T859557 refix)
DevExpress/DevExtreme pull request #11928
Opened 2020-02-07 11:09 UTC by jtoming830

2020-02-07 15:12 UTC, Alyar666 approved these changes

2020-02-10 07:23 UTC, vconst requested changes

2020-02-10 07:23 UTC, vconst commented on js/ui/draggable.js
> +            .toggleClass('dx-rtl', this.option('rtlEnabled'));
This class should not be added if clone is false.

2020-02-11 09:34 UTC, vconst approved these changes

2020-02-11 09:57 UTC, merged