DataGrid: Fix cell was editing after adding row and page change if mode is cell (T861092)
DevExpress/DevExtreme pull request #12067
Opened 2020-02-18 13:42 UTC by jtoming830

2020-02-18 16:27 UTC, vconst requested changes

2020-02-18 16:27 UTC, vconst commented on js/ui/grid_core/ui.grid_core.data_controller.js
> +                            const editingController = that.getController('editing');
1) Move this code to editing module
2) Check virtual scrolling because virtual scrolling uses paging

2020-02-20 13:23 UTC, vconst submitted a review, later dismissed

2020-02-21 10:38 UTC, Alyar666 submitted a review, later dismissed

2020-02-21 11:42 UTC, Alyar666 approved these changes

2020-02-25 08:20 UTC, merged