dxSchedulre - Improve form
DevExpress/DevExtreme pull request #12157
Opened 2020-02-27 14:16 UTC by Krijovnick

2020-03-02 06:58 UTC, Yarovaya commented on styles/widgets/base/recurrenceEditor.less
> +        padding: 8px;
Describe const for this paddind

2020-03-04 08:25 UTC, Yarovaya requested changes

2020-03-04 08:25 UTC, Yarovaya commented on js/ui/scheduler/ui.scheduler.appointment_form.js
> +                    cssClass: 'dx-uppointment-form-switch',
dx-appointment-form-switch?

2020-03-05 12:02 UTC, andrewmakarov approved these changes

2020-03-06 08:00 UTC, Yarovaya approved these changes

2020-03-06 08:05 UTC, merged