DataGrid - The focused row isn't highlighted when the "repaintChangesOnly" option is enabled (T867777)
DevExpress/DevExtreme pull request #12327
Opened 2020-03-17 08:25 UTC by igormalzew

2020-03-18 11:53 UTC, vconst requested changes

2020-03-18 11:53 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +                assert.equal(focusedRowIndex, -1, 'Page index was cleared after page changing');
"Page index was cleared" or "focused row index was cleared"?

2020-03-18 12:40 UTC, igormalzew commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +                assert.equal(focusedRowIndex, -1, 'Page index was cleared after page changing');
Indeed "Focused row index". Fixed.

2020-03-19 16:39 UTC, vconst submitted a review, later dismissed

2020-03-19 19:02 UTC, jtoming830 submitted a review, later dismissed

2020-03-25 11:52 UTC, closed without merging