Implement Deferred utility
DevExpress/DevExtreme pull request #1257
Opened 2017-09-05 12:21 UTC by ovchinnikov

2017-09-05 12:56 UTC, nightskylark requested changes

2017-09-05 12:56 UTC, nightskylark commented on js/core/utils/deferred.js
> +    this._promise.promise(this, this._promise.promise());
Remove second argument

2017-09-05 12:56 UTC, nightskylark approved these changes

2017-09-05 21:22 UTC, Aden-git approved these changes

2017-09-06 08:40 UTC, babich-a approved these changes

2017-09-06 11:59 UTC, merged