fix wrong references in doc comments
DevExpress/DevExtreme pull request #1263
Opened 2017-09-06 15:36 UTC by lukyanovas

2017-09-06 15:51 UTC, pavelgruba requested changes

2017-09-06 15:51 UTC, pavelgruba commented on js/viz/docs/doccharts.js
> +    * @type_function_return basePointObject
dxChartSeriesTypes_CommonSeries_point

2017-09-06 15:51 UTC, pavelgruba commented on js/viz/docs/doccharts.js
> +    * @type_function_return baseLabelObject
dxChartSeriesTypes_CommonSeries_label

2017-09-06 16:11 UTC, pavelgruba approved these changes

2017-09-07 06:39 UTC, IlyaKhD approved these changes

2017-09-07 08:27 UTC, vconst approved these changes

2017-09-07 08:32 UTC, merged