DataGrid: Fix incorrect row render after scroll if scrolling and row rendering are virtual (T750279)
DevExpress/DevExtreme pull request #12762
Opened 2020-04-17 14:06 UTC by jtoming830

2020-04-20 08:26 UTC, vconst requested changes

2020-04-20 08:26 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataController.tests.js
> +        assert.equal(rowsScrollControllerCall.args[0], dataSourceCall.args[0], 'setViewportItemIndex call args are same');
Check call count for this methods.
Also check parameter values instead of args equality.

2020-04-20 13:37 UTC, vconst approved these changes

2020-04-21 08:45 UTC, Alyar666 approved these changes

2020-04-21 08:47 UTC, merged