fix T551822: Defining CustomStore throws errors in TypeScript if stri…
DevExpress/DevExtreme pull request #1280
Opened 2017-09-08 16:27 UTC by dxvladislavvolkov

…ctNullChecks is enabled

2017-09-11 08:54 UTC, Aden-git submitted a review, later dismissed

2017-09-11 10:03 UTC, lukyanovas requested changes
"Function | null" is not supported

2017-09-12 09:22 UTC, lukyanovas approved these changes

2017-09-12 09:23 UTC, Aden-git approved these changes

2017-09-12 09:25 UTC, merged