dxList - search box implementation
DevExpress/DevExtreme pull request #1290
Opened 2017-09-11 14:41 UTC by Alyar666

2017-09-12 07:35 UTC, vconst requested changes

2017-09-12 07:35 UTC, vconst commented on js/ui/list/ui.list.edit.js
> +            * @default 'contains'
Where is available values?

2017-09-12 07:35 UTC, vconst commented on js/ui/list/ui.list.edit.js
> +            searchOperations: this.option("searchMode"),
Why is searchOperations?

2017-09-12 07:35 UTC, vconst commented on js/ui/list/ui.list.edit.js
> +            searchEditorHeight = this._$searchEditorElement.outerHeight(true);
Getting height is not good. Try change to use css only.

2017-09-12 07:35 UTC, vconst commented on js/ui/list/ui.list.edit.js
> +        };
Can we remove this code without any problems?

2017-09-12 07:43 UTC, mrjohn0011 reviewed
I think the dxList is the simple widget designed to show collection data. It is not a good idea to make it more complex. Search functionality should be a separate module or example but not out-of-the-box functionality

2017-09-12 07:47 UTC, kvet commented
It seems a bit strange to embed TextBox to the List. The primary List feature is to show a list. It is used by 100% of customers. The embedded search will be used by, for example, 0.1% of customers. Why should we slow down the widget for all of the customers?

2017-09-12 13:25 UTC, poltp commented
Guys, do you use List without searching capability?
Or DevExtreme list is just control to show 3-5 items? Am I right? There is no objections if it is...

2017-09-12 13:50 UTC, mrjohn0011 commented
@poltp, there is an [example](https://js.devexpress.com/Demos/WidgetsGallery/Demo/List/ListWithSearchBar/jQuery/Light/) demonstrating how to use the search box in the dxList. It contains less of code than changes requested by @Alyar666

2017-09-12 13:53 UTC, mrjohn0011 requested changes
I think this changes should not be merged because this functionality can be implemented by the user with less of code as it is shown in our example

2017-09-12 14:13 UTC, mrjohn0011 commented on js/ui/list/ui.list.edit.search.js
> +                    errors.log("W1009");
dxList can work with "items" option and have no value in the "dataSource" option

2017-09-13 09:27 UTC, poltp commented
@mrjohn0011
I do not understand your logic. What is the goal of dxList?
Loks like "to show list of items", am I right?
What number of items do you show (you do not answer me)?
Ok, you show 3 or 5 items and you are rigt - searching capability is too complex for this control.
I suppose, 80% customers show more than 5 items. If I'm right, searchiong capability must be main feature of this control.

Do you use something like car or phone?
If you buy car and seller ask you to buy steering wheel? If you buy phone and seller sells you just chip and ask you buy the body separately?

Guys, I don't know your users. Our dashboard users want to work fast. As your user I suggest use your controls without coding - you are coding for the DevExporess money, I do not want to get this money twice:)

2017-09-13 10:37 UTC, kvet commented
@poltp 
Our goal is to release fast robust and lightweight widgets that fit the needs of the most customers. You can easily combine them to implement search panel for dxList. It's shown in our demo. And it is simple.

An analogy. You are asking us to equip cars with armored glasses and bodywork. While you will be happy in safety, many others will not buy our car as it too slow and expensive.

Of course, dxList can be better and should evolve. But as an example, I would rather have embedded virtualization. As it will increase dxList performance for many customers that pass more than 5 items to the widget.

2017-09-13 10:57 UTC, dxbykov commented
Guys, why can't we treat this search capability as an extension/plugin to the dxList widget? This way we'll keep the widget fast and light for those who don't need it. At the same time, we'll provide an easy search capabilities integration for those who need it. In the future, we should apply this approach to other DevExtreme widgets, so a widget feature can be enabled by dynamically added extensions not built-in statically. Keep this in mind to minimize the amount of breaking changes in the future.

2017-09-13 11:29 UTC, lukyanovas requested changes

2017-09-13 11:29 UTC, lukyanovas commented on js/ui/list/ui.list.edit.search.js
> +             * @type TextBox options
use dxTextBoxOptions

2017-09-13 12:03 UTC, kaatula commented
@mrjohn0011  @kvet  you could miss that we should deliver not only lightweight widgets, but - in the same time - useful widgets. And that our widgets should be ready for big data, or whatever is exact quotation. 

The opinion of people who tried to **really** use List with more than a couple of dozens items is strangelly unique.

If @dxbykov idea is to provide such search **extension** out of the box, so the only difference with `not built-in statically` feature that it won't break on JS interpretation if required module is missed - I'm for it.

But if you guys decided to embed virtualization in this iteration too - that's a great news!

2017-09-13 12:09 UTC, mrjohn0011 submitted a review, later dismissed

2017-09-13 12:09 UTC, kaatula commented
@mrjohn0011  are referreng to this example, which demonstrates how to integrate dxList and dxTextBox and keep it with perfect common UI style?
![image](https://user-images.githubusercontent.com/939396/30376528-62ea1806-9895-11e7-9fb4-15367878d275.png)

2017-09-13 12:13 UTC, mrjohn0011 commented
I approved this PR if it is going to be a separate plugin in the future

2017-09-14 10:56 UTC, lukyanovas approved these changes

2017-09-14 11:11 UTC, vconst approved these changes

2017-09-14 11:27 UTC, merged