dxTreeView - search box implementation
DevExpress/DevExtreme pull request #1291
Opened 2017-09-11 14:41 UTC by Alyar666

2017-09-13 11:49 UTC, lukyanovas requested changes

2017-09-13 11:49 UTC, lukyanovas commented on js/ui/tree_view.js
> +             * @type TextBox options
dxTextBoxOptions

2017-09-14 08:28 UTC, mrjohn0011 submitted a review, later dismissed

2017-09-14 14:40 UTC, mrjohn0011 submitted a review, later dismissed

2017-09-15 07:33 UTC, lukyanovas approved these changes

2017-09-15 08:29 UTC, merged