dropDownButton - change horizontal paddings if the widget has no dropdown arrow (T888866)
DevExpress/DevExtreme pull request #13040
Opened 2020-05-15 08:55 UTC by alexander-kotov-dx

![ddb](https://user-images.githubusercontent.com/23214056/82031715-f5260780-96a2-11ea-9ce2-c564957ef22b.png)

2020-05-15 11:44 UTC, babich-a submitted a review, later dismissed

2020-05-15 12:26 UTC, ksercs submitted a review, later dismissed

2020-05-15 12:26 UTC, ksercs commented on testing/tests/DevExpress.ui.widgets/dropDownButton.markup.tests.js
> +    QUnit.test('widget should have specific class if it has an no arrow part', function(assert) {
It seems to be like the indefinite article `an` is excess here

2020-05-15 13:15 UTC, DokaRus approved these changes

2020-05-15 13:17 UTC, DokaRus requested changes

2020-05-15 13:17 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets/dropDownButton.markup.tests.js
> +    QUnit.test('widget should have specific class if it has an arrow part (T888866)', function(assert) {
>  const hasArrow = this.option('**splitButton**') || this.option('showArrowIcon');

How about test `splitButton`?

2020-05-15 14:02 UTC, alexander-kotov-dx commented on testing/tests/DevExpress.ui.widgets/dropDownButton.markup.tests.js
> +    QUnit.test('widget should have specific class if it has an arrow part (T888866)', function(assert) {
added

2020-05-18 07:30 UTC, DokaRus approved these changes

2020-05-18 09:32 UTC, ksercs approved these changes

2020-05-18 09:36 UTC, merged