DataGrid: Fix column resizing when columnResizingMode is widget and rtlEnabled is true (T837344)
DevExpress/DevExtreme pull request #13060
Opened 2020-05-15 18:28 UTC by Alyar666

See https://devexpress.com/issue=T837344

2020-05-19 14:42 UTC, vconst requested changes

2020-05-19 14:42 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_resizing_reordering.js
> +    _isRtlMode: function() {
_isRtlMode -> _isRtlParentStyle

2020-05-19 14:42 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_resizing_reordering.js
> +    _isRtlMode: function() {
Also, I think that we should check this style only if rtlEnabled is true to improve performance without rtl

2020-05-20 15:32 UTC, jtoming830 commented on js/ui/grid_core/ui.grid_core.columns_resizing_reordering.js
> +            if(scrollable && that.option('rtlEnabled') && that._isRtlParentStyle()) {
isRtlParentStyle will check for this.option('rtlEnabled') so check rtlEnabled here is unnecessary

2020-05-20 16:03 UTC, jtoming830 commented on js/ui/grid_core/ui.grid_core.columns_resizing_reordering.js
> +        return this._$parentContainer && this.option('rtlEnabled') && this._$parentContainer.parent().css('direction') === 'rtl';
You can minify this condition using optional chaining. 
`this.option('rtlEnabled') && this._$parentContainer?.parent.().css.('direction') === 'rtl';`

2020-05-21 07:01 UTC, vconst approved these changes

2020-05-21 15:30 UTC, merged