Form - New tests
DevExpress/DevExtreme pull request #13415
Opened 2020-06-13 10:57 UTC by novsstation

1) rename "form.scenarios.tests" to  "form.layout.tests"
2) new test for updateFormData logic and editor values after rendering

2020-06-15 12:02 UTC, IgnatovDan requested changes

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                const oldFormData = { a: '1' };
Do we really need to test it for the full set of configs for each widget?
imho it's enough to test one member only: old -> new.

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                assert.strictEqual(form.getEditor('b').option('value'), expectedOldValue);
I think we need to check the formData.member value as well:
assert.strictEqual(form.option('formData').member, expectedOldValue);  - it should be synchronized with the editor value

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                const expectedNewValue = newValue === 'no member' ? expectedOldValue : newValue;
Wow...
The '2' value is expected in the editor if the {b: '2'} object was changed to the {} object... Am I right?

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                assert.strictEqual(form.getEditor('b').option('value'), expectedNewValue);
I think we need to check the formData.member value as well:
assert.strictEqual(form.option('formData').member, expectedNewValue); - it should be synchronized with the editor value

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +        QUnit.test(`FormData = { a: '1', b: ${oldValue} } -> option('formData', {})`, function(assert) {
It seems that this config duplicates the '['no member'].forEach(newValue => {' config and we can delete it.

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +        const $checkBox = $(editor.element());
"$checkBox.hasClass" seems to be internal implementation details of dxCheckBox and we should not check it here.

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +        QUnit.assert.strictEqual(editor.option('value'), value, `editor has ${value} value`);
I think we need to check the formData.member value as well:
assert.strictEqual(form.option('formData').member, value); - it should be synchronized with the editor value

2020-06-15 12:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +        QUnit.test(`FormData = { a: true, b:  ${oldBoolValue}} -> option('formData', {})`, function() {
This config seems to be covered by

    [true, false, undefined, null, 'no member'].forEach(oldBoolValue => {
        ['no member'].forEach(newBoolValue => {

Remove?

2020-06-17 06:17 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                assert.strictEqual(form.getEditor('b').option('value'), expectedOldValue);
Fixed in https://github.com/DevExpress/DevExtreme/pull/13450/files

2020-06-17 06:17 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                assert.strictEqual(form.getEditor('b').option('value'), expectedNewValue);
Fixed in https://github.com/DevExpress/DevExtreme/pull/13450/files

2020-06-17 06:18 UTC, closed without merging

2020-06-17 06:21 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +        const $checkBox = $(editor.element());
It is jQuery method. 
I have check the existence of the dx-check-box-checked and dx-checkbox- intermediate classes to verify visual representation of the checkbox

2020-06-17 06:21 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +        QUnit.test(`FormData = { a: '1', b: ${oldValue} } -> option('formData', {})`, function(assert) {
Fixed in https://github.com/DevExpress/DevExtreme/pull/13450/files

2020-06-17 06:23 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                const expectedNewValue = newValue === 'no member' ? expectedOldValue : newValue;
Yep.
If it does not exists as field of the parameter of the updateData method? the the value does't change.

2020-06-17 06:23 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets.form/form.API.option_formData.tests.js
> +                const oldFormData = { a: '1' };
Fixed in https://github.com/DevExpress/DevExtreme/pull/13450/files