dxScheduler - add argument 'e.popup' to onAppointmentFormOpening
DevExpress/DevExtreme pull request #13421
Opened 2020-06-15 09:36 UTC by andrewmakarov

2020-06-15 12:46 UTC, RomanTsukanov requested changes

2020-06-15 12:46 UTC, RomanTsukanov commented on js/ui/scheduler.d.ts
> +    onAppointmentFormOpening?: ((e: { component?: dxScheduler, element?: dxElement, model?: any, appointmentData?: any, form: dxForm, popup: dxPopup, cancel: boolean }) => any);
The doccomment is missing the `popup` parameter.

2020-06-16 13:38 UTC, RomanTsukanov submitted a review, later dismissed
Doccomment is fine

2020-06-17 10:04 UTC, AryamnovEugeniy approved these changes

2020-06-17 10:08 UTC, AntonSermyazhko approved these changes

2020-06-17 10:53 UTC, Yarovaya approved these changes

2020-06-17 11:15 UTC, IlyaKhD requested changes
`update-ts` failed to update dx.all.d.ts properly, I will fix it in a few days

2020-06-17 11:18 UTC, IlyaKhD commented
> `update-ts` failed to update dx.all.d.ts properly, I will fix it in a few days

Actually we can merge this PR and create another one once tools are ready

2020-06-17 11:18 UTC, IlyaKhD approved these changes

2020-06-17 12:48 UTC, merged