DataGrid: editRowIndex to editRowKey refactoring
DevExpress/DevExtreme pull request #13648
Opened 2020-06-30 17:07 UTC by jtoming830

2020-07-02 13:11 UTC, vconst requested changes

2020-07-02 13:11 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                if(column.visibleIndex === this._editColumnIndex) {
visibleIndex in column is not index of rendered column. Use `columnsController.getVisibleColumns()[this,_editColumnIndex]` to get column by rendered column index

2020-07-02 13:11 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +            return dataController.getRowIndexByKey(this._editRowKey) + editRowIndexCorrection;
if editRowKey is not exist on current page and edit column is hidden the result will be incorrect

2020-07-03 14:58 UTC, vconst requested changes

2020-07-03 14:58 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +            return dataController.getRowIndexByKey(this._editRowKey) + editRowIndexCorrection;
if this._editRowKey is defined `dataController.getRowIndexByKey(this._editRowKey)` can be equal -1 if key is on another page. In this case -1 + 1 = 0.

2020-07-09 07:59 UTC, vconst submitted a review, later dismissed

2020-07-10 11:57 UTC, vconst approved these changes

2020-07-14 07:01 UTC, Alyar666 approved these changes

2020-07-14 10:51 UTC, merged