PivotGrid - ExcelJs Export. Tests for summary options
DevExpress/DevExtreme pull request #13902
Opened 2020-07-21 15:33 UTC by novsstation

Tests for summary options

2020-07-23 14:33 UTC, EugeniyKiyashko submitted a review, later dismissed

2020-07-24 14:12 UTC, IgnatovDan requested changes

2020-07-24 14:12 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/exceljsParts/exceljs.pivotGrid.tests.js
> +            { excelCell: { value: '100%', alignment: alignRightTopWrap }, pivotCell: { colspan: 1, rowspan: 1, text: '100%', value: 1, dataType: 'string', rowPath: ['r1'], columnPath: ['c1'], dataInd
For DataGrid, we exports the '0.9' numeric value and doesn't apply the '%' formatting.
The underlying pivot cell value is Number(1) in this scenario, similar to DataGrid.
But it has dataType: 'string' :-(

2020-07-27 15:13 UTC, EugeniyKiyashko approved these changes

2020-07-28 06:51 UTC, IgnatovDan approved these changes

2020-07-28 12:45 UTC, merged