DataGrid: Fix text of non-editable cell was selected on edit start (T916569)
DevExpress/DevExtreme pull request #13958
Opened 2020-07-23 16:37 UTC by jtoming830

2020-07-23 16:44 UTC, vconst requested changes

2020-07-23 16:44 UTC, vconst commented on js/ui/grid_core/ui.grid_core.utils.js
> +            if(isSelectTextOnEditingStart && !isEditingNavigationMode && $element.is('.dx-texteditor-input') && !element.readOnly) {
What is about null ref checking? Or replacing to:
`$element.is("[readOnly]")`

2020-07-24 10:24 UTC, Alyar666 approved these changes

2020-07-24 13:48 UTC, vconst approved these changes

2020-07-24 13:57 UTC, merged