Resizable - add areaLeftOffset for strict stepPrecision calculation (T919554)
DevExpress/DevExtreme pull request #14159
Opened 2020-08-08 18:16 UTC by Yarovaya

- add areaLeftOffset option in Resizable
-  use areaLeftOffset for Scheduler allDay appointments resizing

2020-08-10 13:20 UTC, andrewmakarov submitted a review, later dismissed

2020-08-11 08:16 UTC, AntonSermyazhko approved these changes

2020-08-11 08:17 UTC, DokaRus requested changes

2020-08-11 08:17 UTC, DokaRus commented on js/ui/resizable.js
> +            areaLeftOffset: 0
Let's prepare a more general solution to the problem of custom offset.

2020-08-12 07:23 UTC, closed without merging