dxPivotGrid: Add headerFilter option
DevExpress/DevExtreme pull request #1419
Opened 2017-09-28 14:07 UTC by Alyar666

2017-09-28 14:32 UTC, sometimesElen requested changes
It will be great to add test for optionChange

2017-09-29 08:02 UTC, roman-simionov requested changes
add headerFilter option for stand-alone FieldChooser (field_chooser_base.js getDefaultOptions)

2017-09-29 10:16 UTC, sometimesElen submitted a review, later dismissed

2017-10-02 07:36 UTC, sometimesElen approved these changes

2017-10-02 07:57 UTC, roman-simionov approved these changes

2017-10-02 07:57 UTC, merged