Remove DataGrid and TreeList styles from dx.common.css
DevExpress/DevExtreme pull request #14343
Opened 2020-08-24 08:51 UTC by babich-a

2020-08-24 14:23 UTC, Staziz approved these changes, later dismissed

2020-08-25 16:28 UTC, vladkovl commented on js/ui/splitter.js
> +    }
```suggestion
    _getContainerLeftOffset() {
        let offsetLeft = this._$container.offset().left;

        if(window) {
            const style = window.getComputedStyle(this._$container.get(0));
            const paddingLeft = parseFloat(style['paddingLeft']) || 0;
            const borderLeft = parseFloat(style['borderLeftWidth']) || 0;
            offsetLeft += paddingLeft + borderLeft;
        }

        return offsetLeft;
    }
```

2020-08-26 11:36 UTC, vconst requested changes

2020-08-26 11:36 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/columnsResizingReorderingModule.tests.js
> +        assert.equal(resizeController._columnsSeparatorView._testPosX, posX, 'posX of columnsSeparator'); // TODO fail
Is it comment actual?
// TODO fail

2020-08-26 15:00 UTC, vconst approved these changes

2020-08-26 15:08 UTC, vladkovl approved these changes

2020-08-26 15:44 UTC, Staziz approved these changes

2020-08-26 15:55 UTC, merged