DataGrid: Fix edit command cell was focused after edit canceling
DevExpress/DevExtreme pull request #14793
Opened 2020-10-02 08:43 UTC by jtoming830

2020-10-09 13:32 UTC, vconst requested changes

2020-10-09 13:32 UTC, vconst commented on js/ui/grid_core/ui.grid_core.keyboard_navigation.js
> +            // } else if(!this._isMasterDetailCell($target)) {
Remove comment

2020-10-12 15:54 UTC, NickMitrokhin approved these changes

2020-10-13 14:07 UTC, vconst approved these changes

2020-10-13 14:14 UTC, merged