ScrollView - Add the offset parameter to the scrollToElement method
DevExpress/DevExtreme pull request #14801
Opened 2020-10-02 13:58 UTC by jsdmitry

2020-10-02 14:29 UTC, MikeVitik requested changes

2020-10-02 14:29 UTC, MikeVitik commented on js/renovation/ui/__tests__/scroll_view.test.tsx
> +        const getOffsetValue = (parameter, offset?): number => (offset ? offset[parameter] : 0);
use jest-each

2020-10-02 14:29 UTC, MikeVitik commented on js/renovation/ui/scroll_view.tsx
> +  scrollToElement(element: HTMLElement, offset?: ScrollOffset): void {
Is it 
````
Partial<ScrollOffset>?
````

2020-10-02 14:29 UTC, MikeVitik commented on js/renovation/ui/__tests__/scroll_view.test.tsx
> +        const getOffsetValue = (parameter, offset?): number => (offset ? offset[parameter] : 0);
Try to change to (parameter: keyof ScrollOffset, offset?: ScrollOffset)

2020-10-06 12:51 UTC, MikeVitik approved these changes

2020-10-07 07:49 UTC, EugeniyKiyashko approved these changes

2020-10-07 12:26 UTC, merged