dxSpeedDialAction - Fix incorrect onClick handler is called after toggling visibility (T933671)
DevExpress/DevExtreme pull request #14953
Opened 2020-10-15 14:11 UTC by groshenkovamarina

2020-10-15 15:18 UTC, babich-a requested changes

2020-10-15 15:18 UTC, babich-a commented on js/ui/speed_dial_action/speed_dial_item.js
>          const currentActions = actions || this.option('actions');
```suggestion
        const currentActions = actions || this.option('actions')  || [];
```

2020-10-15 15:18 UTC, babich-a commented on js/ui/speed_dial_action/speed_dial_item.js
> +        return currentActions ? currentActions.filter((action) => action.option('visible')) : [];
```suggestion
        return currentActions.filter((action) => action.option('visible'));;
```

2020-10-15 15:18 UTC, babich-a commented on js/ui/speed_dial_action/speed_dial_item.js
> +        return this._getVisibleActions().length === 1 ? this._getVisibleActions()[0] : this.option('actionComponent') || this.option('actions')[0];
I suggest writing some parts of this expression to the variable or use `if` operator.

2020-10-15 15:18 UTC, babich-a commented on testing/tests/DevExpress.ui.widgets/speedDialAction.tests.js
> +        const firstClickStub = sinon.stub();
It is better to make a separate test for this scenario and mention bug id in its header. Shorts tests are better (https://devexpress.sharepoint.com/:w:/s/devextreme/ESLCAi7OVW5LtMr9C7Fwp9MB_XSSpz88U9zWhokQcrhTng?e=tSETIV)

2020-10-15 17:41 UTC, groshenkovamarina commented on js/ui/speed_dial_action/speed_dial_item.js
> +        return this._getVisibleActions().length === 1 ? this._getVisibleActions()[0] : this.option('actionComponent') || this.option('actions')[0];
Done

2020-10-15 17:42 UTC, groshenkovamarina commented on testing/tests/DevExpress.ui.widgets/speedDialAction.tests.js
> +        const firstClickStub = sinon.stub();
Done

2020-10-16 05:36 UTC, babich-a approved these changes

2020-10-16 12:21 UTC, merged