DataGrid: Fix validation frame is not updated if the repaintChangesOnly option is enabled in Cell editing mode (T914600)
DevExpress/DevExtreme pull request #14962
Opened 2020-10-16 08:47 UTC by jtoming830

2020-10-16 13:56 UTC, NickMitrokhin requested changes

2020-10-16 13:56 UTC, NickMitrokhin commented on js/ui/grid_core/ui.grid_core.editing.js
> +
Why this method is needed? Maybe it is better to put this._internalState = []; into it?

2020-10-16 13:56 UTC, NickMitrokhin commented on js/ui/grid_core/ui.grid_core.validating.js
> +                        $(cell?.cellElement).toggleClass(this.addWidgetPrefix(INVALIDATE_CLASS), false);
I think that the isCellChanged method should not change anything. 
```suggestion
                    const cellIsMarkedAsInvalid = $(cell?.cellElement).hasClass(this.addWidgetPrefix(INVALIDATE_CLASS));
                    if((oldValidationStatus !== newValidationStatus && rowIsModified) || (validationData.isValid && cellIsMarkedAsInvalid)) {
                        return true;
                    }
```

2020-10-19 13:04 UTC, NickMitrokhin approved these changes

2020-10-20 14:11 UTC, vconst approved these changes

2020-10-20 14:16 UTC, merged