DataGrid: Fix changes reset didn't work in onOptionChanged
DevExpress/DevExtreme pull request #15007
Opened 2020-10-21 15:01 UTC by jtoming830

2020-10-26 14:06 UTC, vconst requested changes

2020-10-26 14:06 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataController.tests.js
> +    QUnit.skip('edit row should not be updated on data change', function(assert) {
Change this test instead of skip.

2020-10-28 14:05 UTC, vconst approved these changes

2020-10-28 14:53 UTC, Alyar666 approved these changes

2020-10-28 14:53 UTC, merged