DataGrid: Fix error when adding new row if rowTemplate and columnAutoWidth are used (T952701)
DevExpress/DevExtreme pull request #15462
Opened 2020-11-30 09:25 UTC by jtoming830

2020-11-30 13:36 UTC, vconst requested changes

2020-11-30 13:36 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +        assert.equal(dataGrid.$element().outerWidth(), 1000, 'dataGrid width');
Add width: 1000 to dataGrid config. Now it is magic number.

2020-11-30 13:36 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +        assert.equal(dataGrid.$element().outerWidth(), 1000, 'dataGrid width');
Add width: 1000 to dataGrid config. Now it is magic number.

2020-12-01 05:44 UTC, vconst approved these changes

2020-12-01 08:31 UTC, NickMitrokhin approved these changes

2020-12-01 08:37 UTC, merged