DataGrid: Fix focus of cell on tab key press (T951849)
DevExpress/DevExtreme pull request #15478
Opened 2020-11-30 21:57 UTC by Alyar666

2020-12-07 07:19 UTC, NickMitrokhin requested changes

2020-12-07 07:19 UTC, NickMitrokhin commented on js/ui/grid_core/ui.grid_core.keyboard_navigation.js
> +                if(!interactiveElements.length || interactiveElements.last().is(eventTarget) || $cell.is(eventTarget)) {
Use **_getInteractiveElement** for getting the last interactive element in a cell.
```suggestion
                const $lastInteractiveElement = this._getInteractiveElement($cell, true);

                if(!isElementDefined($lastInteractiveElement) || $lastInteractiveElement.is(eventTarget) || $cell.is(eventTarget)) {
```

2020-12-07 09:46 UTC, NickMitrokhin approved these changes, later dismissed

2020-12-07 11:24 UTC, NickMitrokhin submitted a review, later dismissed

2020-12-11 14:49 UTC, vconst approved these changes, later dismissed

2020-12-11 15:21 UTC, NickMitrokhin submitted a review, later dismissed

2020-12-14 12:54 UTC, vconst approved these changes

2020-12-14 12:55 UTC, merged