ScrollView - generalization common parts before fix T936630
DevExpress/DevExtreme pull request #15578
Opened 2020-12-07 10:09 UTC by EugeniyKiyashko

2020-12-09 06:52 UTC, novsstation submitted a review, later dismissed

2020-12-09 15:49 UTC, IgnatovDan requested changes

2020-12-09 15:49 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/scrollableParts/scrollable.api.tests.js
> +        const expectedScrollOffsetLeft = left;
Excessive? It's a new variable but it is used one time.

2020-12-09 15:49 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/scrollableParts/scrollable.api.tests.js
> +        QUnit.assert.roughEqual(this.scrollable.scrollLeft(), left, epsilon, message || 'scrollable.scrollLeft()');
Is 'message' excessive? It's a function argument but it is used for the 'scrollLeft()' only

2020-12-09 15:49 UTC, IgnatovDan commented on js/ui/scroll_view/ui.scrollable.js
> +        const { top, left } = this._location();
imho it's too little change

2020-12-09 16:03 UTC, IgnatovDan approved these changes, later dismissed

2020-12-10 09:28 UTC, novsstation approved these changes

2020-12-10 10:14 UTC, merged