DataGeid PDF Export - Print Info Calculator - Simple cases: table pos/width, cell coordinates
DevExpress/DevExtreme pull request #15799
Opened 2020-12-21 18:40 UTC by KuznetsovVN

2020-12-23 07:41 UTC, novsstation commented on js/exporter/jspdf/export_print_info_calculator.js
> +        margin.top = margin.top ?? margin.all;
Is the "all" option really needed?

2020-12-23 08:41 UTC, novsstation submitted a review, later dismissed

2020-12-23 10:19 UTC, EugeniyKiyashko approved these changes

2020-12-23 12:45 UTC, novsstation approved these changes

2020-12-29 13:39 UTC, IgnatovDan requested changes

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +            margin,
imho it's better to sync our API with jsPdf.text: 
`doc.text("Hello world!", 10, 10);`
http://raw.githack.com/MrRio/jsPDF/master/docs/jsPDF.html#text

The doc.text will be used to create header/footer/left/right notes and it doesn't provide 'margin' in root args.

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +            startY,
http://raw.githack.com/MrRio/jsPDF/master/docs/jsPDF.html#text

doc.text calls these arguments 'X,Y' without the 'start' prefix

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +        cells[0]?.forEach((cell, _) => {
Why cell.colSpan is calculated from cells[0] only ? Is it Header cells? Or Data cells? How empty grid will be processed?

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +        }
```
else {
    add an error message to console
}
```

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +                const yPos = lastRowYPos;
xPos  -> cellLeft/cellX
yPos -> cellTop/cellY

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +        let lastRowYPos = y;
lastRowYPos -> lastRowTop/lastRowY

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +                const colStyles = columnStyles[colIndex];
colStyles -> currentColumnStyles

2020-12-29 13:39 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                assert.strictEqual(calculatedOptions.columnStyles[0], undefined, 'columnStyles[0]');
assert is not clear
may be it should be "assert.strictEqual(calculatedOptions.columnStyles.length, 0, 'columnStyles.length');" ?

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +            columnAutoWidth = unAllocatedWidth / (columnCount - columnsWithAssignedWidth.length);
(columnCount - columnsWithAssignedWidth.length) - can it be '0'?

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +    _defaultMinCellHeight: 10,
10 ? cm/mm/in/pt?

2020-12-29 13:39 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                const startY = calculatedOptions.startX;
calculatedOptions.startX -> calculatedOptions.startY ?

2020-12-29 13:39 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdfTestHelper.js
> +            const width = columnStyles[i] ? columnStyles[i].width : 0;
For a separate TablePrinter (width === undefined/null) should mean 'auto'.
IMHO we should change this.
And, it' not clear which class should make this choice: calculator or printer?

2020-12-29 13:39 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                const done = assert.async();
IHMO we should not use 'async()' just to make test safe if it doesn't wait for a promise.

2020-12-29 13:39 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                const columnWidth = calculatedOptions.tableWidth / 2;
It's better to set explicit tableWidth in tests and add few additional tests to check how it is automatically calculated.

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +    _calculateTableWidth: function(jsPDFDocument, leftIndent, rightIndent) {
I think we should postpone automatic tableWidth calculation and work without it for several sprints: it's easy to specify it explicitly and we can declare this value as required at the current stage.

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +                columnStyles[i].width = columnAutoWidth;
I think we should postpone automatic columnWidth calculation and work without it for several sprints: it's easy to specify it explicitly and we can declare this value as required at the current stage.

2020-12-29 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_print_info_calculator.js
> +                columnStyles[i].minCellHeight = this._defaultMinCellHeight;
I think we should postpone automatic rowHeight calculation and work without it for several sprints: it's easy to specify it explicitly and we can declare this value as required at the current stage.

2020-12-29 13:39 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                        1: { width: 70, minCellHeight: 20 }
There should be one property to declare height for entire row

2020-12-30 06:59 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +    _defaultMinCellHeight: 10,
This means the measurement unit, which the customer is defined in jsPDF instance.
As well as in the autoTable plugin, in our approach I will use constants.
In the future, this constant can be replaced by getFonSize() value.

2020-12-30 06:59 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +            margin,
Margin is a padding for the page. What you mean here?
Clarify please.

2020-12-30 06:59 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +            startY,
This variables are used for the starting position for the table. For customer's cases.

2020-12-30 07:00 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +        cells[0]?.forEach((cell, _) => {
The total number of columns is determined by the number of cells in the first row. If the number of columns for each row is different, then this is already incorrect data. For empty grid the number of columns must be zero.

2020-12-30 07:00 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +            columnAutoWidth = unAllocatedWidth / (columnCount - columnsWithAssignedWidth.length);
> can it be '0'?
maybe, we can add this check

2020-12-30 07:01 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +                const colStyles = columnStyles[colIndex];
yes, we can rename this variable

2020-12-30 07:01 UTC, KuznetsovVN commented on js/exporter/jspdf/export_print_info_calculator.js
> +                const yPos = lastRowYPos;
ok

2020-12-30 07:07 UTC, KuznetsovVN commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                assert.strictEqual(calculatedOptions.columnStyles[0], undefined, 'columnStyles[0]');
'columnStyles' is not an array and has no length property. I think we need to add the 'checkColumnWidths' method to the Helper object and check it there.

2020-12-30 07:08 UTC, KuznetsovVN commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf.printInfoCalculator.tests.js
> +                const startY = calculatedOptions.startX;
yes, there is a typo

2021-01-12 15:33 UTC, closed without merging