DataGrid: remove rowIndex from insertInfo
DevExpress/DevExtreme pull request #15870
Opened 2020-12-24 14:09 UTC by jtoming830

2020-12-30 11:39 UTC, vconst requested changes

2020-12-30 11:39 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +            const index = change ? changes.filter(editChange => editChange.key === key)[0].index : 0;
key may be complex

2021-01-11 11:05 UTC, NickMitrokhin approved these changes, later dismissed

2021-01-11 15:30 UTC, vconst requested changes

2021-01-11 15:30 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +        _addInsertInfo: function(change = {}) {
Why is default value {} is here if change is always passed to _addInsertInfo?

2021-01-11 15:30 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +            change.pageIndex = change.pageIndex ?? dataController.pageIndex();
Move change properties modification (index, pageIndex) from _createInsertInfo method to _addInsertInfo. The _createInsertInfo method will be cleaner.

2021-01-11 15:30 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
>                  key = String(new Guid());
Why key is not added to change here but key adds to change after each _addInsertInfo call?

2021-01-12 10:12 UTC, NickMitrokhin approved these changes

2021-01-12 12:00 UTC, vconst requested changes

2021-01-12 12:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    change.pageIndex = Math.floor(change.index / dataController.pageSize());
What is about infinite scrolling? It is very similar to virtual during paging.

2021-01-12 12:03 UTC, vconst approved these changes

2021-01-12 12:57 UTC, merged