Resolve some Or and Nullish coalescing
DevExpress/DevExtreme pull request #15918
Opened 2020-12-30 12:07 UTC by alexander-kotov-dx

2021-01-11 08:49 UTC, ksercs requested changes

2021-01-11 08:49 UTC, ksercs commented on js/ui/load_indicator.js
> -        this._updateContentSizeForAnimation();
imho, we should not remove this function. It will be called after `width` runtime option change for example

2021-01-11 08:52 UTC, ksercs commented
Let's change our [isDefined](https://github.com/DevExpress/DevExtreme/blob/21_1/js/core/utils/type.js#L27) function call will nullish coalescing?

2021-01-11 18:16 UTC, ksercs approved these changes

2021-01-12 09:10 UTC, DokaRus approved these changes

2021-01-12 10:36 UTC, merged