TreeList: Fix getSelectedRowKeys("all") method in selection recursive mode (T968433, T968435)
DevExpress/DevExtreme pull request #16245
Opened 2021-02-01 22:07 UTC by Alyar666

2021-02-02 08:58 UTC, jtoming830 commented on js/ui/tree_list/ui.tree_list.selection.js
> +const getSelectedChildKeys = function(that, key, keysToIgnore, deep) {
Why global?

2021-02-02 08:59 UTC, jtoming830 commented on js/ui/tree_list/ui.tree_list.selection.js
> +const normalizeChildrenKeys = function(that, key, selectedRowKeys) {
And why is this global? (if cause is different from previous)

2021-02-02 09:01 UTC, jtoming830 commented on js/ui/tree_list/ui.tree_list.selection.js
> +const getSelectedChildKeys = function(that, key, keysToIgnore, deep) {
Also maybe use object as parameter?

2021-02-02 10:22 UTC, jtoming830 commented on js/ui/tree_list/ui.tree_list.selection.js
> +                    let keysToIgnore = keys.slice();
You _can_ use spread operator here, if you want.

2021-02-02 10:30 UTC, jtoming830 commented on testing/tests/DevExpress.ui.widgets.treeList/selection.tests.js
> +            /* eslint-disable */
`/* eslint-disable indent */` should be enough.

2021-02-05 09:06 UTC, vconst requested changes

2021-02-05 09:06 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.treeList/selection.tests.js
> +            /* eslint-disable */
You skipped adding "indent" here.

2021-02-05 09:09 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.treeList/selection.tests.js
> +            /* eslint-disable */
Also, eslint-disable disable something globally in the file. Do you want really disable eslint indent check in the whole file?

2021-02-05 12:00 UTC, vconst approved these changes

2021-02-08 10:13 UTC, merged