DataGrid.Pdf - Split grid into pages
DevExpress/DevExtreme pull request #16275
Opened 2021-02-03 15:55 UTC by KuznetsovVN

2021-02-08 08:26 UTC, IgnatovDan requested changes

2021-02-08 08:26 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.tests.js
> +    QUnit.test('Split gird on one page, 1 col - draw table borders', function(assert) {
gird - grid

2021-02-08 08:26 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.tests.js
> +    QUnit.test('Split gird on one page, 1 col', function(assert) {
gird -> grid

2021-02-08 13:53 UTC, IgnatovDan approved these changes

2021-02-09 08:09 UTC, EugeniyKiyashko approved these changes

2021-02-09 08:28 UTC, novsstation approved these changes

2021-02-09 09:33 UTC, merged