Renovation: Rename Preact by Inferno
DevExpress/DevExtreme pull request #16460
Opened 2021-02-20 14:55 UTC by LazyLahtak

2021-02-25 07:29 UTC, vconst approved these changes, later dismissed

2021-02-25 07:58 UTC, vconst submitted a review, later dismissed

2021-02-25 09:58 UTC, MikeVitik requested changes

2021-02-25 09:58 UTC, MikeVitik commented on js/renovation/inferno_wrapper/__tests__/utils/test_components/base_test_widget.ts
> +  _renderInferno(props: any): void {
Can we use simple _render( without Inferno or Preact?

2021-02-25 09:58 UTC, MikeVitik commented on js/renovation/inferno_wrapper/__tests__/utils/test_components/inferno_test_widget.tsx
> +export default class InfernoTestWidget extends JSXComponent(InfernoTestWidgetProps) {
Can we rename it in something more neutral. RenovationTestWidget, or simple TestWidget

2021-02-25 09:58 UTC, MikeVitik commented on js/renovation/inferno_wrapper/__tests__/utils/test_components/inferno_test_widget.tsx
> +  getLastInfernoReceivedProps(): InfernoTestWidgetProps {
The same here. Can we omit Inferno?

2021-02-25 09:58 UTC, MikeVitik commented on js/renovation/inferno_wrapper/component.ts
> +export default class InfernoWrapper extends DOMComponent {
Can we rename it in something more neutral? JQueryWrapper

2021-02-25 09:58 UTC, MikeVitik commented on js/renovation/inferno_wrapper/component.ts
> +  _infernoReplaced!: boolean;
Omit inferno

2021-03-01 08:17 UTC, MikeVitik submitted a review, later dismissed

2021-03-01 11:06 UTC, vconst approved these changes

2021-03-01 11:42 UTC, merged