ScrollView - Scrolling does not work when nested in another ScrollView that has useNative enabled (T977318)
DevExpress/DevExtreme pull request #16704
Opened 2021-03-16 15:17 UTC by EugeniyKiyashko

2021-03-17 12:21 UTC, IgnatovDan requested changes, later dismissed

2021-03-17 12:21 UTC, IgnatovDan commented on scss/widgets/base/_scrollable.scss
>      display: none;
I think we need a new test

2021-03-19 09:18 UTC, EugeniyKiyashko commented on scss/widgets/base/_scrollable.scss
>      display: none;
Fixed in 33b9c36

2021-03-19 09:19 UTC, novsstation approved these changes

2021-03-19 10:08 UTC, merged