TreeView - fix selection of the hidden node (T982103)
DevExpress/DevExtreme pull request #16721
Opened 2021-03-18 10:22 UTC by novsstation

Bugfix T982103

2021-03-19 10:18 UTC, EugeniyKiyashko approved these changes, later dismissed

2021-03-19 15:02 UTC, IgnatovDan requested changes

2021-03-19 15:02 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/treeViewParts/selection.js
> +                    { id: 1, text: 'item1', selected: true },
There can be these combinations for two {visible,selected} items and selectItem call:

1. "[{visible: false, selected: false}, {visible: false, selected: false}] -> selectItem(0)"
1. "[{visible: false, selected: false}, {visible: false, selected: false}] -> selectItem(1)"
1. "[{visible: false, selected: false}, {visible: false, selected: true}] -> selectItem(0)"
1. "[{visible: false, selected: false}, {visible: false, selected: true}] -> selectItem(1)"
1. "[{visible: false, selected: false}, {visible: true, selected: false}] -> selectItem(0)"
1. "[{visible: false, selected: false}, {visible: true, selected: false}] -> selectItem(1)"
1. "[{visible: false, selected: false}, {visible: true, selected: true}] -> selectItem(0)"
1. "[{visible: false, selected: false}, {visible: true, selected: true}] -> selectItem(1)"


1. "[{visible: false, selected: true}, {visible: false, selected: false}] -> selectItem(0)"
1. "[{visible: false, selected: true}, {visible: false, selected: false}] -> selectItem(1)"
1. "[{visible: false, selected: true}, {visible: false, selected: true}] -> selectItem(0)"
1. "[{visible: false, selected: true}, {visible: false, selected: true}] -> selectItem(1)"
1. "[{visible: false, selected: true}, {visible: true, selected: false}] -> selectItem(0)"
1. "[{visible: false, selected: true}, {visible: true, selected: false}] -> selectItem(1)"
1. "[{visible: false, selected: true}, {visible: true, selected: true}] -> selectItem(0)"
1. "[{visible: false, selected: true}, {visible: true, selected: true}] -> selectItem(1)"


1. "[{visible: true, selected: false}, {visible: false, selected: false}] -> selectItem(0)"
1. "[{visible: true, selected: false}, {visible: false, selected: false}] -> selectItem(1)"
1. "[{visible: true, selected: false}, {visible: false, selected: true}] -> selectItem(0)"
1. "[{visible: true, selected: false}, {visible: false, selected: true}] -> selectItem(1)"
1. "[{visible: true, selected: false}, {visible: true, selected: false}] -> selectItem(0)"
1. "[{visible: true, selected: false}, {visible: true, selected: false}] -> selectItem(1)"
1. "[{visible: true, selected: false}, {visible: true, selected: true}] -> selectItem(0)"
1. "[{visible: true, selected: false}, {visible: true, selected: true}] -> selectItem(1)"


1. "[{visible: true, selected: true}, {visible: false, selected: false}] -> selectItem(0)"
1. "[{visible: true, selected: true}, {visible: false, selected: false}] -> selectItem(1)"
1. "[{visible: true, selected: true}, {visible: false, selected: true}] -> selectItem(0)"
1. "[{visible: true, selected: true}, {visible: false, selected: true}] -> selectItem(1)"
1. "[{visible: true, selected: true}, {visible: true, selected: false}] -> selectItem(0)"
1. "[{visible: true, selected: true}, {visible: true, selected: false}] -> selectItem(1)"
1. "[{visible: true, selected: true}, {visible: true, selected: true}] -> selectItem(0)"
1. "[{visible: true, selected: true}, {visible: true, selected: true}] -> selectItem(1)"

Inner implementation is too complex to check getSelectedNodeKeys/getSelectedNodes result before and after selectItem is called in these configs but each should work with an expected result.

TreeView is used in our AT and imho we need more tests for initial render and selectItem result in various configs.

2021-03-22 07:16 UTC, novsstation commented on testing/tests/DevExpress.ui.widgets/treeViewParts/selection.js
> +                    { id: 1, text: 'item1', selected: true },
Yep, added new test cases https://github.com/DevExpress/DevExtreme/pull/16721/commits/1224091d270b221cb849f92418325f44e5856e1c

2021-03-22 07:45 UTC, EugeniyKiyashko approved these changes

2021-03-22 08:16 UTC, IgnatovDan approved these changes

2021-03-22 08:16 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/treeViewParts/selection.js
> +            const result = config.action(wrapper.instance);
I think we it's a good place to check how initial options were processing: check "checkSelectedKeys" before the "action()" call.

2021-03-22 09:36 UTC, merged