DataGrid - Fixes focusing non editable cell (T983590)
DevExpress/DevExtreme pull request #16800
Opened 2021-03-23 14:15 UTC by NickMitrokhin

2021-03-23 15:54 UTC, jtoming830 requested changes

2021-03-23 15:54 UTC, jtoming830 commented on testing/tests/DevExpress.ui.widgets.dataGrid/focus.integration.tests.js
> +    QUnit.testInActiveWindow('Cell - An editable invalid cell should not lose focus when other cells are cicked (T983590)', function(assert) {
typo - 'other cells are **cicked**'

2021-03-23 15:54 UTC, jtoming830 requested changes

2021-03-23 15:54 UTC, jtoming830 commented on testing/tests/DevExpress.ui.widgets.dataGrid/focus.integration.tests.js
> +    QUnit.testInActiveWindow('Cell - An editable invalid cell should not lose focus when other cells are cicked (T983590)', function(assert) {
```suggestion
    QUnit.testInActiveWindow('Cell - An editable invalid cell should not lose focus when other cells are clicked (T983590)', function(assert) {
```

2021-03-24 11:50 UTC, jtoming830 approved these changes, later dismissed

2021-03-25 12:48 UTC, jtoming830 approved these changes

2021-03-25 15:24 UTC, vconst approved these changes

2021-03-25 15:30 UTC, merged