PivotGrid - Scroll position is wrong after expanding/collapsing node, if virtual mode is enabled
DevExpress/DevExtreme pull request #16845
Opened 2021-03-26 11:40 UTC by novsstation

Bugfix T984139

2021-03-31 21:06 UTC, EugeniyKiyashko submitted a review, later dismissed

2021-04-02 08:34 UTC, KuznetsovVN submitted a review, later dismissed

2021-04-05 06:37 UTC, EugeniyKiyashko approved these changes, later dismissed

2021-04-05 07:19 UTC, IgnatovDan requested changes

2021-04-05 07:19 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +                const expectedRowCellRect = getHeaderCellByText($rowsHeaderArea, expected.row.toString()).getBoundingClientRect();
expected.row.toString() -> expectedRowText ?

2021-04-05 07:19 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +            function checkLeftTopVisibleHeaderCellTexts(pivotGrid, expected, message) {
checkLeftTopVisibleHeaderCellTexts(pivotGrid -> imho it's clear what it means,
expected -> expectedRowHeaderText + expectedColHeaderText ?, 
message -> errorMessageDetails?
)

2021-04-05 07:19 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +                const expectedColumnCellRect = getHeaderCellByText($columnsHeaderArea, expected.column.toString()).getBoundingClientRect();
Can we use 'elementFromPoint' instead?
Store {top, left} of the scrollable area and use elementFromPoint to get {top + 1, left + 1} to get the top/left visible cell:
document.elementFromPoint($('.dx-area-data-cell')[0].getBoundingClientRect().left + 1, $('.dx-area-data-cell')[0].getBoundingClientRect().top + 1).innerText - it's "$450" in ticket steps when "$2,410" is expected

2021-04-05 07:19 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +                tryTriggerScrollEventAndWait(scrollable, this.clock);
Why test code should manually trigger 'scroll' after 'expandHeaderItem'?
Can test code call a method that executes all the necessary code?

2021-04-05 07:20 UTC, IgnatovDan requested changes

2021-04-05 07:20 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +                const expectedRow = 60;
expectedRowHeaderCellText ?

2021-04-05 07:20 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +                const expectedColumn = area === 'row' ? 57 : 46;
expectedColHeaderCellText?

2021-04-05 12:28 UTC, EugeniyKiyashko approved these changes

2021-04-05 14:44 UTC, KuznetsovVN approved these changes

2021-04-06 05:16 UTC, IgnatovDan approved these changes

2021-04-06 05:53 UTC, merged