Actualize data visualization palettes/themes according to the new generic color schemes
DevExpress/DevExtreme pull request #1685
Opened 2017-10-24 13:20 UTC by BingoRUS

2017-10-24 14:40 UTC, pavelgruba requested changes
Please list newly added palettes as accepted values for CommonVizPalette option.

2017-10-24 14:56 UTC, BingoRUS commented
@pavelgruba yeah thank you, forgot to update the accepted values.

2017-10-24 15:10 UTC, roman-simionov commented on js/viz/core/themes/generic.darkmoon.js
> +    },
funnel: {
        item: {
            border: {
                color: "#465672"
            }
        }
    }

2017-10-24 15:11 UTC, roman-simionov commented on js/viz/core/themes/generic.darkviolet.js
> +    }
`funnel: {
        item: {
            border: {
                color: "#465672"
            }
        }
    }`

2017-10-24 15:28 UTC, roman-simionov approved these changes

2017-10-25 09:49 UTC, BingoRUS commented
@pavelgruba All additions are pushed, take a look, please.

2017-10-25 14:03 UTC, pavelgruba approved these changes

2017-10-25 14:06 UTC, merged