DataGrid: Add editing.changes interface
DevExpress/DevExtreme pull request #16873
Opened 2021-03-29 16:24 UTC by jtoming830

2021-03-30 06:55 UTC, NickMitrokhin submitted a review, later dismissed

2021-03-30 10:13 UTC, vconst approved these changes

2021-03-30 10:14 UTC, vconst requested changes
Tests are not passed.

2021-04-01 13:49 UTC, NickMitrokhin approved these changes

2021-04-01 14:07 UTC, vconst approved these changes

2021-04-01 14:08 UTC, merged