Text Editors - Add animated labels
DevExpress/DevExtreme pull request #16937
Opened 2021-04-05 07:55 UTC by groshenkovamarina

2021-04-06 09:21 UTC, alexander-kotov-dx reviewed
no top border above the editor buttons
![no-top-border](https://user-images.githubusercontent.com/23214056/113688976-7bd83e80-96d2-11eb-8823-a5c0c04726d9.png)

2021-04-06 09:22 UTC, alexander-kotov-dx requested changes
no place for label for selectBox in Generic theme
![selectbox-label](https://user-images.githubusercontent.com/23214056/113689233-c5288e00-96d2-11eb-8171-a8848fc7cecd.png)

2021-04-06 09:33 UTC, alexander-kotov-dx reviewed
We should describe new options in d.ts

2021-04-06 09:33 UTC, alexander-kotov-dx commented on js/ui/text_box/ui.text_editor.base.js
> +        this._renderLabel();
Is it necessary?

2021-04-06 09:33 UTC, alexander-kotov-dx commented on js/ui/text_box/ui.text_editor.base.js
> +        this._renderLabel();
initMarkup changes should be tested in serverSide tests (markup.tests.js)

2021-04-06 09:33 UTC, alexander-kotov-dx commented on testing/tests/DevExpress.ui.widgets.editors/textEditorParts/common.tests.js
> +        textEditor.option('label', 'label');
Please use the separate test for every test scenario

2021-04-06 09:40 UTC, alexander-kotov-dx reviewed
Colorbox without value has wrong label position
![colorbox-without-value](https://user-images.githubusercontent.com/23214056/113691531-2ea99c00-96d5-11eb-9b7a-238bbd35337a.png)

2021-04-06 09:48 UTC, alexander-kotov-dx reviewed
label position looks strange in this scenario
![vertical-position](https://user-images.githubusercontent.com/23214056/113692589-5d744200-96d6-11eb-9b01-ba589b4d5646.png)

2021-04-06 09:52 UTC, alexander-kotov-dx commented on js/ui/text_box/ui.text_editor.base.js
> +        this.$element().removeClass(TEXTEDITOR_WITH_FLOATING_LABEL_CLASS);
this.$element()
    .removeClass(TEXTEDITOR_WITH_LABEL_CLASS)
    .removeClass(TEXTEDITOR_WITH_FLOATING_LABEL_CLASS);

2021-04-06 10:04 UTC, alexander-kotov-dx commented on js/ui/text_box/ui.text_editor.base.js
> +        const $label = this._$label = $('<div>')
const $labelText = $('<span>').text(this.option('label'));
this._$label = $('<div>')
    .addClass(TEXTEDITOR_LABEL_CLASS)
    .append($labelText)

this._$label.appendTo(this._$textEditorInputContainer);

?

2021-04-06 11:14 UTC, alexander-kotov-dx commented
I think the label should not change position if the editor has readOnly option

2021-04-06 11:29 UTC, alexander-kotov-dx commented
Wrong label position for editors with custom height
![custom-height](https://user-images.githubusercontent.com/23214056/113704125-6b30c400-96e4-11eb-92ab-bab767a925f6.png)

2021-05-20 13:23 UTC, babich-a requested changes
There are no changes in ts declarations. 'label' and 'labelMode' options won't work in modular approaches

2021-09-08 08:23 UTC, DokaRus commented on js/ui/text_box/ui.text_editor.base.js
> +            $label.appendTo($textEditorInputContainer);
Why not extract the label as a separate component to which to pass the required parameters?

Using a descendant component in a base component doesn't look good

2021-09-30 13:00 UTC, closed without merging