TreeView - fix selection changed event raised twice (T988753)
DevExpress/DevExtreme pull request #17025
Opened 2021-04-12 08:41 UTC by novsstation

Bugfix T988753

2021-04-12 10:19 UTC, novsstation commented on js/ui/tree_view/ui.tree_view.base.js
> -            this._$selectAllItem.dxCheckBox('instance').option('value', this._dataAdapter.isAllSelected());
_updateItemsUI must only update UI. It should not fire events

2021-04-12 16:30 UTC, IgnatovDan requested changes

2021-04-12 16:30 UTC, IgnatovDan commented on js/ui/tree_view/ui.tree_view.base.js
> +            selectAllCheckbox.repaint();
Similar to React: rerender component if its state was changed.

2021-04-12 16:30 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/treeViewParts/checkboxes.js
> +        onSelectAllValueChanged: (args) => { eventValue = args.value; }
Whether 'selectAllValueChangedLog' will be better to track event calls?

2021-04-12 16:30 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/treeViewParts/checkboxes.js
> +            QUnit.test(`Click by checkbox. checkboxMode: ${showCheckBoxesMode}, selectionMode: ${selectionMode}, recursive: ${selectNodesRecursive} (T988753)`, function() {
"All selected -> deselect middle level item" - rename?

2021-04-13 07:23 UTC, IgnatovDan requested changes

2021-04-13 07:23 UTC, IgnatovDan commented on js/ui/tree_view/ui.tree_view.base.js
> +    _getSelectAllCheckbox: function() {
imho it doesn't worth it to add such little methods

2021-04-15 11:52 UTC, IgnatovDan approved these changes

2021-04-15 11:52 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/treeViewParts/checkboxes.js
> +        [false, true].forEach((selectNodesRecursive) => {
Also, there is the https://js.devexpress.com/Documentation/21_1/ApiReference/UI_Components/dxTreeView/Configuration/#selectByClick option but I am not sure that we have to add tests for the same selection events in this PR

2021-04-15 12:39 UTC, merged