TreeView - fix "this._selectAllValueChangedAction is not a function" (T988756)
DevExpress/DevExtreme pull request #17031
Opened 2021-04-12 12:31 UTC by novsstation

Bugfix T988756

2021-04-13 06:18 UTC, IgnatovDan requested changes

2021-04-13 06:18 UTC, IgnatovDan commented on testing/tests/DevExpress.ui.widgets/treeViewParts/checkboxes.js
> +['normal', 'none'].forEach((showCheckBoxesMode) => {
imho two separate tests are easier to understand than ['normal', 'none'].forEach

2021-04-15 11:59 UTC, IgnatovDan submitted a review, later dismissed

2021-04-15 14:30 UTC, EugeniyKiyashko approved these changes

2021-04-15 14:31 UTC, KuznetsovVN approved these changes

2021-04-15 14:32 UTC, merged