CheckBox: add getter for viewModel.target.current for normal generating angular component
DevExpress/DevExtreme pull request #17056
Opened 2021-04-13 16:14 UTC by Zedwag

2021-04-13 16:35 UTC, ksercs requested changes, later dismissed

2021-04-13 16:35 UTC, ksercs commented on js/renovation/ui/check_box.tsx
> +  get targetCurrent(): HTMLDivElement | null {
We should also add test for this getter

2021-04-15 07:15 UTC, pavelgruba approved these changes

2021-04-15 15:39 UTC, ksercs approved these changes

2021-04-15 15:58 UTC, merged