Renovated DataGrid: Fix QUnit tests (part 3)
DevExpress/DevExtreme pull request #17083
Opened 2021-04-15 10:52 UTC by Alyar666

2021-04-15 11:03 UTC, vconst submitted a review, later dismissed

2021-04-15 13:25 UTC, vconst submitted a review, later dismissed

2021-04-15 13:36 UTC, MikeVitik requested changes

2021-04-15 13:36 UTC, MikeVitik commented on js/renovation/ui/grids/data_grid/common/data_grid_view_props.ts
> +  @OneWay() showBorders!: boolean;
Re-export showBorders like in https://github.com/MikeVitik/DevExtreme/blob/27500a0cf0f8a74d9196e9675efb7d4fbcc53dd9/js/renovation/ui/pager/pages/large.tsx#L93

2021-04-16 13:23 UTC, LazyLahtak approved these changes

2021-04-16 13:53 UTC, vconst approved these changes

2021-04-16 15:06 UTC, MikeVitik approved these changes

2021-04-16 15:08 UTC, merged