Form - simple layout manager implementation
DevExpress/DevExtreme pull request #17147
Opened 2021-04-20 08:09 UTC by novsstation

2021-04-20 10:12 UTC, EugeniyKiyashko commented on js/renovation/ui/form/form_layout_manager.tsx
> +  jQuery: { register: true },
Shall we register layout manager?

2021-04-20 10:15 UTC, novsstation commented on js/renovation/ui/form/form_layout_manager.tsx
> +  jQuery: { register: true },
Sorry, it's my fault

2021-04-21 14:21 UTC, IgnatovDan requested changes

2021-04-21 14:21 UTC, IgnatovDan commented on js/renovation/ui/form/__tests__/form_layout_manager.test.tsx
> +import React from 'react';
Is 'React' used?

2021-04-21 15:14 UTC, novsstation commented on js/renovation/ui/form/__tests__/form_layout_manager.test.tsx
> +import React from 'react';
Yep, otherwise there will be a warning
![image](https://user-images.githubusercontent.com/57402891/115577728-5439c680-a2cd-11eb-94b9-c9dd4ead26d4.png)

2021-04-21 17:25 UTC, IgnatovDan approved these changes

2021-04-22 07:18 UTC, merged