dxFilterBuilder: Add onValueChanged event
DevExpress/DevExtreme pull request #1724
Opened 2017-10-26 11:23 UTC by Alyar666

2017-10-26 13:43 UTC, lukyanovas commented on js/ui/filter_builder/filter_builder.js
> +            * @name dxFilterBuilderOptions_onValueChanged
* @name dxFilterBuilderOptions_onValueChanged
            * @publicName onValueChanged
            * @extends Action
            * @type function(e)
            * @type_function_param1 e:object
            * @type_function_param1_field4 value:object
            * @type_function_param1_field5 previousValue:object
            * @action
            */

2017-10-26 13:44 UTC, lukyanovas requested changes
update doc-comment

2017-10-27 07:34 UTC, lukyanovas submitted a review, later dismissed

2017-10-27 08:59 UTC, komarovalexander approved these changes

2017-10-27 09:06 UTC, merged