Renovation: add DraggableContainer component
DevExpress/DevExtreme pull request #17405
Opened 2021-05-07 11:59 UTC by Alyar666

2021-05-11 08:06 UTC, MikeVitik approved these changes, later dismissed

2021-05-11 09:43 UTC, churkin submitted a review, later dismissed

2021-05-11 15:49 UTC, vconst requested changes

2021-05-11 15:49 UTC, vconst commented on js/renovation/ui/draggable/__tests__/container.test.tsx
> +describe('DataGrid', () => {
DataGrid?

2021-05-12 07:49 UTC, vconst approved these changes

2021-05-12 08:44 UTC, merged