DataGrid.Pdf - Grouping, Indents and Backgrounds
DevExpress/DevExtreme pull request #17621
Opened 2021-05-25 09:03 UTC by KuznetsovVN

2021-06-03 13:39 UTC, IgnatovDan requested changes

2021-06-03 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/draw_pdf_table.js
> +                doc.setFillColor(cell.backgroundColor);
Let's move 'cell background' to a separate PR

2021-06-03 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_data_grid_2.js
> +                let rowType;
let -> const?

2021-06-03 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_data_grid_2.js
> +                        const prevCellsHaveSummaryItems = currentRow.slice(1).filter(pdfCell => isDefined(pdfCell.text)).length > 0;
Let's move 'group totals' to a separate PR

2021-06-03 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_data_grid_2.js
> +                rowsIndents.push(groupLevel * 10); // TODO: Default value for horizontalIndent : 10
Let's add 'indent' into 'options' with 10 as the default value

2021-06-03 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/export_data_grid_2.js
> +                        startNewTableWithIndent = false;
Let's move 'support group indents between pages' to a separate PR

2021-06-03 13:39 UTC, IgnatovDan commented on js/exporter/jspdf/pdf_grid.js
> +            this._columnWidths[0] = firstColumnWidth;
Is it possible to avoid changes in _columnWidths?

2021-06-04 10:39 UTC, IgnatovDan requested changes

2021-06-04 10:39 UTC, IgnatovDan commented on js/exporter/jspdf/pdf_grid.js
> +            new PdfTable(drawTableBorder, firstTableTopLeft, this._columnWidths.slice(0, firstTableEndColumnIndex), firstColumnWidth)
const tableColumnWidths = this._columnWidths.slice(0, firstTableEndColumnIndex);
tableColumnWidths[0] = firstColumnWidth;
this._currentHorizontalTables = [new PdfTable(drawTableBorder, firstTableTopLeft, tableColumnWidths)];

?

2021-06-04 10:39 UTC, IgnatovDan commented on js/exporter/jspdf/pdf_table.js
> +        this.columnWidths = columnWidths.slice(0); // TODO
Implement before "new PdfTable" ?

2021-06-08 10:49 UTC, novsstation submitted a review, later dismissed

2021-06-08 12:22 UTC, IgnatovDan requested changes

2021-06-08 12:22 UTC, IgnatovDan commented on js/exporter/jspdf/export_data_grid_2.js
> +    options.indent = options.indent || 10;
Imho Number(0) should be available:
`isDefined(options.indent) ? options.indent : 10; `
Initialize it in _getFullOptions?

2021-06-08 14:45 UTC, IgnatovDan approved these changes

2021-06-09 06:48 UTC, novsstation approved these changes

2021-06-09 07:10 UTC, EugeniyKiyashko approved these changes

2021-06-09 07:13 UTC, merged