DataGrid - Remove code for ie
DevExpress/DevExtreme pull request #17744
Opened 2021-06-02 10:15 UTC by pomah33

Trello card: https://trello.com/c/9EauINT1/5786-remove-the-code-for-ie-from-sources-in-212

I removed all code that is connected with IE (I searched for `msie` prop to find it) and also removed some methods and vars that was only used in that parts of code

So behaviors for MS browsers are:

- IE — not supported
- Edge Legacy (which is using old edgeHTML engine, so `browser.msie` is `true`) — not supported. Is it supposed to be that way?
- Edge —  supported, `browser.chrome` is `true`

2021-06-07 07:45 UTC, NickMitrokhin commented
It seems that not all files was processed. The following files with corresponding line numbers contain ".msie":
js\ui\grid_core\ui.grid_core.virtual_scrolling.js - 786
testing\helpers\grid\getPointsByColumnsHelper.js - 5
testing\tests\DevExpress.ui.widgets\sortable.tests.js - 229, 245, 252, 433
testing\tests\DevExpress.ui.widgets.dataGrid\adaptiveColumns.integration.tests.js - 157, 314
testing\tests\DevExpress.ui.widgets.dataGrid\columnsResizingReorderingModule.tests.js - 3060
testing\tests\DevExpress.ui.widgets.dataGrid\dataGrid.resizing.tests.js - 1443
testing\tests\DevExpress.ui.widgets.dataGrid\editing.tests.js - 2523, 7920, 12096
testing\tests\DevExpress.ui.widgets.dataGrid\editorFactory.tests.js - 151
testing\tests\DevExpress.ui.widgets.dataGrid\filtering.integration.tests.js - 76
testing\tests\DevExpress.ui.widgets.dataGrid\filterRow.tests.js - 1314
testing\tests\DevExpress.ui.widgets.dataGrid\fixedColumns.tests.js - 185
testing\tests\DevExpress.ui.widgets.dataGrid\focus.integration.tests.js - 71
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.accessibility.tests.js - 475, 770, 842
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.customization.tests.js - 1947
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.keyboardKeys.tests.js - 679, 800, 1436, 1500
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.realControllers.tests.js - 531, 1131, 1176, 1214
testing\tests\DevExpress.ui.widgets.dataGrid\rowDragging.tests.js - 804, 881, 909, 1041
testing\tests\DevExpress.ui.widgets.dataGrid\rowsView.tests.js - 5696, 6885
testing\tests\DevExpress.ui.widgets.dataGrid\scrolling.integration.tests.js - 437
testing\tests\DevExpress.ui.widgets.dataGrid\virtualScrolling.integration.tests.js - 1073
testing\tests\DevExpress.ui.widgets.dataGrid\virtualScrolling.tests.js - 549

2021-06-07 07:46 UTC, NickMitrokhin requested changes
It seems that not all files were processed. The following files with corresponding line numbers contain ".msie":

js\ui\grid_core\ui.grid_core.virtual_scrolling.js - 786
testing\helpers\grid\getPointsByColumnsHelper.js - 5
testing\tests\DevExpress.ui.widgets\sortable.tests.js - 229, 245, 252, 433
testing\tests\DevExpress.ui.widgets.dataGrid\adaptiveColumns.integration.tests.js - 157, 314
testing\tests\DevExpress.ui.widgets.dataGrid\columnsResizingReorderingModule.tests.js - 3060
testing\tests\DevExpress.ui.widgets.dataGrid\dataGrid.resizing.tests.js - 1443
testing\tests\DevExpress.ui.widgets.dataGrid\editing.tests.js - 2523, 7920, 12096
testing\tests\DevExpress.ui.widgets.dataGrid\editorFactory.tests.js - 151
testing\tests\DevExpress.ui.widgets.dataGrid\filtering.integration.tests.js - 76
testing\tests\DevExpress.ui.widgets.dataGrid\filterRow.tests.js - 1314
testing\tests\DevExpress.ui.widgets.dataGrid\fixedColumns.tests.js - 185
testing\tests\DevExpress.ui.widgets.dataGrid\focus.integration.tests.js - 71
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.accessibility.tests.js - 475, 770, 842
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.customization.tests.js - 1947
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.keyboardKeys.tests.js - 679, 800, 1436, 1500
testing\tests\DevExpress.ui.widgets.dataGrid\keyboardNavigation.realControllers.tests.js - 531, 1131, 1176, 1214
testing\tests\DevExpress.ui.widgets.dataGrid\rowDragging.tests.js - 804, 881, 909, 1041
testing\tests\DevExpress.ui.widgets.dataGrid\rowsView.tests.js - 5696, 6885
testing\tests\DevExpress.ui.widgets.dataGrid\scrolling.integration.tests.js - 437
testing\tests\DevExpress.ui.widgets.dataGrid\virtualScrolling.integration.tests.js - 1073
testing\tests\DevExpress.ui.widgets.dataGrid\virtualScrolling.tests.js - 549

2021-06-08 13:28 UTC, vconst approved these changes

2021-06-08 15:36 UTC, NickMitrokhin approved these changes

2021-06-09 06:21 UTC, merged