Renovation: implement the Droppable component
DevExpress/DevExtreme pull request #18086
Opened 2021-06-25 06:41 UTC by Alyar666

2021-06-25 10:37 UTC, vconst commented on js/renovation/ui/droppable.tsx
> +    register: true,
Remove jquery registration if it is internal widget now.

2021-06-29 09:57 UTC, MikeVitik requested changes

2021-06-29 09:57 UTC, MikeVitik commented on js/renovation/ui/droppable.tsx
> +  @Slot() children?: JSX.Element | (JSX.Element | undefined | false | null)[];
I suppose it simple JSX.Element without (false | null)[]

2021-06-29 09:57 UTC, MikeVitik commented on js/renovation/ui/droppable.tsx
> +  @OneWay() disabled?: boolean;
Do you miss default - false?

2021-06-29 09:57 UTC, MikeVitik commented on js/renovation/ui/droppable.tsx
> +  @Event() onDragEnter?: (e: DroppableEvent) => void;
Replace to @Event() onDragEnter?: EventCallback<DroppableEvent>;

2021-07-06 15:10 UTC, MikeVitik approved these changes

2021-07-06 15:11 UTC, merged