DataGrid — clears selection when toggling the showCheckBoxesMode option (T1008562)
DevExpress/DevExtreme pull request #18169
Opened 2021-07-01 06:05 UTC by pomahtri

- Trello card: https://trello.com/c/v9m25e0v/5830-t1008562-datagrid-clears-selection-when-toggling-the-showcheckboxesmode-option
- Ticket: https://supportcenter.devexpress.com/ticket/details/t1008562/datagrid-clears-selection-when-toggling-the-showcheckboxesmode-option

Cherry picks:

-

---

I edited `optionChanged` method in `ui.grid_core.selection`.  Previously it cleared `selectedRowKeys` on changing options `showCheckBoxesMode`, which isn't necessary

Other options in `selection.*`:

- `allowSelectAll` — this option is checked in method `_updateSelectAllValue`, which is added to `selectionChanged` event. It may be unsafe to skip updating on this option, cause in updating we fire this event
- `deferred` — obviously can't skip updating
- `mode` — obviously can't skip updating
- `selectAllMode` — breaks `change selectAllMode to \'allPages\' at runtime` test

2021-07-02 06:45 UTC, NickMitrokhin requested changes

2021-07-02 06:45 UTC, NickMitrokhin commented on testing/tests/DevExpress.ui.widgets.dataGrid/selection.integration.tests.js
> +        dataGrid.getSelectedRowKeys().done((keys) => selectedKeysBefore = keys);
I would reset the selectedKeysBefore variable value to an empty array before calling dataGrid.getSelectedRowKeys() for the second time to make sure that selectedKeysBefore is really updated. 

```js
        // assert
        let selectedKeysBefore;
        dataGrid.getSelectedRowKeys().done((keys) => selectedKeysBefore = keys);
        this.clock.tick();
        assert.deepEqual(selectedKeysBefore, [1]);

        // act
        dataGrid.option('selection.showCheckBoxesMode', 'none');
        selectedKeysBefore = []; //add this line

        // assert
        dataGrid.getSelectedRowKeys().done((keys) => selectedKeysBefore = keys);
```

2021-07-02 08:03 UTC, NickMitrokhin approved these changes

2021-07-05 07:57 UTC, Alyar666 approved these changes

2021-07-05 08:04 UTC, merged