DataGrid.Pdf - Set backgroundColor for header, group, total rows
DevExpress/DevExtreme pull request #18406
Opened 2021-07-21 08:11 UTC by KuznetsovVN

2021-07-22 05:50 UTC, IgnatovDan approved these changes

2021-07-22 06:08 UTC, IgnatovDan requested changes

2021-07-22 06:08 UTC, IgnatovDan commented on js/exporter/jspdf/export_data_grid_2.js
> +            const rowStyles = { headerStyles, groupStyles, totalStyles };
Destructuring and immediate constructing back looks strange.
How the same scenarios are managed in our asp/mvc/winforms components?

2021-07-22 06:21 UTC, IgnatovDan requested changes

2021-07-22 06:21 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.styles.tests.js
> +        const onRowExporting = (e) => { e.rowHeight = 16; };
Will we introduce an argument for 'one height for all rows' scenario?

2021-07-22 06:21 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.styles.tests.js
> +                    'text,F1,10,23,{baseline:middle}', 'setLineWidth,1', 'rect,10,15,90,16',
We can test rect in one test and remove rects for all the others to reduce expected logs, what do you think?
Or, can we draw both the rect and fill in one 'rect' call?

2021-07-22 06:21 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.styles.tests.js
> +                exportDataGrid(doc, dataGrid, { topLeft: { x: 10, y: 15 }, columnWidths: [ 90, 80 ], onRowExporting, ...rowTypeStyles }).then(() => {
Styles were constructed in an object and destructed here.
Internally, styles will be constructed back to a single object.
Can we pass an object without destruct/construct?

2021-07-23 07:00 UTC, IgnatovDan approved these changes

2021-07-23 07:11 UTC, novsstation approved these changes

2021-07-23 13:35 UTC, EugeniyKiyashko approved these changes

2021-07-23 14:04 UTC, merged