pivot: refactor get_scrollbar_info utility
DevExpress/DevExtreme pull request #18577
Opened 2021-08-02 14:36 UTC by EugeniyKiyashko

2021-08-04 08:37 UTC, KuznetsovVN approved these changes, later dismissed

2021-08-05 07:08 UTC, IgnatovDan requested changes

2021-08-05 07:08 UTC, IgnatovDan commented on js/ui/pivot_grid/utils/get_scrollbar_info.js
> +    const $testContainer = $('<div>').appendTo('body');
'test' ?
Let's rename it to 'dummy' like in

        const dummy = that._createIndicator(settings.type, that._renderer.root);
        if(dummy) {
            dummy.dispose();
            target.render(settings, isRecreate);
        }

And, let's add try/finally section to easily find '$testContainer.remove();' entry

2021-08-05 07:31 UTC, EugeniyKiyashko commented on js/ui/pivot_grid/utils/get_scrollbar_info.js
> +    const $testContainer = $('<div>').appendTo('body');
Fixed in https://github.com/DevExpress/DevExtreme/pull/18577/commits/6bccfe41245604e79948374c616356643dae3dc1

2021-08-05 07:46 UTC, IgnatovDan approved these changes

2021-08-05 09:48 UTC, KuznetsovVN approved these changes

2021-08-05 10:24 UTC, merged