scrollable: not update scrollbar location when container doesn't have sizes
DevExpress/DevExtreme pull request #18610
Opened 2021-08-04 11:53 UTC by EugeniyKiyashko

2021-08-04 16:44 UTC, KuznetsovVN approved these changes, later dismissed

2021-08-05 07:43 UTC, IgnatovDan requested changes, later dismissed

2021-08-05 07:43 UTC, IgnatovDan commented on js/renovation/ui/scroll_view/scrollbar.tsx
> +    if (this.props.containerDimensionsIsNotZero
Let's make it the first line of method:
```
if (!this.props.containerDimensionsIsNotZero){
  return;
}
```
Or rename it:
```
if (this.props.containerHasSize){
  return;
}
```
It's very easy to understand what this condition means.

Do we need the same condition in other methods?

2021-08-05 08:03 UTC, EugeniyKiyashko commented on js/renovation/ui/scroll_view/scrollbar.tsx
> +    if (this.props.containerDimensionsIsNotZero
I renamed 'containerDimensionsIsNotZero' property to 'containerHasSize**s**' because it is important that the container's  **height & width** dimensions was not zero value simeltainiously. 

As for other methods if it's become a necessity we will add these condition in future PRs. I can't tell yet.

2021-08-08 08:58 UTC, KuznetsovVN approved these changes

2021-08-09 08:45 UTC, novsstation approved these changes

2021-08-09 08:48 UTC, merged