PDF - implement multiline text
DevExpress/DevExtreme pull request #18799
Opened 2021-08-17 12:32 UTC by novsstation

2021-08-17 16:46 UTC, IgnatovDan requested changes

2021-08-17 16:46 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.tests.js
> +    QUnit.test('1 col - 1 text line. fontSize default, lineHeight: default', function(assert) {
I think we need a new fixture.js file for each new feature

2021-08-17 16:48 UTC, IgnatovDan requested changes

2021-08-17 16:48 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.tests.js
> +        doc.setFontSize(20);
I think our code should accept a font settings, set its own font and restore initial font at the end.

2021-08-17 16:52 UTC, IgnatovDan requested changes

2021-08-17 16:52 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.tests.js
> +        doc.setLineHeightFactor(1);
And here: it's better to pass it as an explicit parameter.

2021-08-17 16:52 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/jspdf_v2.dataGrid.tests.js
> +        doc.setLineHeightFactor(1.5);
I think that these settings can be different for each cell, clients need a way to specify it for entire grid and for each cell

2021-08-19 12:40 UTC, KuznetsovVN approved these changes

2021-08-20 13:48 UTC, IgnatovDan approved these changes

2021-08-20 14:19 UTC, merged