PDF - implement grouping and summaries
DevExpress/DevExtreme pull request #19170
Opened 2021-09-10 15:17 UTC by novsstation

2021-09-14 06:37 UTC, KuznetsovVN submitted a review, later dismissed

2021-09-14 14:55 UTC, IgnatovDan requested changes

2021-09-14 14:55 UTC, IgnatovDan commented on js/exporter/jspdf/v3/row_utils.js
> +function resizeColumnsByIndentLevel(rows, options) {
resizeFirstColumnByIndentLevel ?

2021-09-14 14:55 UTC, IgnatovDan commented on js/exporter/jspdf/v3/row_utils.js
> +            cell.pdfCell._rect.x = x + intend;
Can we update '_rect.w' near this line?

row.cells[0].pdfCell._rect.w -= row.indentLevel * options.indent;

2021-09-14 14:55 UTC, IgnatovDan commented on js/exporter/jspdf/v3/rows_generator.js
> +            cellInfo.pdfCell.drawRightBorder = cellIndex === colCount - 1;
Why there was 'cellInfo.drawLeftBorder = false;' ?
I have not found a test for it.

2021-09-15 06:08 UTC, novsstation commented on js/exporter/jspdf/v3/row_utils.js
> +            cell.pdfCell._rect.x = x + intend;
Unfortunately, nope.
Reduced column width is involved in calculating the height of the text of cells.
Decreasing the width may result in a new line of text

2021-09-15 06:15 UTC, novsstation commented on js/exporter/jspdf/v3/rows_generator.js
> +            cellInfo.pdfCell.drawRightBorder = cellIndex === colCount - 1;
In the previous version of the export we always draw table borders.
So all cells in the group has no left and right border
![image](https://user-images.githubusercontent.com/57402891/133380089-07e59a27-f97e-45b6-a907-4a31795517f9.png)

In the new version of the export we don't draws the table borders. So, it's necessary to draf left border for the first cell and right border for the last cell. (Or first, if it has collSpan)
![image](https://user-images.githubusercontent.com/57402891/133380329-21e8114d-0a76-4f47-8630-9d563ecc17f6.png)

2021-09-15 06:22 UTC, novsstation commented on js/exporter/jspdf/v3/rows_generator.js
> +            cellInfo.pdfCell.drawRightBorder = cellIndex === colCount - 1;
Currently, there is a lot of [tests](https://github.com/DevExpress/DevExtreme/pull/19170/files#diff-31e0e57f3c31cf384714db7acee32571faf50d2f66126e1d1eb01d397783bda8R218) for checking the left and right borders.

![image](https://user-images.githubusercontent.com/57402891/133380773-d82dde38-4c28-4c38-bea5-a2294e6eaeec.png)

In the old version it looks like this 
![image](https://user-images.githubusercontent.com/57402891/133381205-0227ce62-b1f3-441c-b505-e880a044a006.png)

2021-09-15 06:29 UTC, novsstation commented on js/exporter/jspdf/v3/row_utils.js
> +function resizeColumnsByIndentLevel(rows, options) {
Yep, great idea. Fixed

2021-09-15 07:46 UTC, novsstation commented on js/exporter/jspdf/v3/row_utils.js
> +            cell.pdfCell._rect.x = x + intend;
I have check more complex approach with always adding virtual cells to all columns
RowsSpan calculation in this case is ok. 
```js
    rows.forEach(row => {
        row.cells[0].pdfCell._rect.w -= row.indentLevel * options.indent;
        row.cells.splice(0, 0, {
            pdfCell: {
                isVirtual: true,
                _rect: {
                    w: row.indentLevel * options.indent,
                    h: 0,
                }
            }
        });
    });
```

![image](https://user-images.githubusercontent.com/57402891/133391924-dfe2c6e2-0c2d-4e69-8201-93ee08b2ee08.png)


But in this case it's necessary to filter those virtal cells in the steps with applyingBorders config and drawing. 
But I found that all tests resulting table width grows up by 2 pixels. So, I returned to the first solution

2021-09-15 08:24 UTC, KuznetsovVN approved these changes

2021-09-15 16:53 UTC, IgnatovDan approved these changes

2021-09-15 17:20 UTC, merged