Get rid of IE hacks: Core Browser
DevExpress/DevExtreme pull request #19218
Opened 2021-09-14 14:18 UTC by jacksonrr3

2021-09-17 09:06 UTC, novsstation approved these changes, later dismissed

2021-09-17 10:52 UTC, nightskylark requested changes

2021-09-17 10:52 UTC, nightskylark commented on js/core/utils/date.js
>  const createDate = function(date) {
Let's get rid of this method. It's not needed anymore.

2021-09-17 10:52 UTC, nightskylark commented on js/core/utils/position.js
>  const getElementsFromPoint = (x, y) => {
Same here

2021-09-17 10:52 UTC, nightskylark commented on js/renovation/ui/form/_toDelete/ui.form.js
> +    _visibilityChanged: function() {},
Why did you leave an empty method?

2021-09-17 10:52 UTC, nightskylark commented on js/ui/form/ui.form.js
> +    // TODO. Deleting this method causes the DataGrid.editing test error.
Let's not leave todos in PRs. If we need to solve some issue, let's do it now. Nobody will return to it later.

2021-09-17 17:37 UTC, nightskylark approved these changes, later dismissed

2021-09-18 10:35 UTC, nightskylark submitted a review, later dismissed

2021-09-21 09:26 UTC, nightskylark approved these changes

2021-09-21 09:48 UTC, merged