DataGrid - getting rid of any - TKey, TRowData
DevExpress/DevExtreme pull request #19464
Opened 2021-09-30 11:33 UTC by pomahtri

2021-10-01 12:42 UTC, vconst requested changes
data in DataChange is not full TRowData. It is recursive partial of it.
Also, newData in setCellValue, onRowInserting, onRowUpdating, onRowValidating is also recursive partial of  TRowData.

2021-10-01 12:42 UTC, vconst commented on js/ui/data_grid.d.ts
> +    getKeyByRowIndex(rowIndex: number): TKey;
This method can return undefined. Change TKey to TKey | undefined

2021-10-04 04:27 UTC, vconst approved these changes, later dismissed

2021-10-04 12:12 UTC, IlyaKhD approved these changes, later dismissed

2021-10-04 12:15 UTC, vconst approved these changes, later dismissed

2021-10-04 12:19 UTC, IlyaKhD submitted a review, later dismissed

2021-10-04 12:25 UTC, IlyaKhD approved these changes, later dismissed

2021-10-05 07:18 UTC, vconst approved these changes

2021-10-05 07:19 UTC, merged