DataGrid - The mouse cursor is changed to 'hand' over a sorted column's header when sorting.mode is 'none' (T1032991)
DevExpress/DevExtreme pull request #19496
Opened 2021-10-04 06:56 UTC by pomahtri

Ticket:  https://devexpress.com/issue=T1032991

Cherry picks:

- 
-

---

It was explicitly set that there is hand cursor if row is sorted, even if sorting is disabled. I changed it

2021-10-04 08:55 UTC, pomahtri commented on js/ui/grid_core/ui.grid_core.sorting_mixin.js
> +            const isSortingAllowed = sortingMode !== 'none' && column.allowSorting;
Need to change it, cause in tests there's no default value for `sortingMode`. It should be `'single'`,  but in non-integration tests it's `undefined`

2021-10-05 09:34 UTC, NickMitrokhin requested changes

2021-10-05 09:34 UTC, NickMitrokhin commented on testing/tests/DevExpress.ui.widgets.dataGrid/sorting.integration.tests.js
> +                { dataField: 'field3' }],
sortOrder: 'asd' -> sortOrder: 'asc'

2021-10-06 14:07 UTC, NickMitrokhin approved these changes

2021-10-08 14:34 UTC, vconst approved these changes

2021-10-11 06:22 UTC, merged