TreeList - stricter typing - TKey, TRowData
DevExpress/DevExtreme pull request #19552
Opened 2021-10-06 13:49 UTC by pomahtri

2021-10-11 07:17 UTC, vconst requested changes

2021-10-11 07:17 UTC, vconst commented on js/ui/tree_list.d.ts
> +    isRowExpanded(key: TRowData): boolean;
TRowData -> TKey

2021-10-11 09:27 UTC, NickMitrokhin submitted a review, later dismissed

2021-10-12 09:27 UTC, IlyaKhD approved these changes

2021-10-12 09:57 UTC, vconst approved these changes

2021-10-12 09:59 UTC, NickMitrokhin approved these changes

2021-10-12 10:00 UTC, merged