List - add data-based typings
DevExpress/DevExtreme pull request #19593
Opened 2021-10-08 10:48 UTC by pavelgruba

2021-10-08 15:17 UTC, IgnatovDan requested changes

2021-10-08 15:17 UTC, IgnatovDan commented on js/ui/collection/ui.collection_widget.base.d.ts
> +    readonly addedItems: Array<TItem>;
Imho there should be 'any'.

1. Our docs declares addedItems as 'Array of any'
["addedItems	| Array of any | The **data** of the items that have been selected."](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxTabs/Configuration/#onSelectionChanged)

2. At runtime there are 'data' objects, https://js.devexpress.com/Demos/WidgetsGallery/Demo/TabPanel/Overview/jQuery/Light/:

![image](https://user-images.githubusercontent.com/2094015/136580503-debfad04-06ac-4a41-8c46-73dc7b9588cb.png)

3. 'CollectionWidgetItem' declares strict set of members (it's a wrapper around 'data' object):
https://github.com/DevExpress/DevExtreme/blob/21_2/js/ui/collection/ui.collection_widget.base.d.ts#L186

2021-10-08 15:24 UTC, IgnatovDan commented on js/ui/collection/ui.collection_widget.base.d.ts
> +    readonly addedItems: Array<TItem>;
My fault, there can 3 types of object: string, CollectionWidgetItem and data object.
The "`<TItem extends string | CollectionWidgetItem<any> | any = any>`" declaration is correct.

2021-10-11 14:27 UTC, IlyaKhD commented on js/ui/list.d.ts
> +export type InitializedEvent<TItem extends string | Item<any> | any = any, TKey = any> = InitializedEventInfo<dxList<TItem, TKey>>;
We could extract local type:
```ts
type ItemLike = string | Item<any> | any;
```

```suggestion
export type InitializedEvent<TItem extends ItemLike = any, TKey = any> = InitializedEventInfo<dxList<TItem, TKey>>;
```

2021-10-12 07:57 UTC, DokaRus approved these changes
LGTM

2021-10-12 08:07 UTC, IlyaKhD approved these changes

2021-10-12 08:33 UTC, merged