DataGrid - Remove index and pageIndex in editing.changes
DevExpress/DevExtreme pull request #19623
Opened 2021-10-11 14:32 UTC by Alyar666

2021-10-11 16:00 UTC, vconst requested changes

2021-10-11 16:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                            if(equalByValue(item[keyExpr], key)) {
Use dataController.keyOf to get key by data. Also you can remove` isDefined(keyExpr) ` condition in this case.

2021-10-11 16:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +            return isDefined(item.rowType);
Use more complex condition from ui.data_grid.grouping.js because data item can contains rowType field:
```
isDefined(item.groupIndex) && isString(item.rowType) && item.rowType.indexOf('group') === 0
```
Use can return false in this file and override this method (_IsProcessedItem) in ui.data_grid.grouping.js.

2021-10-11 16:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    let visibleItemIndex = isViewportBottom ? rowsView?.getBottomVisibleItemIndex(isViewportBottom) : rowsView?.getTopVisibleItemIndex(isViewportBottom);
It is strange that getBottomVisibleItemIndex and getTopVisibleItemIndex have different parameters here and in the _getInsertRowIndex method.

2021-10-11 16:00 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataController.tests.js
> +    };
Extract this code to helper method to avoid code duplication.

2021-10-13 07:31 UTC, NickMitrokhin requested changes

2021-10-13 07:31 UTC, NickMitrokhin commented on js/ui/grid_core/ui.grid_core.editing.js
> +            } else if(isDefined(key)) {
The key may not be defined if you add a row using the addRow method and you are on the first or last page. In case if the newRowPosition is 'first'/'last' this method returns -1 and updateItems will not cause new row rendering. It is necessary to consider the case when the key is undefined and the result should be calculated based on the newRowPosition value.

2021-10-15 06:48 UTC, NickMitrokhin submitted a review, later dismissed

2021-10-18 07:32 UTC, vconst approved these changes

2021-10-18 11:39 UTC, merged