DataGrid: Rework columns.button.template to fix button position in React (T1036895)
DevExpress/DevExtreme pull request #19720
Opened 2021-10-18 16:47 UTC by vconst

2021-10-19 13:12 UTC, NickMitrokhin requested changes

2021-10-19 13:12 UTC, NickMitrokhin commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.integration.tests.js
> +                                onRendered();
maybe "div" instead of "adiv"

2021-10-20 13:54 UTC, NickMitrokhin approved these changes

2021-10-20 23:59 UTC, Alyar666 approved these changes

2021-10-21 05:53 UTC, merged