PDF - implement customDrawCell callback
DevExpress/DevExtreme pull request #19770
Opened 2021-10-20 15:51 UTC by novsstation

2021-10-21 07:01 UTC, IgnatovDan requested changes

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                    pdfCell.customDrawCell = ({ rect, cell }) => {
({ rect, cell }) -> ({ jsPDFDocument, rect, cell })
\+ assert.strictEqual(jsPDFDocument, doc);

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                        assert.deepEqual(rect, { h: 18.4, w: 500, x: 10, y: 10 });
There should be correct values for each cell: let's use "if(pdfCell.text === 'f1') { pdfCell.customDrawCell = .." approach

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.addImage(logoBase64, 'JPEG', rect.x, rect.y, 16, 16);
It's not clear what we are testing here

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.addImage(logoBase64, 'JPEG', rect.x, rect.y, 16, 16);
It's not clear what we are testing here

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.textWithLink('Click here', rect.x, rect.y + rect.h - 1, { url: 'http://www.google.com' });
It's not clear what we are testing here

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.textWithLink('Click here', rect.x, rect.y + rect.h - 1, { url: 'http://www.google.com' });
It's not clear what we are testing here

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.rect(rect.x, rect.y, rect.w, rect.h, 'F');
It's not clear what we are testing here

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.rect(rect.x, rect.y, rect.w, rect.h, 'F');
It's not clear what we are testing here

2021-10-21 07:01 UTC, IgnatovDan commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                    columns: [{ caption: 'f1' }]
\+ columns: [{ caption: 'f1', caption: 'f2' }]

2021-10-21 07:02 UTC, IgnatovDan requested changes

2021-10-21 07:02 UTC, IgnatovDan commented on js/exporter/jspdf/v3/draw_utils.js
> +        if(isDefined(cell.customDrawCell)) {
drawCellBackground(doc, cell); - why it doesn't depend from customDrawCell ?

2021-10-21 14:28 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                    pdfCell.customDrawCell = ({ rect, cell }) => {
Yep, great idea. Fixed

2021-10-21 14:28 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                        assert.deepEqual(rect, { h: 18.4, w: 500, x: 10, y: 10 });
Yep, fixed. Now I check all available cells in this test

2021-10-21 14:32 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.addImage(logoBase64, 'JPEG', rect.x, rect.y, 16, 16);
I wanted to test that the new functionality allows customers to draw any rects/images/links/etc in a cell.
But I agree, in fact, I got into checking the logic of the jsPDF.
After I added a checking of the doc argument, this test now looks redundant :)
Removed it.

2021-10-21 14:32 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.addImage(logoBase64, 'JPEG', rect.x, rect.y, 16, 16);
Same as before. Removed this test

2021-10-21 14:32 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.textWithLink('Click here', rect.x, rect.y + rect.h - 1, { url: 'http://www.google.com' });
Same as before. Removed it

2021-10-21 14:32 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.textWithLink('Click here', rect.x, rect.y + rect.h - 1, { url: 'http://www.google.com' });
Same as before. Removed it

2021-10-21 14:32 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.rect(rect.x, rect.y, rect.w, rect.h, 'F');
Same as before. Removed it

2021-10-21 14:34 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                            doc.rect(rect.x, rect.y, rect.w, rect.h, 'F');
Same as before. Removed it

2021-10-21 14:35 UTC, novsstation commented on testing/tests/DevExpress.exporter/jspdfParts/v3/jspdf_v3.dataGrid.customDrawCell.tests.js
> +                    columns: [{ caption: 'f1' }]
Yep, fixed and now I checks all available cells

2021-10-21 14:36 UTC, novsstation commented on js/exporter/jspdf/v3/draw_utils.js
> +        if(isDefined(cell.customDrawCell)) {
My fault. 
Now, I call the drawCellBackground only if customDrawCell is not specified

2021-10-22 13:56 UTC, KuznetsovVN submitted a review, later dismissed

2021-10-25 11:12 UTC, KuznetsovVN submitted a review, later dismissed

2021-10-26 10:18 UTC, IgnatovDan approved these changes

2021-10-26 11:06 UTC, KuznetsovVN approved these changes

2021-10-26 11:10 UTC, merged