Sortable - The drop indicator is displayed incorrectly after scrolling when dragging an item from another Sortable (T1035958)
DevExpress/DevExtreme pull request #19847
Opened 2021-10-26 06:58 UTC by pomahtri

`_subscribeToSourceScroll` was called only in `_dragStartHandler`. That means that scrollable was updating only for one-component dragging. In order to update `itemPoints` in cross-component dragging, I added `_subscribeToSourceScroll` in `_dragEnterHandler`

2021-11-02 11:32 UTC, NickMitrokhin requested changes

2021-11-02 11:32 UTC, NickMitrokhin commented on js/ui/sortable.js
> +    _movePlaceholder: function(_isFromHandler) {
What for "_isFromHandler"?

2021-11-02 14:26 UTC, pomahtri commented on js/ui/sortable.js
> +    _movePlaceholder: function(_isFromHandler) {
forgot to remove, fixed

2021-11-03 06:48 UTC, NickMitrokhin submitted a review, later dismissed

2021-11-09 06:15 UTC, NickMitrokhin approved these changes

2021-11-09 08:10 UTC, merged