Add native events types to Grid and TreeList
DevExpress/DevExtreme pull request #19896
Opened 2021-10-28 12:38 UTC by pavelgruba

2021-10-28 12:43 UTC, IlyaKhD commented on js/events/index.d.ts
> +export type DxEvent<TNativeEvents = Event> = {} extends EventType ? (EventObject & TNativeEvents) : EventType;
```suggestion
export type DxEvent<TNativeEvent = Event> = {} extends EventType ? (EventObject & TNativeEvents) : EventType;
```

2021-11-02 15:34 UTC, IlyaKhD approved these changes, later dismissed

2021-11-17 06:32 UTC, vconst requested changes

2021-11-17 06:32 UTC, vconst commented on js/ui/data_grid.d.ts
> +export type FocusedCellChangingEvent<TRowData = any, TKey = any> = Cancelable & NativeEventInfo<dxDataGrid<TRowData, TKey>, KeyboardEvent | PointerEvent | MouseEvent | TouchEvent> & {
TouchEvent is not possible here

2021-11-17 06:32 UTC, vconst commented on js/ui/data_grid.d.ts
> +export type FocusedRowChangingEvent<TRowData = any, TKey = any> = Cancelable & NativeEventInfo<dxDataGrid<TRowData, TKey>, KeyboardEvent | PointerEvent | MouseEvent | TouchEvent> & {
TouchEvent is not possible here

2021-11-17 10:54 UTC, vconst approved these changes

2021-11-17 10:56 UTC, merged