dxTreeList - fixes problem with wrong row heights when selection mode is multiple
DevExpress/DevExtreme pull request #2
Opened 2017-04-26 08:35 UTC by Alyar666

2017-04-26 09:23 UTC, vconst requested changes

2017-04-26 09:23 UTC, vconst commented on styles/widgets/generic/treeList.generic.less
> +    .dx-treelist-editor-cell .dx-checkbox {
Change dx-treelist-editor-cell class name to dx-treelist-select-all

2017-04-26 09:41 UTC, Yarovaya requested changes

2017-04-26 09:41 UTC, Yarovaya commented on styles/widgets/android5/treeList.android5.less
> +    .dx-checkbox {
Is it possible to move this css to base/treeList.less?

2017-04-26 18:31 UTC, Yarovaya approved these changes

2017-04-28 15:08 UTC, vconst approved these changes

2017-04-28 16:04 UTC, merged