Custom Store: fix `load(options)` type declaration
DevExpress/DevExtreme pull request #20080
Opened 2021-11-15 09:41 UTC by jacksonrr3

2021-11-17 05:53 UTC, vconst commented on js/data/custom_store.d.ts
> +    load: ((options: LoadOptions<TItem>) => DxPromise<Array<TItem>> | Array<TItem>);
It is possible to return promise with { data: Array<TItem>, totalCount: number, summary: Array} object here.
Also grouped data can be returned.

2021-11-17 07:44 UTC, vconst commented on js/data/custom_store.d.ts
> +    load: ((options: LoadOptions<TItem>) => DxPromise<Array<TItem>> | Array<TItem>);
See details examples for jquery and angular here - https://js.devexpress.com/Documentation/Guide/Data_Binding/Specify_a_Data_Source/Custom_Data_Sources/

2021-11-18 08:01 UTC, vconst requested changes

2021-11-18 08:01 UTC, vconst commented on js/data/custom_store.d.ts
> +> = { key: string; items?: Array<TItem> | GroupItem; count?: number; summary?: Array<number> };
key can have different types. So, key type should be changed to any or unknown
`items?: Array<TItem> | GroupItem` should be replaced to `items: Array<TItem> | Array<GroupItem<TItem>> | null`
Summary values can be not number. For example if use max summaryType for date or string column.

2021-11-18 08:01 UTC, vconst commented on js/data/custom_store.d.ts
> +      | DxPromise<Array<TItem>
DxPromise<Array<TItem> -> DxPromise<Array<TItem> | Array<GroupItem<TItem>>

2021-11-18 08:01 UTC, vconst commented on js/data/custom_store.d.ts
> +              data: Array<TItem> | Array<GroupItem>;
Array<GroupItem> -> Array<GroupItem<TItem>>

2021-11-18 08:01 UTC, vconst commented on js/data/custom_store.d.ts
> +              summary?: Array<number>;
number should replaced to unknown or any because summary values can have different types.

2021-11-19 14:58 UTC, IlyaKhD commented on js/data/custom_store.d.ts
> +     * @type_function_return Promise<Array|object>|Array
```suggestion
     * @type_function_return Promise<Array<any>|object>|Array<any>
```

2021-11-22 06:48 UTC, vconst commented on ts/dx.all.d.ts
> +              totalCount?: any;
totalCount type is number

2021-11-22 07:30 UTC, vconst approved these changes

2021-11-22 07:52 UTC, merged