DataGrid: Fix applying the 'editing.changes' option change inside an onOptionChanged event to a boolean column (T1043517)
DevExpress/DevExtreme pull request #20193
Opened 2021-11-19 11:50 UTC by Alyar666

See https://devexpress.com/issue=T1043517

2021-11-23 12:53 UTC, NickMitrokhin requested changes

2021-11-23 12:53 UTC, NickMitrokhin commented on js/ui/grid_core/ui.grid_core.validating.js
> +                        change && validatingController.updateValidationState(change);
```suggestion
                    if(change && params.type !== EDIT_DATA_REMOVE_TYPE) {
                        validatingController.updateValidationState(change);
```
change && is redundant here.

2021-11-25 06:15 UTC, vconst approved these changes

2021-11-25 08:22 UTC, NickMitrokhin approved these changes

2021-11-25 08:23 UTC, merged