DataGrid: Fix navigation to last row using keyboard after adding new row if scrolling mode is virtual (T1069849)
DevExpress/DevExtreme pull request #21421
Opened 2022-04-05 08:45 UTC by vconst

2022-04-05 11:34 UTC, NickMitrokhin requested changes

2022-04-05 11:34 UTC, NickMitrokhin commented on testing/testcafe/tests/dataGrid/scrolling.ts
> +  const addRoweButton = dataGrid.getHeaderPanel().getAddRowButton();
addRoweButton -> addRowButton

2022-04-06 08:52 UTC, NickMitrokhin approved these changes

2022-04-07 06:39 UTC, Alyar666 approved these changes

2022-04-07 07:00 UTC, merged