DataGrid - An editing form for a new row is not displayed under certain conditions (T1083874)
DevExpress/DevExtreme pull request #21593
Opened 2022-04-26 08:19 UTC by pomahtri

2022-04-27 07:58 UTC, Alyar666 submitted a review, later dismissed

2022-04-28 07:37 UTC, NickMitrokhin requested changes

2022-04-28 07:37 UTC, NickMitrokhin commented on testing/tests/DevExpress.ui.widgets.dataGrid/virtualScrolling.integration.tests.js
> +        assert.ok(true, 'no error throwed');
throwed -> thrown or much better "no errors"

2022-04-28 09:08 UTC, NickMitrokhin approved these changes

2022-04-28 09:09 UTC, merged