DataGrid - Pager - Add aria- attributes (T1103945)
DevExpress/DevExtreme pull request #22512
Opened 2022-08-29 10:55 UTC by Tucchhaa

2022-09-01 07:39 UTC, pomahtri submitted a review, later dismissed
~~translation for pager's label will be added in next PR~~

2022-09-05 12:34 UTC, MikeVitik requested changes

2022-09-05 12:34 UTC, MikeVitik commented on js/renovation/ui/pager/common/light_button.tsx
> +    aria-current={selected ? 'page' : undefined}
Add label localization

2022-09-05 12:34 UTC, MikeVitik commented on js/renovation/ui/pager/pages/__tests__/page.test.tsx
> +  it('pageIndexes: check aria-current attribute', () => {
Split this test into two parts. One should test page and another should test light button

2022-09-05 12:34 UTC, MikeVitik commented on js/renovation/ui/pager/__tests__/content.test.tsx
> +    it('aria', () => {
Add check messageLocalization.format is called

2022-09-06 13:03 UTC, MikeVitik approved these changes, later dismissed

2022-09-08 13:40 UTC, MikeVitik approved these changes

2022-09-09 05:26 UTC, merged