DataGrid - Show popup on init if editRowKey is specified
DevExpress/DevExtreme pull request #22676
Opened 2022-09-16 12:15 UTC by Tucchhaa

2022-09-19 06:49 UTC, pomahtri requested changes

2022-09-19 06:49 UTC, pomahtri commented on js/ui/grid_core/ui.grid_core.editing_form_based.js
> +                        if(rowIndex !== -1 && this.isEditing() && this.isPopupEditMode()) {
you also need to add flag like `isFirstRender` to prevent calling `_showEditPopup` in case editRow is changed

2022-09-19 06:49 UTC, pomahtri commented on js/ui/grid_core/ui.grid_core.editing_form_based.js
> +                    this._rowsView.renderCompleted.add(() => {
```suggestion
                    this._rowsView?.renderCompleted.add(() => {
```

tests are failed with `TypeError: Cannot read properties of undefined (reading 'renderCompleted')`, it seems that `_rowsView` isn't initialized in tests, so just add `?`

2022-09-22 08:07 UTC, pomahtri approved these changes

2022-09-22 10:06 UTC, Alyar666 approved these changes

2022-09-22 10:58 UTC, merged