Fix incorect rerendering of menu items (T586310)
DevExpress/DevExtreme pull request #2275
Opened 2017-12-18 09:15 UTC by sometimesElen

2017-12-18 10:28 UTC, DokaRus requested changes

2017-12-18 10:28 UTC, DokaRus commented on js/ui/context_menu/ui.menu_base.js
> +            $itemFrame.removeClass(DX_ITEM_HAS_TEXT);
use the `toggleClass` method

2017-12-18 10:28 UTC, DokaRus commented on js/ui/context_menu/ui.menu_base.js
> +            $itemFrame.removeClass(DX_ITEM_HAS_ICON);
you can refactor it too

2017-12-18 10:28 UTC, DokaRus commented on js/ui/context_menu/ui.menu_base.js
> +            $itemFrame.removeClass(DX_ITEM_HAS_SUBMENU);
use the `toggleClass` method

2017-12-18 10:28 UTC, DokaRus commented on js/ui/context_menu/ui.menu_base.js
> +        if(!$itemFrame || !$itemFrame.length) {
Is there a chance, that the `children` function returns `null` or `undefined`?

2017-12-18 10:28 UTC, DokaRus commented on js/ui/context_menu/ui.menu_base.js
> +        var $itemFrame = $container.children(".dx-menu-item");
extract a class names to constant

2017-12-18 12:09 UTC, DokaRus commented
Let's wait for @mrjohn0011 review

2017-12-18 15:33 UTC, mrjohn0011 requested changes
Pull request should unclear name. The name should be corrected to describe fixed problem more concrete

2017-12-18 15:33 UTC, mrjohn0011 commented on js/ui/context_menu/ui.menu_base.js
> +        return node.internalFields && node.internalFields.childrenKeys.length;
If a node has no internalFields - it is an item. Why not converted items appear in this method? This issue should be fixed on another level

2017-12-18 15:33 UTC, mrjohn0011 commented on js/ui/context_menu/ui.menu_base.js
> +    _addContentClasses: function(node, $itemFrame) {
If this is not a `node`, rename please

2017-12-18 15:33 UTC, mrjohn0011 commented on js/ui/context_menu/ui.menu_base.js
> +        if(!this.constructor.ItemClass.getInstance($item).setDataField(property, value)) {
Don't redefine all method but only required part of this

2017-12-18 15:33 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets/menuBase.tests.js
> +    assert.equal($item.length, 1, 'there is 1 item in menu');
This assert is redundant

2017-12-19 08:57 UTC, DokaRus commented on js/ui/collection/ui.collection_widget.base.js
> +            this._renderNewItem($item, item);
You update an existed item, right? Maybe better rename to `_refreshItem`?

2017-12-19 08:57 UTC, DokaRus commented on js/ui/context_menu/ui.menu_base.js
> +            $itemContent = $itemFrame.children("." + ITEM_CLASS + "-content");
Move to a constant, do not hide classes or selectors in the code

2017-12-19 09:20 UTC, DokaRus approved these changes

2017-12-19 12:25 UTC, mrjohn0011 approved these changes

2017-12-19 13:29 UTC, merged