Fix wrong text clipping if Toolbar has small size (T585698)
DevExpress/DevExtreme pull request #2315
Opened 2017-12-22 06:29 UTC by Yarovaya

2017-12-22 08:59 UTC, DokaRus commented on js/ui/toolbar/ui.toolbar.base.js
> +            for(i = 0; i < labels.length; i++) {
Can we refactor it? Function is very long and probably you can extract reusable code parts

2017-12-26 09:46 UTC, DokaRus requested changes

2017-12-26 09:46 UTC, DokaRus commented on js/ui/toolbar/ui.toolbar.base.js
> +                currentLabelWidth = $($label).outerWidth(),
`$($label)` - is it necessary after `$label = $(labels[i])`

2017-12-26 09:46 UTC, DokaRus commented on js/ui/toolbar/ui.toolbar.base.js
> +        labels.forEach(function($label, index) {
rename `$label` to `label`

2017-12-26 09:46 UTC, DokaRus commented on js/ui/toolbar/ui.toolbar.base.js
> +        labels.forEach(function($label, index) {
rename `$label` to `label`

2017-12-26 09:46 UTC, DokaRus commented on js/ui/toolbar/ui.toolbar.base.js
> +            expanding && $($label).css("maxWidth", "inherit");
I think it would looks better with a conditional statement
```
if(expanding) {
  $label.css("maxWidth", "inherit");
}
```

2017-12-26 09:46 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets/toolbar.tests.js
> +        this.element = $("#toolbar");
Maybe add a `getItems` function here? You call `this.element.find("." + TOOLBAR_ITEM_CLASS)` in each test

2017-12-26 10:53 UTC, DokaRus requested changes

2017-12-26 10:53 UTC, DokaRus commented on js/ui/toolbar/ui.toolbar.base.js
> +                $($label).css("maxWidth", labelMaxWidth);
One more `$($label)` missed :)

2017-12-26 11:40 UTC, DokaRus approved these changes
LGTM

2017-12-26 12:10 UTC, jsdmitry approved these changes

2017-12-26 12:24 UTC, merged