DataGrid - Focus doesn't move if dataRowTemplate is specified - T1125984
DevExpress/DevExtreme pull request #23208
Opened 2022-11-15 07:17 UTC by Tucchhaa

2022-11-15 07:58 UTC, pomahtri requested changes

2022-11-15 07:58 UTC, pomahtri commented on js/ui/grid_core/ui.grid_core.keyboard_navigation.js
> +        const isCellPositionDefined = isDefined(this._focusedCellPosition) && !isEmptyObject(this._focusedCellPosition) && !(this._focusedCellPosition.rowIndex === -1 && this._focusedCellPosition.col
```suggestion
        const isCellPositionDefined = 
                isDefined(this._focusedCellPosition) &&
                !isEmptyObject(this._focusedCellPosition) &&
                !(
                        this._focusedCellPosition.rowIndex === -1 &&
                        this._focusedCellPosition.columnIndex === -1
                );
```

2022-11-15 07:58 UTC, pomahtri commented on js/ui/grid_core/ui.grid_core.keyboard_navigation.js
> +        const isCellPositionDefined = isDefined(this._focusedCellPosition) && !isEmptyObject(this._focusedCellPosition) && !(this._focusedCellPosition.rowIndex === -1 && this._focusedCellPosition.col
or maybe it's better to move to helper function, if similar expression is used somewhere else

2022-11-15 12:57 UTC, Tucchhaa commented on testing/tests/DevExpress.ui.widgets.dataGrid/keyboardNavigation.keyboardKeys.tests.js
> +        this.keyboardNavigationController._focusedCellPosition = { columnIndex: 0, rowIndex: 1 };
it is strange that after editing _focusedCellPosition is set to (-1, -1) in this test. There are couple another tests for T259896 below this test, where _focusedCellPosition is set to edited cell position. Please check this.

2022-11-17 23:07 UTC, pomahtri submitted a review, later dismissed

2022-11-22 07:02 UTC, pomahtri approved these changes

2022-11-22 12:39 UTC, Alyar666 approved these changes

2022-11-22 14:02 UTC, merged