add eslint react config
DevExpress/DevExtreme pull request #23415
Opened 2022-12-12 11:16 UTC by iBat

2022-12-12 11:19 UTC, alexslavr approved these changes

2022-12-14 07:56 UTC, MikeVitik requested changes

2022-12-14 07:56 UTC, MikeVitik commented on packages/react/.eslintrc.js
>      'react/jsx-no-constructed-context-values': 'off',
Remove this exeption

2022-12-14 08:01 UTC, const314 commented on packages/react/.eslintrc.js
>      'react/jsx-no-constructed-context-values': 'off',
fixed

2022-12-14 08:05 UTC, MikeVitik commented on package.json
> +        "lint": "eslint --ignore-path .eslintignore .",
Do we really need so many lint scripts in the root package.json?
'Lint' and 'lint:fix' it's enough for me.

2022-12-14 08:05 UTC, MikeVitik approved these changes

2022-12-14 11:44 UTC, const314 approved these changes

2022-12-14 12:02 UTC, merged