Fix jquery lint
DevExpress/DevExtreme pull request #23486
Opened 2022-12-20 13:20 UTC by MikeVitik

2022-12-20 14:31 UTC, const314 approved these changes

2022-12-21 04:25 UTC, williamvinogradov commented on .github/workflows/_lint.yml
> +    - name: Build
Major comment.

I don't think it's a good place for a build check.

If you want to add a build check for the @devextreme/jquery, 
let's add it to the ```.github/workflows/_tests.yml``` as a separate job

Or let's wait until playgrounds/jquery will be ready.
Because now we checking our builds by building playground apps (these apps depend on the all platform packages)

2022-12-21 04:25 UTC, williamvinogradov commented on packages/jquery/patch/radio-button-hocs.jsx
> +/* eslint-disable react/react-in-jsx-scope */
This file is ignored by ```eslintignore```.
Also, these rules are disabled in the local ```.eslintrc.js``` config

So, looks like we don't need these disabling comments here :)

```suggestion
```

2022-12-21 04:25 UTC, williamvinogradov commented on .eslintignore
> +packages/jquery/patch/*
Question.

Maybe I missed something in our discussions.
But as far as I know, we write patch/* files by hand.

Why do we add these files to ```.eslintignore```?

2022-12-21 04:25 UTC, williamvinogradov commented on packages/jquery/patch/radio-button-hocs.jsx
> +      event.stopPropagation();
Question.

Maybe I missed something from our discussions.
But if I remember all correctly, we agreed that we remove this from the React component o_O

@const314 correct me if I wrong

2022-12-21 10:01 UTC, williamvinogradov commented on .github/workflows/_lint.yml
> +    - name: Build
We discussed it at the daily meeting.
Without build, the eslint check isn't passed because some source code uses imports from the generated code.

2022-12-21 12:56 UTC, MikeVitik commented on .eslintignore
> +packages/jquery/patch/*
Because it has the wrong file paths in the module imports

2022-12-21 13:41 UTC, MikeVitik commented on .github/workflows/_lint.yml
> +    - name: Build
Change it to build:react to reduce build scoupe

2022-12-22 10:57 UTC, iBat requested changes

2022-12-22 10:57 UTC, iBat commented on .github/workflows/_lint.yml
> +      run: npm run build:react
This is a redundant and harmful change. Should be reverted. With this change ./packges/jquery project not builds. This is why eslint check fails.
```suggestion
      run: npm run build
```

2022-12-22 14:46 UTC, iBat approved these changes

2022-12-23 07:16 UTC, IlyaKhD approved these changes

2022-12-23 08:53 UTC, merged