Fix TS - make GlobalConfig type public
DevExpress/DevExtreme pull request #23617
Opened 2023-01-05 06:51 UTC by ivanblinov2k17

2023-01-09 07:39 UTC, IlyaKhD requested changes

2023-01-09 07:39 UTC, IlyaKhD commented on js/core/config.d.ts
> +export interface GlobalConfig {
Add alias for backward compatibility
```ts
/**
 * @deprecated Use GlobalConfig instead
 */
export globalConfig = GlobalConfig;
 ```

2023-01-09 12:11 UTC, IlyaKhD requested changes

2023-01-09 12:11 UTC, IlyaKhD commented on js/core/config.d.ts
> + * @docid
This one doesn't need `docid` tag because it doesn't have it's own topic (`GlobalConfig` should have)
```suggestion
```

2023-01-09 12:11 UTC, IlyaKhD commented on js/core/config.d.ts
> +export interface globalConfig extends GlobalConfig {}
```suggestion
export type globalConfig = GlobalConfig;
```

2023-01-09 13:01 UTC, IlyaKhD commented on js/core/config.d.ts
> +export interface GlobalConfig {
```suggestion
export type GlobalConfig = {
```

2023-01-09 13:03 UTC, IlyaKhD commented on ts/aliases.d.ts
> +    /** @deprecated Use GlobalConfig instead */
```suggestion
    /** @deprecated Use DevExpress.GlobalConfig instead */
```

2023-01-09 14:49 UTC, IlyaKhD submitted a review, later dismissed

2023-01-09 16:17 UTC, IlyaKhD commented on js/core/config.d.ts
> + * @public
Let's change it's namespace as well
```diff
-* @namespace DevExpress
+* @namespace DevExpress.common
```

2023-01-10 08:12 UTC, vladaskorohodova approved these changes, later dismissed

2023-01-10 11:34 UTC, IlyaKhD requested changes

2023-01-10 11:34 UTC, IlyaKhD commented on ts/aliases.d.ts
> +declare module DevExpress.common {
```suggestion
declare module DevExpress {
```

2023-01-10 11:40 UTC, IlyaKhD approved these changes

2023-01-10 11:41 UTC, vladaskorohodova approved these changes

2023-01-10 12:01 UTC, merged