Fix a throwing exception while drugging a row in grid (T1150251)
DevExpress/DevExtreme pull request #23958
Opened 2023-03-01 19:06 UTC by GoodDayForSurf

Fix a throwing exception while drugging a row in grid  if angular is used in a page (T1150251)

2023-03-03 11:22 UTC, MikeVitik requested changes

2023-03-03 11:22 UTC, MikeVitik commented on js/core/utils/type.js
> +    if(object === null) {
Remove types["Object null"]
Use type in isPlainObject instead of direct Object.prototype.toString.call

2023-03-03 13:11 UTC, GoodDayForSurf commented on js/core/utils/type.js
> +    if(object === null) {
ok

2023-03-03 17:43 UTC, artem-kurchenko approved these changes

2023-03-07 08:20 UTC, MikeVitik approved these changes

2023-03-07 08:21 UTC, merged