BarGauge: If labels do not overlap, then connectors should be drawn as if resolveLabelOverlapping = none
DevExpress/DevExtreme pull request #23981
Opened 2023-03-06 12:40 UTC by EvgeniiMorozovDevSoft

2023-03-06 17:29 UTC, ksercs commented on js/viz/gauges/bar_gauge.js
> +            const indent = 4;
Why do we need this?
Can we choose more meaningful name to describe what is this for?

2023-03-06 17:34 UTC, ksercs commented on testing/tests/DevExpress.viz.gauges/barGauge.tests.js
> +QUnit.test('Connectors should be moved by turning, if labels are not moved', function(assert) {
```suggestion
QUnit.test('Connectors should be moved by turning if labels are not moved', function(assert) {
```

2023-03-07 07:24 UTC, ksercs submitted a review, later dismissed

2023-03-07 07:28 UTC, alexanderPolosatov requested changes

2023-03-07 07:28 UTC, alexanderPolosatov commented on testing/tests/DevExpress.viz.gauges/barGauge.tests.js
> +    group.animationComplete = $.proxy(function() {
looks like proxy is not needed

2023-03-07 08:10 UTC, alexanderPolosatov approved these changes

2023-03-07 08:16 UTC, Krijovnick approved these changes

2023-03-07 08:17 UTC, merged