DataGrid - move to ts
DevExpress/DevExtreme pull request #24110
Opened 2023-03-26 23:47 UTC by pomahtri

2023-03-28 07:43 UTC, MikeVitik requested changes
Remove @ts-expect-error

2023-03-28 07:56 UTC, pomahtri commented
> Remove @ts-expect-error

`@ts-expect-error` was added intentionally, since these errors are hard to fix right now, we will do it later while refactoring
Many of them are caused by incorrect d.ts files outside of grid's files

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/grouping/module.ts
> +    _hasGroupLevelsExpandState(group, isExpanded) {
Let's add ```// @ts-expect-error``` here, because:

```
TS7030: Not all code paths return a value.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/grouping/module_expanded.ts
> +      foreachCollapsedGroups(that, (groupInfo) => {
Let's add ```// @ts-expect-error``` here, because:

```
TS7030: Not all code paths return a value.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/grouping/module_expanded.ts
> +      foreachCollapsedGroups(that, (groupInfo) => {
Let's add ```// @ts-expect-error``` here, because:

```
TS7030: Not all code paths return a value.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/module_not_extended/editor_factory.ts
> +import { editorFactoryModule } from '@js/ui/grid_core/ui.grid_core.editor_factory';
Let's add ```// @ts-expect-error``` here because:
```
TS2305: Module '"@js/ui/grid_core/ui.grid_core.editor_factory"' has no exported member 'editorFactoryModule'.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/summary/module.ts
> +          _getSummaryOptions(remoteOperations) {
Let's add ```// @ts-expect-error``` here because:

```
TS7030: Not all code paths return a value.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/summary/module.ts
> +              each(summaryItems || [], function (index) {
Let's add ```// @ts-expect-error``` here because:

```
TS7030: Not all code paths return a value.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/__internal/grids/data_grid/module_editing.ts
> +import { editingModule } from '@js/ui/grid_core/ui.grid_core.editing';
Let's add ```// @ts-expect-error``` here because

```
TS2305: Module '"@js/ui/grid_core/ui.grid_core.editing"' has no exported member 'editingModule'.
```

2023-03-28 15:01 UTC, williamvinogradov commented on js/ui/data_grid/ui.data_grid.js
>  // STYLE dataGrid
Maybe it will be better if we move this ```STYLE``` comment to 
```js/data_grid.js```?

2023-03-28 15:01 UTC, williamvinogradov commented on js/ui/grid_core/ui.grid_core.column_chooser.js
> +                         * @type {any}
We disabled the grid core TS checks for now
Let's rollback this doc comment

It may help us in the future when we will move the grid core to TS

2023-03-28 15:06 UTC, pomahtri commented on js/ui/grid_core/ui.grid_core.column_chooser.js
> +                         * @type {any}
I added it to prevent importing data_grid from grid_core, I will fix it right after this PR with correct import from `common/grids`

2023-03-29 10:27 UTC, williamvinogradov approved these changes, later dismissed

2023-03-29 10:40 UTC, pomahtri commented on js/ui/data_grid/ui.data_grid.js
>  // STYLE dataGrid
Unfortunately, we can't because of error in themebuilder tests

2023-03-30 07:33 UTC, MikeVitik approved these changes

2023-03-30 08:14 UTC, merged