T1156999 23.1
DevExpress/DevExtreme pull request #24264
Opened 2023-04-12 13:15 UTC by Raushen

Adding aria-label attribute for pager's inputs (see https://supportcenter.devexpress.com/ticket/details/t1156999/datagrid-pager-s-editors-don-t-have-the-aria-label-attribute-in-compact-mode)

2023-04-12 13:20 UTC, pomahtri requested changes

2023-04-12 13:20 UTC, pomahtri commented on js/renovation/ui/pager/page_size/small.tsx
> +const PAGER_PAGE_SIZE_SMALL_DESCRIPTION = 'Page size';
Needs to be translated

2023-04-12 13:20 UTC, pomahtri commented on js/renovation/ui/pager/page_size/small.tsx
> +    inputAttr={ { 'aria-label': PAGER_PAGE_SIZE_SMALL_DESCRIPTION } }
Let's move object to getter inside `PageSizeSmall` class, otherwise new object will be created each time `viewFunction` is called, it can lead to extra rerenders. Getters inside component's class are memorized

2023-04-20 19:01 UTC, williamvinogradov submitted a review, later dismissed

2023-04-21 07:01 UTC, pomahtri approved these changes

2023-04-21 07:44 UTC, merged