Toolbar: Fix menu button attributes
DevExpress/DevExtreme pull request #24322
Opened 2023-04-17 12:21 UTC by marker-dao

2023-04-17 23:18 UTC, ksercs requested changes

2023-04-17 23:18 UTC, ksercs commented on js/ui/toolbar/internal/ui.toolbar.menu.js
> +                role: 'menu',
WAVE reports about wrapper's child without role `menuitem` and about item's parent without role `menu`. Please, check it

2023-04-18 11:35 UTC, ksercs approved these changes

2023-04-18 11:39 UTC, alexanderPolosatov approved these changes

2023-04-18 12:15 UTC, merged