DataGrid - A cell with a TextArea editor is closed when a mouse click is released outside the editor (T1161254)
DevExpress/DevExtreme pull request #24492
Opened 2023-05-02 15:01 UTC by Raushen

TextArea editor closing cancelled (see https://supportcenter.devexpress.com/ticket/details/t1161254/datagrid-a-cell-with-a-textarea-editor-is-closed-when-a-mouse-click-is-released-outside)

2023-05-02 20:05 UTC, pomahtri approved these changes, later dismissed

2023-05-03 00:06 UTC, Alyar666 requested changes

2023-05-03 00:06 UTC, Alyar666 commented on js/ui/grid_core/ui.grid_core.editing_cell_based.js
> +                            function isEditable($element) {
Is it possible to pull this method outside of the controller?

2023-05-03 00:06 UTC, Alyar666 commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.integration.tests.js
> +        this.clock.tick(5000);
Need such a big timeout?

2023-05-03 00:06 UTC, Alyar666 commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.integration.tests.js
> +        $textArea.trigger($.Event('dxpointerdown', { pageX: $textArea.offset().left + 5, pageY: $textArea.offset().top + 5 }));
dxpointerdown and dxpointerup - are these events necessary?

2023-05-03 00:06 UTC, Alyar666 commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.integration.tests.js
> +        $textArea.trigger($.Event('click', { pageX: 0, pageY: 0, target: $('body').get(0) }));
pageX and pageY - are these parameters needed? I think they do not play an important role, and they can be left out.

2023-05-03 00:06 UTC, Alyar666 commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.integration.tests.js
> +        this.clock.tick(5000);
Need such a big timeout?

2023-05-03 12:15 UTC, Alyar666 approved these changes

2023-05-04 17:31 UTC, williamvinogradov approved these changes

2023-05-05 11:04 UTC, merged