DateRangeBox - startDate/endDate options should have 'default' prefix in React
DevExpress/DevExtreme pull request #24800
Opened 2023-05-31 14:17 UTC by alexanderPolosatov

2023-05-31 14:23 UTC, ksercs approved these changes

2023-05-31 14:25 UTC, ksercs requested changes

2023-05-31 14:25 UTC, ksercs commented on js/ui/date_range_box.d.ts
> +     * @fires BaseWidgetOptions.onValueChanged
```suggestion
        * @fires EditorOptions.onValueChanged
```

2023-05-31 16:00 UTC, ksercs submitted a review, later dismissed

2023-06-01 09:27 UTC, Zedwag approved these changes, later dismissed

2023-06-01 10:01 UTC, IlyaKhD requested changes

2023-06-01 10:01 UTC, IlyaKhD commented on js/ui/date_range_box.d.ts
> +     * @fires
```suggestion
     * @fires dxDateRangeBoxOptions.onOptionChanged
```

2023-06-01 10:01 UTC, IlyaKhD commented on js/ui/date_range_box.d.ts
> +     * @fires
```suggestion
     * @fires dxDateRangeBoxOptions.onOptionChanged
```

2023-06-01 10:01 UTC, IlyaKhD commented on js/ui/date_range_box.d.ts
> +     * @fires
`@fires` can not be empty

2023-06-01 10:12 UTC, mpreyskurantov approved these changes

2023-06-01 10:20 UTC, Zedwag approved these changes

2023-06-01 10:40 UTC, IlyaKhD approved these changes

2023-06-01 10:42 UTC, merged