Chart: bar should be rendered when value is on border (T1176892)
DevExpress/DevExtreme pull request #25144
Opened 2023-07-21 10:55 UTC by Zedwag

2023-07-21 10:56 UTC, alexanderPolosatov submitted a review, later dismissed

2023-07-21 10:58 UTC, Krijovnick submitted a review, later dismissed

2023-07-21 12:03 UTC, ksercs requested changes

2023-07-21 12:03 UTC, ksercs commented on js/viz/series/points/bar_point.js
> +        this.inVisibleArea = minX <= x + width && maxX >= x && minY <= y + height && maxY >= y;
Please, update all code style according to our guidelines

2023-07-21 12:56 UTC, Zedwag commented on js/viz/series/points/bar_point.js
> +        this.inVisibleArea = minX <= x + width && maxX >= x && minY <= y + height && maxY >= y;
roger that

2023-07-21 13:17 UTC, ksercs approved these changes, later dismissed

2023-07-24 05:42 UTC, Krijovnick submitted a review, later dismissed

2023-07-26 13:43 UTC, alexanderPolosatov approved these changes

2023-07-26 13:44 UTC, merged