Fix onClick event for column button
DevExpress/DevExtreme pull request #25395
Opened 2023-08-21 07:45 UTC by dxvladislavvolkov

### Cherry-picks
- #25644

Docs:
- https://github.com/DevExpress/devextreme-documentation/pull/5506

2023-08-22 05:01 UTC, pomahtri submitted a review, later dismissed

2023-08-22 10:37 UTC, mpreyskurantov requested changes

2023-08-22 10:37 UTC, mpreyskurantov commented on packages/devextreme/js/ui/data_grid.d.ts
> +     * @type_function_param1 e:{ui/data_grid:ColumnButtonClickEvent}
Let's make a counterpart fix for TreeList and add doc comments for the ColumnButtonClickEvent type(s) to be published.
Blocked until the mono-repo CI fix.

2023-08-22 10:43 UTC, mpreyskurantov commented on packages/devextreme/js/ui/data_grid.d.ts
> +     * @type_function_param1 e:{ui/data_grid:ColumnButtonClickEvent}
Moreover, TopicsGenerator fails without declaring the "ColumnButtonClickEvent" type linked via uid ref e:{ui/data_grid:ColumnButtonClickEvent}

2023-08-31 09:19 UTC, mpreyskurantov commented on packages/devextreme/js/ui/data_grid.d.ts
> +     * @type_function_param1 e:{ui/data_grid:ColumnButtonClickEvent}
Discard TreeList. Add declarations for DataGrid.

2023-08-31 09:44 UTC, mpreyskurantov approved these changes

2023-08-31 10:03 UTC, pomahtri submitted a review, later dismissed

2023-08-31 10:28 UTC, OlegKipchatov approved these changes

2023-08-31 11:48 UTC, mpreyskurantov requested changes

2023-08-31 11:48 UTC, mpreyskurantov commented on packages/devextreme-angular/src/ui/nested/base/text-editor-button-dxi.ts
>      }
Confirm if this change ever has effect.

2023-09-21 13:00 UTC, mpreyskurantov commented on packages/devextreme-angular/src/ui/nested/base/text-editor-button-dxi.ts
>      }
TypeScript checking does not work for nested options (at least without the @Input() decorator).

2023-09-21 13:00 UTC, mpreyskurantov approved these changes

2023-09-21 13:01 UTC, merged