Charts - Publish SeriesPoint & SeriesLabel types
DevExpress/DevExtreme pull request #25701
Opened 2023-09-28 11:14 UTC by alexanderPolosatov

2023-10-18 15:31 UTC, mpreyskurantov approved these changes

2023-10-18 15:32 UTC, mpreyskurantov requested changes
Wait until 23.1.6 is released

2023-10-20 09:28 UTC, marker-dao approved these changes

2023-10-20 10:58 UTC, mpreyskurantov approved these changes

2023-10-20 11:00 UTC, merged