Refactor theme-options and fix theme-builder theme test
DevExpress/DevExtreme pull request #25834
Opened 2023-10-18 19:20 UTC by GoodDayForSurf

+ fix theme test

2023-10-20 13:21 UTC, OlegKipchatov approved these changes

2023-10-20 13:36 UTC, mpreyskurantov approved these changes

2023-10-20 14:00 UTC, mpreyskurantov requested changes

2023-10-20 14:00 UTC, mpreyskurantov commented on packages/devextreme/build/gulp/styles/theme-options.js
> +const getThemes = () => sizes.flatMap((size) => [
Let's wait for @EugeniyKiyashko review for the components' side.

2023-10-23 08:27 UTC, EugeniyKiyashko approved these changes

2023-10-23 08:28 UTC, mpreyskurantov approved these changes

2023-10-23 08:29 UTC, merged