Form: fix validation message position for items with top label in Material & Fluent
DevExpress/DevExtreme pull request #26024
Opened 2023-11-14 22:45 UTC by EugeniyKiyashko

2023-11-14 23:14 UTC, Zedwag submitted a review, later dismissed

2023-11-14 23:16 UTC, ksercs requested changes

2023-11-14 23:16 UTC, ksercs commented on packages/devextreme/scss/widgets/material/form/_index.scss
> -
What about tests?

2023-11-15 11:34 UTC, EugeniyKiyashko commented on packages/devextreme/scss/widgets/material/form/_index.scss
> -
https://github.com/DevExpress/DevExtreme/pull/26024/commits/cd901f553fabda53a29c6543adf785d2932ec2ce

2023-11-15 14:02 UTC, ksercs approved these changes

2023-11-15 14:07 UTC, alexanderPolosatov approved these changes

2023-11-15 14:23 UTC, merged