Utils: Add isIterableObject and use it in each function
DevExpress/DevExtreme pull request #26571
Opened 2024-02-06 14:52 UTC by marker-dao

2024-02-06 16:09 UTC, pomahtri requested changes
`each` is old function which was created before existing of modern es methods like `.forEach`, `for (let el of someArray)` etc. It's better to use standard modern utilities, and not change this one

2024-02-06 16:26 UTC, marker-dao commented
> `each` is old function which was created before existing of modern es methods like `.forEach`, `for (let el of someArray)`, `Object.keys` etc. It's better to use standard modern utilities, and not change this one

Yes, I agree with you. Our team suggested that this might be a solution. So I just tried it.

2024-02-06 16:48 UTC, pomahtri approved these changes, later dismissed

2024-02-06 16:52 UTC, pomahtri commented
Please note that using `Object.keys()` differs from using `for in` loop, which was inside `each`, since `Object.keys()` ignores prototype
But I don't know whether it's good for your case or bad

2024-02-06 18:21 UTC, Zedwag approved these changes, later dismissed

2024-02-07 06:12 UTC, AlexanderMoiseev submitted a review, later dismissed

2024-02-09 07:32 UTC, ksercs approved these changes, later dismissed

2024-02-09 07:32 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.form/form.tests.js
> +QUnit.test('onFieldDataChanged must be called once (T1213983)', function(assert) {
Let's make scenario description more precise plz
```suggestion
QUnit.test('onFieldDataChanged must be called once if new formData contains "length" property (T1213983)', function(assert) {
```

2024-02-12 07:23 UTC, marker-dao commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.form/form.tests.js
> +QUnit.test('onFieldDataChanged must be called once (T1213983)', function(assert) {
[9f919472bf239ce538e466cd6a61e848fbd9df1a]

2024-02-12 07:33 UTC, ksercs approved these changes

2024-02-12 10:36 UTC, merged