dxSparkline: Fixing inability to change lossColor option (T1218338)
DevExpress/DevExtreme pull request #26837
Opened 2024-03-06 05:14 UTC by jdvictoria

2024-03-06 05:14 UTC, jdvictoria commented
![](https://github.trello.services/images/mini-trello-icon.png) [dxSparkline - Impossible to change lossColor option[T1218338]](https://trello.com/c/MHGOomIL/8532-dxsparkline-impossible-to-change-losscolor-optiont1218338)

2024-03-06 05:54 UTC, AlexanderMoiseev commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +            winlossThreshold: 4,
I believe tests should be as concise as possible. We are testing the runtime change of the lossColor property. Do we need to initialize other properties, such as winLossThreshold or winColor?

2024-03-06 05:57 UTC, AlexanderMoiseev commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +    QUnit.test('Change winloss lossColor property', function(assert) {
please make a test name according to our convention, such as 'lossColor property should be able to change at runtime.'

2024-03-06 06:49 UTC, AlexanderMoiseev commented
The main issue is that changes are not reflected after a runtime change. Please adjust the title accordingly

2024-03-06 07:11 UTC, AlexanderMoiseev requested changes

2024-03-06 07:11 UTC, AlexanderMoiseev commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +        assert.strictEqual(sparkline.option('lossColor'), 'green', 'lossColor should be green after runtime change');
this condition won't fail if you remove your fix, i suppose. probably we have to use 'checkCustomizePoint' here, please check

2024-03-06 10:02 UTC, AlexanderMoiseev commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +    QUnit.test('winloss sparkline lossColor should change', function(assert) {
'The main issue is that changes are not reflected after a runtime change. Please adjust the title accordingly' - the same goes for the test name

2024-03-06 13:13 UTC, AlexanderMoiseev commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +            winlossThreshold: 4,
just wondering - is settng 'winlossThreshold' necessary for this tests?

2024-03-06 13:17 UTC, jdvictoria commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +            winlossThreshold: 4,
![image](https://github.com/DevExpress/DevExtreme/assets/133762589/fdacbd7a-7e62-4d15-b18a-980eb3b42b71)
Without 'winlossThreshold' the test doesn't run as intended. Still trying to figure out how to omit it.

2024-03-07 06:46 UTC, AlexanderMoiseev commented on packages/devextreme/testing/tests/DevExpress.viz.sparklines/sparkline.tests.js
> +    QUnit.test('winloss sparkline lossColor should be updated after runtime change', function(assert) {
please add ticket number to the test's name

2024-03-07 06:48 UTC, AlexanderMoiseev approved these changes, later dismissed

2024-03-07 06:56 UTC, alexanderPolosatov approved these changes

2024-03-07 11:40 UTC, AlexanderMoiseev approved these changes

2024-03-08 01:04 UTC, merged