DateBox: Fixing alphanumeric key behavior for setting time to "AM" and "PM" (T1216937)
DevExpress/DevExtreme pull request #26868
Opened 2024-03-07 13:56 UTC by jdvictoria

2024-03-07 13:57 UTC, jdvictoria commented
![](https://github.trello.services/images/mini-trello-icon.png) [Datebox - AM/PM can not be set by keyboard [T1216937]](https://trello.com/c/eOI4RzLO/8513-datebox-am-pm-can-not-be-set-by-keyboard-t1216937)

2024-03-12 10:18 UTC, ksercs requested changes

2024-03-12 10:18 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +        QUnit.test('AM/PM part should not change when keys other than \'a\' or \'p\' are pressed (T1216937)', function(assert) {
Let's just remove this additional test. I found we already have it: https://github.com/DevExpress/DevExtreme/blob/24_1/packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js#L1018

2024-03-12 10:18 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +
I see that all these scenarios were working before your changes as well. I mean config `useMaskBehavior + displayFormat="a"`. (u can remove your changes and see that your tests are still green)

Please, 
- comment temporarily your changed in the code;
- add similar tests for the **initial scenario**: useMaskBehavior + type="time"`;l
- ensure new tests are red;
- apply the fix and ensure tests became green

(TDD approach)

2024-03-12 10:18 UTC, ksercs commented on packages/devextreme/js/ui/date_box/ui.date_box.mask.js
> +            this._toggleAmPm();
With such a solution if we press "A" several times we will toggle this part every time. I expect that we only get "AM" after the first press and it will not be changed after next presses.

Please, add test for this scenario as well.

2024-03-12 10:18 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +        QUnit.test('AM/PM part should not change when keys other than \'a\' or \'p\' are pressed (T1216937)', function(assert) {
Just an advice for future tests: let's use double quotes inside of single quotes instead if slashing because it simplifies search

2024-03-12 10:18 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +    test('when P is pressed it should toggle AM to PM (T1216937)', function(assert) {
Please, add ticket ID only to the test for initial scenario.

2024-03-12 10:18 UTC, ksercs commented on packages/devextreme/js/ui/date_box/ui.date_box.mask.js
> +        if((char.toLowerCase() === 'p' && activePartText === 'AM') || (char.toLowerCase() === 'a' && activePartText === 'PM')) {
It's not a good approach to add specific checks for each found scenario:
- it's difficult to consider everything. In the note below I already found one additional scenario => this `if` would grow much;
- it's difficult to maintain. If we wanna extend the behavior in future we will need to rewrite attentively this conditions;
- if we add specific conditions we don't improve a general algorithm => neighbor scenarios still can be broken.

Did u find why general algorithm does not work? Seems like everything is logical: we brut force all values for active part and check if it contains the passed search string. 

I prefer we debug this algorithm more, find the exact reason and try to improve it.

2024-03-15 12:36 UTC, ksercs commented on packages/devextreme/js/ui/date_box/ui.date_box.mask.js
> +        const isAmPmPartActive = activePartPattern === 'a' || activePartPattern === 'aaa';
As far as i know "aa" and "aaaa" can be used as well.
Let's check it with a regexp ensuring that format is a string which consist of 1-5 "a" letters

2024-03-15 12:36 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +    test('when "p" is pressed it should change AM to PM (T1217203)', function(assert) {
I prefer we move the ticket it to the test below cause ticket scenario is about pressing "a"

2024-03-15 12:36 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +    test('when "p" is pressed it should change AM to PM (T1217203)', function(assert) {
let's make a submodule and iterate through all "a" formats

2024-03-18 06:47 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +        ['a', 'aa', 'aaa', 'aaaa', 'aaaaa'].forEach((format) => {
`beforeEach` is called before each test
=> before each test u iterate through all display formats setting it one after another and finally u always have the last `aaaaa` format in all your tests.

We cannot set `displayFormat` in beforeEach.

2024-03-18 06:47 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +            this.instance.option('value', new Date('10/10/2012 10:00 PM'));
This operation is common for all tests => it can be moved to `beforeEach`

2024-03-18 07:41 UTC, ksercs commented on packages/devextreme/testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +    beforeEach: function() {
if we have nothing to do additionally in `beforeEach` we can just pass already existing setupModule

2024-03-18 07:51 UTC, ksercs approved these changes

2024-03-18 08:41 UTC, ksercs approved these changes

2024-03-18 14:21 UTC, EugeniyKiyashko approved these changes

2024-03-19 07:03 UTC, merged