Save dx component classes when using a custom class attribute (T1243735)
DevExpress/DevExtreme pull request #27818
Opened 2024-07-23 07:34 UTC by dxvladislavvolkov

2024-07-23 08:22 UTC, ivanblinov2k17 submitted a review, later dismissed

2024-07-23 11:07 UTC, VasilyStrelyaev requested changes

2024-07-23 11:07 UTC, VasilyStrelyaev commented on packages/devextreme-vue/src/core/component.ts
> +const dxClasses: string[] = [];
This is going to be one "static" array for all the Vue components on the page, which does not seem good

2024-07-23 11:07 UTC, VasilyStrelyaev commented on packages/devextreme-vue/src/core/component.ts
> +      dxClasses.push(item);
Is it okay that we only accumulate class names in this array and never remove them? Could there be duplicates?

2024-07-23 11:07 UTC, VasilyStrelyaev commented on packages/devextreme-vue/src/core/component.ts
> +      pickOutDxClasses(this.$el, this.$attrs);
I'm also worried that if we pick classes on mount, will they be relevant at the moment we restore them?

I mean, the Widget may change its dx classes dynamically, are we sure that what we pick here stays relevant at the moment of restoration?

2024-07-23 11:10 UTC, VasilyStrelyaev commented
Overall, I think we need just tests on the mentioned scenarios:
1) two components on the page
2) component that updates a couple of times (there should be no dx class duplicates)
3) components whose dynamical class is changed after the Widget changes it dx classes (the latest version of Widget's dx classes should be restored)

2024-07-24 09:30 UTC, VasilyStrelyaev approved these changes

2024-07-24 10:29 UTC, merged