T601556: SelectBox - Data request is executed each time the widget with some selected value loses focus
DevExpress/DevExtreme pull request #2807
Opened 2018-02-01 10:35 UTC by mrjohn0011

2018-02-01 15:21 UTC, jsdmitry submitted a review, later dismissed

2018-02-02 06:54 UTC, jsdmitry approved these changes

2018-02-02 06:55 UTC, jsdmitry requested changes
this._displayGetter(oldSelectedItem) !== this._searchValue()

2018-02-02 07:49 UTC, lukyanovas submitted a review, later dismissed
LGTM

2018-02-02 08:31 UTC, jsdmitry approved these changes

2018-02-02 08:31 UTC, merged