Chat: Add localization
DevExpress/DevExtreme pull request #28123
Opened 2024-09-30 11:06 UTC by marker-dao

2024-09-30 12:10 UTC, vladaskorohodova submitted a review, later dismissed

2024-10-01 12:27 UTC, vladaskorohodova approved these changes, later dismissed

2024-10-01 12:31 UTC, ksercs commented on packages/devextreme/js/localization/messages/zh-tw.json
> +        "dxAvatar-imageAlt": "Avatar",
Shouldn't it be by analogy with `"dxAvatar-defaultUserName"`?
```suggestion
        "dxAvatar-defaultImageAlt": "Avatar",
```

2024-10-01 12:37 UTC, ksercs requested changes

2024-10-01 12:37 UTC, ksercs commented on packages/devextreme/js/localization/messages/zh-tw.json
> +        "dxAvatar-defaultUserName": "Unknown User",
For what? I don't think we should publish it. First of all because there is no avatar at the moment. But even if we have it, Avatar does not have "username", it'll mostly have other API like "letters/text".
So please remove it

2024-10-01 13:06 UTC, marker-dao commented on packages/devextreme/js/localization/messages/zh-tw.json
> +        "dxAvatar-imageAlt": "Avatar",
[aa1c45fcfe057ea307c9912fa5e14fa0c4a5a231]

2024-10-01 13:07 UTC, marker-dao commented on packages/devextreme/js/localization/messages/zh-tw.json
> +        "dxAvatar-defaultUserName": "Unknown User",
[aa1c45fcfe057ea307c9912fa5e14fa0c4a5a231]

2024-10-01 13:09 UTC, EugeniyKiyashko approved these changes, later dismissed

2024-10-01 13:10 UTC, ksercs approved these changes, later dismissed

2024-10-02 05:51 UTC, vladaskorohodova submitted a review, later dismissed

2024-10-02 09:21 UTC, ksercs approved these changes

2024-10-02 09:22 UTC, nikkithelegendarypokemonster approved these changes

2024-10-02 09:37 UTC, vladaskorohodova approved these changes

2024-10-02 11:07 UTC, merged