Button Group: added string value in ButtonTypes for custom type value
DevExpress/DevExtreme pull request #28256
Opened 2024-10-28 08:57 UTC by nikkithelegendarypokemonster

2024-10-28 11:53 UTC, ksercs requested changes
@nikkithelegendarypokemonster your change is related to Button, not a Button Group. Please update the name with `Button: extend ButtonType with any string`

2024-10-28 11:53 UTC, ksercs commented on packages/devextreme/js/common.d.ts
> +export type ButtonType = 'danger' | 'default' | 'normal' | 'success' | 'string';
[incorrect solution]
You've just added one more possible value `"string"`, but we need this option to accept any string value besides predefined (how it's done for text above)

2024-10-28 12:33 UTC, ksercs approved these changes

2024-10-28 21:31 UTC, EugeniyKiyashko approved these changes

2024-10-30 11:27 UTC, mpreyskurantov approved these changes

2024-10-31 16:09 UTC, merged