Map - unskip demos tests
DevExpress/DevExtreme pull request #28533
Opened 2024-12-11 03:36 UTC by Zedwag

2024-12-25 06:35 UTC, EugeniyKiyashko approved these changes, later dismissed

2025-01-13 03:10 UTC, pomahtri requested changes

2025-01-13 03:10 UTC, pomahtri commented on apps/demos/testing/common.test.js
> +  const EXPECTED_CONSOLE_MESSAGES = {
Please, move this constant to known-warning.json file
Also, it would be good if you guys could plan task with moving other consts to according files too (like, create `known-a11y-issues.json`, `known-screenshot-issues.json` etc)

2025-01-23 12:34 UTC, EugeniyKiyashko approved these changes

2025-01-24 05:57 UTC, pomahtri approved these changes

2025-01-24 06:12 UTC, merged