ThemeBuilder: clean imports from bootstrap _variables.scss
DevExpress/DevExtreme pull request #28552
Opened 2024-12-13 09:08 UTC by GoodDayForSurf

2024-12-13 14:23 UTC, dxvladislavvolkov approved these changes, later dismissed

2024-12-18 20:51 UTC, mpreyskurantov commented
Why so many garbage commits, if this is a cherry-pick?

2024-12-18 20:53 UTC, mpreyskurantov requested changes
Why so many garbage commits, if this is a cherry-pick?

2024-12-19 14:27 UTC, mpreyskurantov approved these changes

2024-12-19 15:03 UTC, merged