Add doc comment for dxOverlayOptions_position
DevExpress/DevExtreme pull request #3030
Opened 2018-02-20 14:16 UTC by AntonSermyazhko

2018-02-22 12:52 UTC, RomanTsukanov submitted a review, later dismissed

2018-02-27 09:00 UTC, San4es commented
Clarification:

The `position` option accepts 'left', 'top', 'right', 'bottom' and 'center' starting with [this PR](https://github.com/DevExpress/DevExtreme/pull/2601).

`Enums.Position` has no 'center' item:
https://github.com/DevExpress/DevExtreme/blob/17_2/js/docEnums.js#L137-L140

2018-02-27 09:34 UTC, San4es commented
I suggest creating a separate enum (e.g. OverlayPosition) with "center", "left", "right", "top", "bottom" items.

@AntonSermyazhko @RomanTsukanov @lukyanovas @KsyushaM @vconst 
What do you think?

2018-02-27 09:37 UTC, San4es requested changes

2018-02-27 09:37 UTC, San4es commented on js/ui/overlay.js
> +            * @type Enums.Position|positionConfig|function
This enum has no "center" item.

2018-02-27 09:58 UTC, RomanTsukanov commented
@San4es seems like a good idea

2018-02-27 14:14 UTC, San4es commented
@AntonSermyazhko @vconst @RomanTsukanov 
FYI:
https://github.com/DevExpress/DevExtreme/pull/3111

Looks like we need to close this PR :)

2018-02-27 14:15 UTC, closed without merging