Extend doc comment for dxOverlayOptions_position
DevExpress/DevExtreme pull request #3070
Opened 2018-02-22 11:59 UTC by AntonSermyazhko

2018-02-22 12:53 UTC, RomanTsukanov submitted a review, later dismissed

2018-02-27 11:15 UTC, San4es requested changes

2018-02-27 11:15 UTC, San4es commented on js/ui/overlay.js
> +            * @type Enums.Position|positionConfig|function
This enum has no 'center' item. See conversation in PR #3030.

2018-02-27 14:17 UTC, San4es commented
We will cherry-pick this PR #3111.

2018-02-28 07:58 UTC, lukyanovas commented
https://github.com/DevExpress/DevExtreme/pull/3117

2018-02-28 07:58 UTC, closed without merging