Add "no-multiple-empty-line" lint rule
DevExpress/DevExtreme pull request #3119
Opened 2018-02-28 09:36 UTC by anna-zhernovkova

2018-02-28 09:44 UTC, nightskylark approved these changes

2018-02-28 10:06 UTC, lukyanovas approved these changes

2018-02-28 10:42 UTC, pavelgruba approved these changes

2018-02-28 12:07 UTC, DokaRus approved these changes

2018-02-28 21:39 UTC, vconst approved these changes

2018-03-01 15:23 UTC, vconst requested changes
Why? It is better to add prettier.

2018-03-01 16:12 UTC, nightskylark commented
Let`s decide that we will make a cherry-pick of this PR and previous one into the 17.2 brunch and postpone the question about auto-fix code on pre-commit till code-freeze.

2018-03-05 08:59 UTC, vconst approved these changes

2018-03-05 09:00 UTC, merged