Fix hide submenu on mouseleave event when relatedTarget is children of target
DevExpress/DevExtreme pull request #3264
Opened 2018-03-13 11:52 UTC by dxvladislavvolkov

2018-03-13 16:17 UTC, nightskylark requested changes

2018-03-13 16:17 UTC, nightskylark commented on js/events/core/events_engine.js
> +                    secondaryTargetIsOutside = !relatedTarget || (relatedTarget !== target && !(target && e.currentTarget.contains(relatedTarget))),
I think it should be refactored.
Try this:
```
secondaryTargetIsOutside = !relatedTarget || !target || relatedTarget !== target && !target.contains(relatedTarget)
```

2018-03-13 16:17 UTC, nightskylark commented on testing/tests/DevExpress.ui.events/eventsEngine.tests.js
> +    var event = new eventsEngine.Event("someEvent", { target: div, relatedTarget: div.children[0] });
It's better to rename `div2` to something like `childNode` and use it instead of ` div.children[0]`.

2018-03-14 13:55 UTC, nightskylark approved these changes

2018-03-14 13:59 UTC, ovchinnikov approved these changes

2018-03-14 14:00 UTC, merged