Documentation - Use Enums.Mode for options that have only "auto" in accepted values
DevExpress/DevExtreme pull request #3523
Opened 2018-04-04 09:14 UTC by San4es

Сonsistently with:
https://github.com/DevExpress/DevExtreme/blob/5cf6845a9476869d82a5fd5be4905aa0c702a7af/js/ui/box.js#L789-L792
https://github.com/DevExpress/DevExtreme/blob/615ad101f6bb7347817d13167ede9b6b1c8dd1b2/js/ui/data_grid/ui.data_grid.grouping.js#L745-L748
https://github.com/DevExpress/DevExtreme/blob/1da1f301737e56bca94891f9829f32c6cd4277a2/js/ui/form/ui.form.js#L76-L79
https://github.com/DevExpress/DevExtreme/blob/7fa0c31705ad8a8197b401f90c0f5b4c8bb79a59/js/ui/responsive_box.js#L41-L44

Pros:
- Use one way for similar cases.
- Get rid of strange "Accepted Values: 'auto' | true | false" in API reference. For instance: https://js.devexpress.com/Documentation/18_1/ApiReference/UI_Widgets/dxDataGrid/Configuration/pager/#visible
- More strongly-typed `OptionX(Mode)` overload on MVC Controls side (`OptionX(string)` now).

2018-04-04 09:42 UTC, RomanTsukanov commented
More possible entries:

https://github.com/DevExpress/DevExtreme/blob/5cf6845a9476869d82a5fd5be4905aa0c702a7af/js/ui/grid_core/ui.grid_core.data_controller.js#L48

https://github.com/DevExpress/DevExtreme/blob/5cf6845a9476869d82a5fd5be4905aa0c702a7af/js/ui/grid_core/ui.grid_core.data_controller.js#L54

https://github.com/DevExpress/DevExtreme/blob/5cf6845a9476869d82a5fd5be4905aa0c702a7af/js/ui/grid_core/ui.grid_core.rows.js#L98

https://github.com/DevExpress/DevExtreme/blob/5cf6845a9476869d82a5fd5be4905aa0c702a7af/js/ui/pivot_grid/ui.pivot_grid.js#L206

2018-04-04 09:43 UTC, AntonSermyazhko approved these changes

2018-04-04 09:56 UTC, lukyanovas approved these changes

2018-04-04 13:31 UTC, IlyaKhD requested changes
Agreed with Roman, it seems that more options could be declared with `Enums.Mode`

2018-04-04 13:39 UTC, AlekseyMartynov commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
Not clean. Bools are not allowed.

2018-04-04 14:45 UTC, San4es commented
>More possible entries

@RomanTsukanov @IlyaKhD 

These options do not use @acceptvalues, are we sure that "auto" is single string-typed accepted value for all of them?

2018-04-04 14:49 UTC, San4es commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
@AlekseyMartynov 

The Enums.Mode enum does not contain any bool values:
https://github.com/DevExpress/DevExtreme/blob/18_1/js/docEnums.js#L107-L110

2018-04-04 14:57 UTC, RomanTsukanov commented
@San4es I'm pretty sure it is.

2018-04-04 15:31 UTC, AlekseyMartynov commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
😮 
Enum of a single item?
@IlyaKhD 👏

2018-04-04 15:32 UTC, IlyaKhD commented
Moreover, if an option accepts `'auto'` as well as other `string` values, we should declare it as `@type Enum.Mode|string` in most cases.

2018-04-04 15:36 UTC, AlekseyMartynov commented
@IlyaKhD 
Re `Enums.Mode`, does it make any sense? It looks all wrong.
Has it been released yet?

2018-04-05 08:07 UTC, San4es commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
> Enum of a single item?

Yes. Historically (starting with 16.1) we use it already for some options (BoxItem.ratio, DataGridOptions.groupPanel.visible, FormOptions.colCount) on the MVC side.

Our (my and @lukyanovas) idea: other options that have "auto" as accepted value can use this enum. More strongly-typed `OptionX(Mode)` overload is better than `OptionX(string)` one which we have now.

2018-04-05 08:11 UTC, San4es commented
>Re Enums.Mode, does it make any sense? It looks all wrong.
Has it been released yet?

This enum was born in 16.1 for BoxItem.ratio, DataGridOptions.groupPanel.visible, FormOptions.colCount options on the MVC controls side and lives already for 5 releases.
I agree that this solution is not ideal, but it better than "string".

2018-04-05 08:21 UTC, lukyanovas commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
I think for TS  ```number[] | "auto"``` is also more useful than ```number[] | string```

2018-04-05 08:27 UTC, AlekseyMartynov commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
Я нами нэдоволэн 💩

2018-04-05 08:34 UTC, AlekseyMartynov commented on js/ui/grid_core/ui.grid_core.pager.js
> +                 * @type Array<number>|Enums.Mode
@lukyanovas 
In TS it's fine.
My concern is about C# code which is kind of stupid:

```c#
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Mode {
        [EnumMember(Value = "auto")]
        Auto
    }
```

But as @San4es explained, we overlooked it 5 releases ago. So let's live with it...

2018-04-05 09:32 UTC, IlyaKhD commented
So, talking about declarations, `Enums.Mode` was migrated from the SMD "as is". We could fix this on the MVC side, and keep normalizing declarations using `Enums.Mode`.

@AlekseyMartynov, @San4es how do you think?

2018-04-12 11:35 UTC, San4es commented
Considering the entire feedback above we decided to make [an alternative solution](https://github.com/DevExpress/DevExtreme/pull/3634).

2018-04-12 12:28 UTC, closed without merging