Fix TreeView items duplication when the virtual mode is active (T616920)
DevExpress/DevExtreme pull request #3537
Opened 2018-04-04 13:09 UTC by DokaRus

2018-04-04 13:24 UTC, mrjohn0011 requested changes

2018-04-04 13:24 UTC, mrjohn0011 commented on js/ui/tree_view/ui.tree_view.base.js
> +            if(!that._areItemsExists(newItems, that.option("items"))) {
Use dataAdapter for this purpose. It contains full dataStructure and array of loaded item keys (getIndexByKey method)

2018-04-04 14:16 UTC, DokaRus commented on js/ui/tree_view/ui.tree_view.base.js
> +            if(!that._areItemsExists(newItems, that.option("items"))) {
`getIndexByKey` actual for the items displayed at the moment. If we search something, we can operate only with raw `initialDataStructure`

2018-04-05 07:46 UTC, mrjohn0011 approved these changes

2018-04-05 07:59 UTC, merged