dxDataGrid: Fix "role", "aria-colindex" attributes for the command column
DevExpress/DevExtreme pull request #3864
Opened 2018-04-27 12:06 UTC by AntonSermyazhko

2018-05-24 13:14 UTC, mrjohn0011 submitted a review, later dismissed

2018-05-25 09:23 UTC, vconst requested changes

2018-05-25 09:23 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_view.js
> +        if(cellOptions.rowType !== "freeSpace" && cellOptions.rowType !== "header") {
The strange condition is the base ColumnsView class. The base class should not know about descendants.

2018-05-28 09:56 UTC, vconst approved these changes

2018-05-28 09:56 UTC, vconst commented on js/ui/grid_core/ui.grid_core.column_headers.js
>                              this.setAria("colindex", options.column.index + 1, $cell);
This is wrong. The column.index is not the visible index

2018-05-28 10:07 UTC, merged