Implement styles for material theme in dxLookup
DevExpress/DevExtreme pull request #3897
Opened 2018-05-03 17:43 UTC by groshenkovamarina

2018-05-04 06:35 UTC, babich-a commented on js/ui/lookup.js
> +        this._list.scrollToItem(selectedIndex);
Why do we need to scroll to the last item first and then to the selectedItem?

2018-05-04 06:38 UTC, DokaRus requested changes

2018-05-04 06:38 UTC, DokaRus commented on js/ui/lookup.js
> +                     * @default undefined @for Material
But default value is `(function() { return this._$element.outerWidth(); }).bind(this)`

2018-05-04 06:38 UTC, DokaRus commented on js/ui/lookup.js
> +                    popupHeight: (function() { return this._setPopupHeight(MATERIAL_LOOKUP_LIST_ITEMS_COUNT); }).bind(this),
>_setPopupHeight

It's confusing. Function's name tells that it is a setter but in fact, it's a getter?

2018-05-04 06:38 UTC, DokaRus commented on js/ui/lookup.js
> +                     * @default undefined @for Material
You define a default value below

2018-05-04 06:38 UTC, DokaRus commented on js/ui/lookup.js
> +                    * @default undefined @for Material
You have described `position` config below

2018-05-04 06:39 UTC, babich-a commented on testing/tests/DevExpress.ui/defaultOptions.tests.js
> +
Let's remove empty lines after each option.

2018-05-04 08:21 UTC, mrjohn0011 submitted a review, later dismissed

2018-05-04 08:21 UTC, mrjohn0011 commented on js/ui/lookup.js
> +            translator.resetPosition(this._popup._$content);
Use this._popup.$content() method

2018-05-04 08:21 UTC, mrjohn0011 commented on js/ui/lookup.js
> +            this._popup._changePosition({ left: 0, top: -popupOffsetY });
Can you use this._popup.option("position") here? Don't use private methods

2018-05-04 08:21 UTC, mrjohn0011 commented on js/ui/lookup.js
> +            var differenceOfOffsets = selectedListItem.offset().top - this._popup._$content.offset().top;
use popup.$content()

2018-05-04 08:21 UTC, mrjohn0011 commented on js/ui/lookup.js
> +            selectedListItem = this._list._$element.find("." + this._list._selectedItemClass()),
Don't use double private methods anywhere. `_list._method` should be never used. Use another way to get selected item element from the list

2018-05-04 08:21 UTC, mrjohn0011 commented on js/ui/lookup.js
> +            this._list.scrollToItem({ group: itemsCount - 1, item: listItems[itemsCount - 1].items.length - 1 });
Check that the widget with grouped strategy does not crash if there are no items in it. Write a test

2018-05-04 08:21 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/lookup.tests.js
> +
remove one empty string

2018-05-04 08:21 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/lookup.tests.js
> +        $(lookup._$field).trigger("dxclick");
Don't use private methods outside of the owner widget

2018-05-04 08:21 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/lookup.tests.js
> +        $(lookup._$field).trigger("dxclick");
Don't use private methods outside of the owner widget

2018-05-04 08:21 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/lookup.tests.js
> +        $(lookup._$field).trigger("dxclick");
Don't use private methods outside of the owner widget

2018-05-04 14:24 UTC, groshenkovamarina commented on js/ui/lookup.js
> +            this._popup._changePosition({ left: 0, top: -popupOffsetY });
Can't, doesn't work, if set this._popup.option("position").offset here

2018-05-04 14:42 UTC, DokaRus requested changes

2018-05-04 14:42 UTC, DokaRus commented on js/ui/lookup.js
> +
Remove empty line, pls

2018-05-04 14:42 UTC, DokaRus commented on js/ui/lookup.js
> +
Remove empty line between doccoment and option for all cases below

2018-05-04 14:42 UTC, DokaRus commented on js/ui/lookup.js
> +            translator.resetPosition(this._popup.$element().find(".dx-overlay-content"));
Use `element()` instead of `$element()`

2018-05-04 14:42 UTC, DokaRus commented on js/ui/lookup.js
> +
Remove a redundant empty line

2018-05-04 14:49 UTC, lukyanovas commented
Separators in doc-comments have been changed in #3896 Please, rebase your PR.

2018-05-05 09:47 UTC, lukyanovas commented on js/ui/lookup.js
> +                    * @name dxLookupOptions_usePopover
dxLookupOptions_usePopover => dxLookupOptions.usePopover

2018-05-05 13:02 UTC, groshenkovamarina commented on js/ui/lookup.js
> +                    * @name dxLookupOptions_usePopover
Fixed

2018-05-05 17:51 UTC, DokaRus submitted a review, later dismissed

2018-05-07 11:41 UTC, babich-a commented on js/ui/lookup.js
> +            this._popup._changePosition({ left: 0, top: -popupOffsetY });
fixed

2018-05-07 11:52 UTC, DokaRus commented on js/ui/lookup.js
> +
Remove empty line

2018-05-07 11:52 UTC, DokaRus commented on js/ui/lookup.js
> +
Remove empty line

2018-05-07 11:57 UTC, DokaRus approved these changes

2018-05-07 12:09 UTC, merged