Dispose view on navigation when cache is cleared (T627856)
DevExpress/DevExtreme pull request #4100
Opened 2018-05-24 09:43 UTC by anna-zhernovkova

2018-05-24 11:13 UTC, nightskylark submitted a review, later dismissed

2018-05-24 11:19 UTC, AlekseyMartynov commented
@dxbykov 😝

2018-05-25 08:55 UTC, dxbykov requested changes

2018-05-25 08:55 UTC, dxbykov commented on js/framework/application.js
>              args;
This variable is not used in its method scope.

2018-05-25 08:55 UTC, dxbykov commented on js/framework/application.js
> +        var disposeView = function(viewInfo) {
I see no reason to recreate this function on each method call. It can be a regular class (private) method.

2018-05-25 08:55 UTC, dxbykov commented on js/framework/application.js
> +            hash = this._viewLinksHash[key];
Naming. It's not actually a hash (the key is a hash). It's rather a 'view link' (hash -> viewLink)

2018-05-25 08:55 UTC, dxbykov commented on js/framework/application.js
> +        var createViewLinkHash = function() {
This function looks strange to me. Can't we remove it and use the following code below:

```
        if(!viewLink) {
             this._viewLinksHash[key] = {
                 viewInfo: viewInfo,
                 linkCount: 1
             };
        } else {
            if(viewLink.viewInfo !== viewInfo) {
                this._removedViewInfos.push(viewLink.viewInfo);
                viewLink.viewInfo = viewInfo;
                // should viewLink.linkCount already be 1 here ???
            } else {
                viewLink.linkCount++;
            }
         }
```

2018-05-25 09:22 UTC, dxbykov approved these changes

2018-05-28 05:09 UTC, merged