Provide component instance type in callbacks and methods
DevExpress/DevExtreme pull request #4288
Opened 2018-06-08 10:38 UTC by lukyanovas

Fixes [T613738](https://www.devexpress.com/Support/Center/Question/Details/T613738)

2018-06-08 15:14 UTC, IlyaKhD commented
I suggest generating classes, that have no derived classes as non-generics.
E.g. instead of
```ts
export interface dxAccordionOptions<T = dxAccordion> extends CollectionWidgetOptions<T> {
```
generate this:
```ts
export interface dxAccordionOptions extends CollectionWidgetOptions<dxAccordion> {
```

2018-06-08 15:17 UTC, IlyaKhD requested changes
Generate interfaces, that are not derived from as non-generics

2018-06-08 15:33 UTC, lukyanovas commented
@IlyaKhD 
well, let's try to generate! 😃

2018-06-09 20:13 UTC, San4es commented on js/core/component.js
> +            * @type_function_param1_field1 component:this
The 'this' string as a type looks strange for me on the documentation comments side.

2018-06-14 09:22 UTC, lukyanovas commented
@IlyaKhD 
Please, check the new changes.

@San4es 
It's some kind of compromise. We had 3 options:
1) to add "this" type like in TS
2) to transform all ComponentOptions to generic interfaces
3) to duplicate all callback doc-comments

We think that "this" type is less confusing of these.

2018-06-14 10:01 UTC, IlyaKhD approved these changes

2018-06-14 10:36 UTC, merged