Fix T525376: dxSelectBox selection is case insensitive (#436)
DevExpress/DevExtreme pull request #440
Opened 2017-06-20 14:16 UTC by sometimesElen

2017-06-20 14:28 UTC, lukyanovas approved these changes

2017-06-20 14:30 UTC, lukyanovas requested changes

2017-06-20 14:30 UTC, lukyanovas commented on testing/tests/DevExpress.ui.widgets.editors/dropDownList.tests.js
> +    assert.equal(instance._input().val(), "");
don't call private method _input

2017-06-20 20:57 UTC, lukyanovas approved these changes

2017-06-21 07:43 UTC, DokaRus approved these changes

2017-06-21 08:27 UTC, merged