Get rid of templatesRenderAsynchronously flag from dxScheduler
DevExpress/DevExtreme pull request #446
Opened 2017-06-20 20:55 UTC by dxvladislavvolkov

2017-06-21 09:31 UTC, lukyanovas requested changes

2017-06-21 09:31 UTC, lukyanovas commented on testing/tests/DevExpress.ui.widgets.scheduler/integrationParts/appointments.tests.js
> -    this.instance.option("templatesRenderAsynchronously", true);
I suppose this test is outdated. You should remove it. Also, please locally check scenario from T515894 with AngularJS.

2017-06-21 11:08 UTC, lukyanovas submitted a review, later dismissed

2017-06-22 10:16 UTC, KsyushaM approved these changes

2017-06-22 10:17 UTC, merged