Fix filter area in PivotGrid FiledPanel when there is a lot of fields on it (T645658)
DevExpress/DevExtreme pull request #4518
Opened 2018-06-27 16:26 UTC by sometimesElen

2018-06-28 13:12 UTC, vconst requested changes

2018-06-28 13:12 UTC, vconst commented on styles/widgets/base/pivotGrid.less
> +        .dx-area-field-container{
The space is skipped

2018-06-28 13:12 UTC, vconst commented on styles/widgets/base/pivotGrid.less
> +                padding: 2px;
Use constant for number

2018-06-28 13:12 UTC, vconst commented on styles/widgets/base/pivotGrid.less
> +            padding-left: @PIVOTGRID_COMMON_LEFT_RIGHT_PADDING;
This style is not necessary

2018-07-02 10:56 UTC, vconst requested changes

2018-07-02 10:56 UTC, vconst commented on styles/widgets/base/pivotGrid.less
> +            border-spacing: @PIVOTGRID_FILTER_AREA_BORDING_SPACING;
BORDING_SPACING?

2018-07-02 16:46 UTC, roman-simionov approved these changes

2018-07-03 07:59 UTC, vconst approved these changes

2018-07-03 08:48 UTC, merged