Improve TreeView less styles
DevExpress/DevExtreme pull request #4576
Opened 2018-07-04 16:05 UTC by alexander-kotov-dx

2018-07-04 17:48 UTC, San4es commented
CSS classes renaming, massive changes in LESS hierarchy are looking like a breaking change to me - it can break user CSS customization by class selectors.

Can we:
 - do this changes for 18_2 branch **first**?
 - do this changes for 18_2 branch **only**?

2018-07-05 08:43 UTC, mrjohn0011 requested changes

2018-07-05 08:43 UTC, mrjohn0011 commented on js/ui/tree_view/ui.tree_view.base.js
> -    TOGGLE_ITEM_VISIBILITY_CLASS = "dx-treeview-toggle-item-visibility",
We should discuss about the possible breaking change with @jsdmitry and support team

2018-07-05 08:43 UTC, mrjohn0011 commented on js/ui/tree_view/ui.tree_view.base.js
> -    TOGGLE_ITEM_VISIBILITY_OPENED_CLASS = "dx-treeview-toggle-item-visibility-opened",
We should discuss about the possible breaking change with @jsdmitry and support team

2018-07-05 08:43 UTC, mrjohn0011 commented on styles/widgets/android5/menu.android5.less
> -        .dx-treeview-toggle-item-visibility {
I think this selector can be replaced to the root level

2018-07-05 08:43 UTC, mrjohn0011 commented on styles/widgets/android5/treeView.android5.less
> +    .dx-treeview-item-content {
I think this selector can be replaced to the root level

2018-07-05 08:43 UTC, mrjohn0011 commented on styles/widgets/common/menu.less
>      .dx-treeview {
Can we remove .dx-treeview selector?

2018-07-05 08:43 UTC, mrjohn0011 commented on styles/widgets/generic/treeView.generic.less
> +&.dx-treeview-with-search > .dx-scrollable {
Can we remove & from the root-level selector?

2018-07-05 08:43 UTC, mrjohn0011 commented on styles/widgets/generic/treeView.generic.less
> +    &:not(.dx-treeview-item-with-checkbox) {
Can we get rid of &not selector?

2018-07-05 09:05 UTC, mrjohn0011 commented on styles/widgets/generic/treeView.generic.less
> +                * {
Can we remove '*'?

2018-07-05 09:05 UTC, mrjohn0011 commented on styles/widgets/ios7/treeView.ios7.less
> +    &:not(.dx-treeview-item-with-checkbox) {
Try to simplify selectors with 'background-color' property

2018-07-05 09:29 UTC, DokaRus commented on styles/widgets/android5/treeView.android5.less
> +&.dx-treeview-with-search > .dx-scrollable {
Looks like there is no need to use `&` after a style extracting

2018-07-05 09:29 UTC, DokaRus commented on styles/widgets/android5/treeView.android5.less
> +    border: 1px solid @ANDROID5_TREE_VIEW_BORDER_COLOR;
Looks like there is no need to use `&` after a style extracting

2018-07-05 19:00 UTC, DokaRus commented
You need to rebase the PR branch onto 18_2

2018-07-11 13:47 UTC, closed without merging