Sankey datasource format
DevExpress/DevExtreme pull request #4774
Opened 2018-07-23 11:18 UTC by sokolov11

1. Data source format changed to
'''
[{source:<string>, target:<string>, weight: <number>}, ... ]
'''
2. Data validator messages changed
3. Default theme values (borders and colours) changed
4. The height of nodes is tuned accordingly with heights of links rounded to integer values

2018-07-23 13:29 UTC, viterobk submitted a review, later dismissed

2018-07-23 14:41 UTC, pavelgruba submitted a review, later dismissed

2018-07-24 07:37 UTC, viterobk requested changes

2018-07-24 07:37 UTC, viterobk commented on js/viz/docs/docSankey.js
> +        * @type Enums.SankeyLabeloverlappingBehavior
SankeyLabel-o-verlappingBehavior - "o" should be capitalized.

2018-07-24 13:36 UTC, pavelgruba approved these changes

2018-07-25 07:24 UTC, viterobk approved these changes

2018-07-25 08:56 UTC, merged