Change dxTreeView expandEvent option type to String
DevExpress/DevExtreme pull request #4879
Opened 2018-08-01 12:59 UTC by mrjohn0011

2018-08-01 13:51 UTC, San4es requested changes

2018-08-01 13:51 UTC, San4es commented on js/ui/tree_view/ui.tree_view.base.js
> +             * @type String
String -> string

2018-08-02 13:43 UTC, San4es approved these changes

2018-08-02 14:00 UTC, jsdmitry approved these changes

2018-08-02 14:14 UTC, TikhonovaTatyana reviewed
Add @acceptValues

2018-08-02 14:22 UTC, San4es commented
>Add @acceptValues

The `@acceptValues` attribute is obsolete. In fact, it is the same thing as `@enum` and `@type Enums.SomeEnumName`.

2018-08-02 14:32 UTC, TikhonovaTatyana requested changes
There should be acceptValues or Enum, if the option works only with click and dblclick

2018-08-02 14:33 UTC, San4es commented
> if the option works **only with click and dblclick**

@mrjohn0011  @lukyanovas  what about other events: dxclick, dxhold, etc?

2018-08-03 12:49 UTC, mrjohn0011 commented
We (Me and @San4es) have decided to close this pull request because it is more convenient to use Enum with all accepted values than string.

2018-08-03 12:55 UTC, closed without merging