"outcoming" -> "outgoing"
DevExpress/DevExtreme pull request #4894
Opened 2018-08-02 09:27 UTC by sokolov11

2018-08-02 11:31 UTC, RomanTsukanov submitted a review, later dismissed

2018-08-02 13:39 UTC, pavelgruba requested changes

2018-08-02 13:39 UTC, pavelgruba commented on js/viz/sankey/tooltip.js
> +            var res = isFunction(customCallback) ? customCallback(objectInfo) : {};
customCallback should have objectInfo as the context

2018-08-02 14:14 UTC, pavelgruba approved these changes

2018-08-03 06:56 UTC, RomanTsukanov approved these changes

2018-08-03 07:24 UTC, merged