Add xhr object and a request settings to arguments of errorHandler
DevExpress/DevExtreme pull request #5062
Opened 2018-08-16 09:26 UTC by dxvladislavvolkov

Feature request from a customer (see more info [here](https://www.devexpress.com/Support/Center/Question/Details/T641930/the-errorhandler-callback-doesn-t-have-the-same-parameters-as-ajaxerror)).

2018-08-16 10:26 UTC, AlekseyMartynov requested changes
We're discussing this changeset in the internal chat.

2018-08-17 08:52 UTC, AlekseyMartynov commented on js/data/odata/context.js
> +         * @type_function_param1_field2 errorDetails:boolean
`errorDetails` is not `boolean`.

2018-08-17 09:00 UTC, AlekseyMartynov commented on js/data/odata/context.js
> +         * @type_function_param1_field2 errorDetails:boolean
It's an object
https://github.com/DevExpress/DevExtreme/blob/7a8b9942408894e28a39f70d0c49532695ddbe84/testing/tests/DevExpress.data/odataStore.tests.js#L1763-L1775

2018-08-17 11:29 UTC, ovchinnikov approved these changes

2018-08-17 12:02 UTC, AlekseyMartynov approved these changes

2018-08-17 12:18 UTC, merged