Change names and add checks for command line arguments in ThemeBuilder
DevExpress/DevExtreme pull request #5183
Opened 2018-08-24 12:45 UTC by babich-a

2018-08-24 15:09 UTC, BingoRUS requested changes

2018-08-24 15:09 UTC, BingoRUS commented on themebuilder/package.json
> +    "devextreme-themebuilder": "cli/index.js"
We don't need commands to be available for this npm package. Let's remove it.

2018-08-24 15:23 UTC, BingoRUS submitted a review, later dismissed
👍

2018-08-27 04:27 UTC, babich-a commented
Sure. I also add info about swatch selector will be used. Check it, please.

2018-08-27 12:49 UTC, BingoRUS approved these changes
👌

2018-08-27 13:53 UTC, merged