Implement attr, removeAttr, prop and removeProp methods
DevExpress/DevExtreme pull request #531
Opened 2017-06-27 12:22 UTC by dxvladislavvolkov

2017-06-27 12:34 UTC, ovchinnikov requested changes

2017-06-27 12:34 UTC, ovchinnikov commented on js/core/renderer.js
> +    var propFix = {};
PropFix have to be removed. Fix attributes and properties names in code

2017-07-03 08:47 UTC, San4es commented on js/events/click.js
> +        if($element[0].getAttribute) {
Looks like this condition is not equivalent previous one.

2017-07-04 09:54 UTC, ovchinnikov approved these changes

2017-07-04 10:31 UTC, merged