Incapsulate the xhr from fileUploader into the ajax utility
DevExpress/DevExtreme pull request #536
Opened 2017-06-27 15:39 UTC by nightskylark

- Added necessary functionality for the `ajax` utility
- Replaced `XMLHttpRequest` with `ajax` utility in the FileUploader

2017-06-28 13:52 UTC, Aden-git submitted a review, later dismissed

2017-06-28 14:06 UTC, timbset requested changes

2017-06-28 14:06 UTC, timbset commented on js/core/utils/ajax.js
> +    if(options.upload) {
Use negative condition to decrease nesting level
```
if(!options.upload) {
    return $.ajax(options);
}

var xhr = ...
...
```

2017-06-28 14:06 UTC, timbset commented on js/core/utils/ajax.js
> +        xhr.upload["onprogress"] = options.upload["onprogress"];
Why don't you use dot notation?

2017-06-28 14:06 UTC, timbset commented on js/ui/file_uploader.js
> +                "onprogress": function(e) {
Here is redudant quotes

2017-07-03 09:55 UTC, nightskylark commented on js/core/utils/ajax.js
> +    if(options.upload) {
This method will be rewritten much to get rid of $.ajax. But till then for the most scenarios, the $.ajax will be used. So, it`s better to see the upload scenario in the separated condition block.

2017-07-03 09:55 UTC, nightskylark commented on js/core/utils/ajax.js
> +        xhr.upload["onprogress"] = options.upload["onprogress"];
The "onprogress" is not valid word for the linter. I am not sure it is correct to add the linter exception for this words.

2017-07-03 09:55 UTC, nightskylark commented on js/ui/file_uploader.js
> +                "onprogress": function(e) {
The same reason as previous.

2017-07-03 11:04 UTC, timbset approved these changes

2017-07-03 11:57 UTC, ovchinnikov approved these changes

2017-07-03 11:58 UTC, merged