DataSource & Store: Add push API
DevExpress/DevExtreme pull request #5433
Opened 2018-09-14 13:28 UTC by komarovalexander

2018-09-14 13:35 UTC, vconst requested changes

2018-09-14 13:35 UTC, vconst commented on js/data/data_source/data_source.js
> +        this._pushThrottle = new dataUtils.ThrottleWithAggregation(this._onPush, options.pushAggregationTimeout);
This object will be created for each widget with dataSource even if it does not use push functionality. This is not good.

2018-09-14 13:35 UTC, vconst commented on js/data/abstract_store.js
> +                "onPush",
Describe parameters

2018-09-14 13:35 UTC, vconst commented on js/data/abstract_store.js
> +    push: function(changes) {
Add doc comments for arguments

2018-09-14 13:35 UTC, vconst commented on js/data/utils.js
> +    this.indexByKey = function(array, key, keyInfo) {
It will be better if keyInfo will be the first parameter

2018-09-19 21:37 UTC, vconst requested changes

2018-09-19 21:37 UTC, vconst commented on js/data/data_source/data_source.js
> +            this.aggregationTimeoutId = onPushHandler.call(this, changes);
aggregationTimeoutId -> _aggregationTimeoutId

2018-09-19 21:37 UTC, vconst commented on js/data/data_source/data_source.js
> +        this.reshapeOnPush = __isDefined(options.reshapeOnPush) ? options.reshapeOnPush : false;
reshapeOnPush -> _reshapeOnPush

2018-09-19 21:37 UTC, vconst commented on js/data/utils.js
> +function ArrayHelper() {
Why is ArrayHelper class needs? It does not contain any state.  Why methods push, updateArrayItem insertItemToArray, removeItemFromArray are not exported?

2018-09-19 21:37 UTC, vconst commented on js/data/utils.js
> +function createThrottle(func, timeout) {
createThrottle -> throttle?

2018-09-19 21:37 UTC, vconst commented on js/data/utils.js
> +function createThrottleWithAggregation(func, timeout) {
createThrottleWithAggregation -> throttleChanges?

2018-09-20 09:06 UTC, AlekseyMartynov commented
Tests look good.
I sent more feedback to @komarovalexander in a private chat.

2018-09-21 07:05 UTC, vconst requested changes

2018-09-21 07:05 UTC, vconst commented on js/data/data_source/data_source.js
> +            ? dataUtils.throttleChanges(this._onPush, options.pushAggregationTimeout).bind(this)
Why is not this._onPush.bind(this)?

2018-09-21 07:05 UTC, vconst commented on js/data/data_source/data_source.js
> +            this.load();
There is no changes argument in the changed event in this case.

2018-09-21 07:05 UTC, vconst commented on js/data/data_source/data_source.js
> +            this.load();
Also it will be good to have changes argument in the customizeStoreLoadOptions event to invalidate cache for the DataGrid widget.

2018-09-21 07:42 UTC, vconst submitted a review, later dismissed

2018-09-21 08:50 UTC, vconst approved these changes

2018-09-21 08:52 UTC, merged