Add a special class if a TreeView parent node has a selected child
DevExpress/DevExtreme pull request #5564
Opened 2018-09-28 14:07 UTC by alexander-kotov-dx

2018-09-28 14:32 UTC, DokaRus submitted a review, later dismissed

2018-10-02 08:06 UTC, mrjohn0011 requested changes

2018-10-02 08:06 UTC, mrjohn0011 commented on js/ui/hierarchical_collection/ui.data_adapter.js
> +            hasSelectedChild: false,
Why we should use a feature toggle option? There is no breaking change in this feature. This option should be removed

2018-10-02 08:06 UTC, mrjohn0011 commented on js/ui/hierarchical_collection/ui.data_adapter.js
> +                    if(node.internalFields.hasOwnProperty(HASSELECTEDCHILD)) {
Don't use node property to assign a CSS class. Has-selection classes should be reassigned dynamically when the selection was changed

2018-10-02 08:06 UTC, mrjohn0011 commented on js/ui/hierarchical_collection/ui.data_adapter.js
> +    _setParentSelectionProperties: function(withoutSelection) {
Don't use a magic boolean parameter. It is unclear what this function do when we call `_setParentSelectionProperties(true)`

2018-10-02 08:06 UTC, mrjohn0011 commented on js/ui/tree_view/ui.tree_view.base.js
> +        this._toggleSelectionClasses($node, nodeData.selected, nodeData.hasSelectedChild);
This is unclear to use 3 parameters in this method. If the method called `toggleSelectionClasses`, it should assign more than 2 classes. Change the method's signature

2018-10-02 08:06 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets/treeViewParts/selection.js
> +QUnit.test("parent has a special class if node has selected child", function(assert) {
More tests required:

1. Recursive selection is enabled, select a middle-level child. Check if sub-children and parents have this class
2. Select all
3. Recursive selection is enabled/Disabled. Select/Deselect branch
4. Virtual mode/Create children. Select a leaf, load children, check the state
5. Select a parent of the Invisible/disabled children
6. Selection state is assigned on init. Select a middle-level child with the recursive selection. Check the state. Add this test to the server-side rendering (markup) tests

2018-10-02 08:17 UTC, ovchinnikov requested changes

2018-10-02 08:17 UTC, ovchinnikov commented on js/ui/hierarchical_collection/ui.data_adapter.js
> +    HASSELECTEDCHILD = "hasSelectedChild";
I suggest HAS_SELECTED_CHILD name for variable name

2018-10-08 14:54 UTC, closed without merging