Fix Illegal Invocation errors after dxpointermove event (T672275)
DevExpress/DevExtreme pull request #5719
Opened 2018-10-10 12:44 UTC by alexander-kotov-dx

2018-10-10 13:04 UTC, nightskylark requested changes

2018-10-10 13:04 UTC, nightskylark commented on js/events/pointer.js
> +    if(useJQuery && pointerEvent === eventsEngine.passiveListenerEvents.eventName) {
Move it to the jquery integration

2018-10-10 13:07 UTC, ovchinnikov reviewed
This fix should be moved into jQuery integration module.
Also, I suggest to review this thread https://github.com/jquery/jquery/issues/2871 for possible workarounds

2018-10-11 09:09 UTC, nightskylark submitted a review, later dismissed

2018-10-11 09:26 UTC, DokaRus submitted a review, later dismissed

2018-10-11 09:28 UTC, ovchinnikov submitted a review, later dismissed

2018-10-18 16:00 UTC, nightskylark approved these changes

2018-10-19 09:17 UTC, ovchinnikov approved these changes

2018-10-19 09:22 UTC, DokaRus approved these changes

2018-10-19 09:30 UTC, merged