TabPanel rerenders items after badge changed (close #5966)
DevExpress/DevExtreme pull request #6027
Opened 2018-11-02 15:41 UTC by churkin

2018-11-06 09:25 UTC, mrjohn0011 requested changes
You can use an existing method to redraw only changed items

2018-11-06 09:25 UTC, mrjohn0011 commented on js/ui/tab_panel.js
>              case "items":
Try to use `_itemOptionChanged` method like it is done in the base collection widget

2018-11-14 07:47 UTC, churkin commented
@lukyanovas ping

2018-11-14 08:17 UTC, lukyanovas approved these changes
LGTM

2018-11-14 08:21 UTC, mrjohn0011 approved these changes

2018-11-14 08:49 UTC, jsdmitry approved these changes

2018-11-14 08:57 UTC, merged