Update description of the E1051 error
DevExpress/DevExtreme pull request #6092
Opened 2018-11-12 08:02 UTC by DokaRus

2018-11-12 13:01 UTC, churkin requested changes
May be we can add steps to solve the problem to the error message?

2018-11-13 07:26 UTC, TikhonovaTatyana reviewed
@churkin These steps are shown in the error description in the documentation.

2018-11-13 07:26 UTC, TikhonovaTatyana commented on js/ui/widget/ui.errors.js
> +    E1051: "HtmlEditor's valueType is \"{0}\", but the {0} converter is not imported.",
```suggestion
    E1051: "HtmlEditor's valueType is \"{0}\", but the {0} converter was not imported.",
```

2018-11-13 10:55 UTC, TikhonovaTatyana approved these changes

2018-11-14 06:56 UTC, churkin approved these changes

2018-11-14 06:56 UTC, merged