Add possibility to redefine setters for date components in the dxDateBox
DevExpress/DevExtreme pull request #6244
Opened 2018-11-26 15:19 UTC by mrjohn0011

2018-11-26 15:32 UTC, lukyanovas commented on js/ui/date_box/ui.date_box.mask.js
> +            dateComponentSetters: null,
Take a look https://vuejs.org/v2/guide/computed.html#Computed-Setter

2018-11-27 12:04 UTC, RomanTsukanov submitted a review, later dismissed

2018-11-27 15:18 UTC, lukyanovas submitted a review, later dismissed
LGTM

2018-11-27 15:19 UTC, lukyanovas commented on js/ui/date_box/ui.date_box.mask.js
> +            case "dateComponentGetters":
remove this dateComponentGetters

2018-11-27 20:09 UTC, vconst requested changes
Why?

2018-11-30 12:19 UTC, closed without merging