Fix multiple value axes synchronisation when zooming (T684665)
DevExpress/DevExtreme pull request #6425
Opened 2018-12-14 13:25 UTC by jetuuuu

2018-12-14 14:12 UTC, roman-simionov requested changes

2018-12-14 14:12 UTC, roman-simionov commented on js/viz/chart.js
> +        (rotated ? horizontalAxes : verticalAxes).forEach((axis) => {
Use that._valueAxis instead of (rotated ? horizontalAxes : verticalAxes) expression

2018-12-14 16:35 UTC, roman-simionov submitted a review, later dismissed

2018-12-15 11:17 UTC, alexanderPolosatov submitted a review, later dismissed

2018-12-17 08:41 UTC, roman-simionov approved these changes

2018-12-17 08:59 UTC, merged