TagBox should wait for data loading to change selection (close T673636)
DevExpress/DevExtreme pull request #6426
Opened 2018-12-14 15:22 UTC by churkin

2018-12-17 11:59 UTC, Yarovaya commented on js/ui/tag_box.js
> +            that._popup && that._popup.refreshPosition();
You can use this

2018-12-17 12:06 UTC, mrjohn0011 requested changes
Test should be refactored

2018-12-17 12:06 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/tagBox.tests.js
> +                load: () => {
Don't use both ES5 and ES6

2018-12-17 12:06 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/tagBox.tests.js
> +    tagBox._refreshSelected = () => refreshSelectedCalled = true;
Don't use private methods in the test

2018-12-17 12:06 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/tagBox.tests.js
> +        refreshSelectedCalled = false,
Use sinon.stub or sinon.spy for this purpose

2018-12-17 12:06 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/tagBox.tests.js
> +    var clock = sinon.useFakeTimers(),
Restore the clock after the test or use this.clock

2018-12-17 15:14 UTC, churkin commented on testing/tests/DevExpress.ui.widgets.editors/tagBox.tests.js
> +    tagBox._refreshSelected = () => refreshSelectedCalled = true;
Any suggestions?

2018-12-18 12:33 UTC, Yarovaya submitted a review, later dismissed

2018-12-19 13:05 UTC, mrjohn0011 approved these changes

2018-12-19 13:41 UTC, Yarovaya approved these changes

2018-12-19 13:49 UTC, merged