Select a newly created item in the list and clear the filter in the dxSelectBox after item added (T699477)
DevExpress/DevExtreme pull request #6471
Opened 2018-12-24 10:19 UTC by mrjohn0011

2018-12-24 10:34 UTC, lukyanovas commented on js/ui/select_box.js
> +        if(this._wasSearch()) {
Check TagBox behavior

2018-12-24 10:35 UTC, lukyanovas commented on js/ui/select_box.js
> +        if(this._wasSearch()) {
_shouldClearFilter ?

2018-12-25 05:45 UTC, churkin requested changes

2018-12-25 05:45 UTC, churkin commented on testing/tests/DevExpress.ui.widgets.editors/selectBox.tests.js
> +QUnit.test("Custom value should be selected in the list", function(assert) {
Rewrite to ES6 please

2018-12-25 09:12 UTC, churkin submitted a review, later dismissed

2018-12-25 13:11 UTC, lukyanovas requested changes
If you want to use ES6 in tests, rewrite all test file(or `import` at least)

2018-12-28 08:01 UTC, churkin approved these changes

2018-12-28 08:04 UTC, lukyanovas approved these changes

2018-12-28 08:20 UTC, merged