Search closest enabled date on init of the dxCalendar (T701103)
DevExpress/DevExtreme pull request #6506
Opened 2018-12-27 09:34 UTC by mrjohn0011

2018-12-27 10:20 UTC, DokaRus commented on js/ui/calendar/ui.calendar.js
> +        if(zoomLevel === "decade") {
How do you think about replacing `zoomLevel` values with constants?

2018-12-27 10:26 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets.editors/calendar.tests.js
> +import inflector from "core/utils/inflector";
```suggestion
 import { camelize } from "core/utils/inflector";
```

2018-12-27 10:27 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets.editors/calendar.tests.js
> +const camelize = inflector.camelize;
```suggestion

```

2018-12-27 11:34 UTC, DokaRus submitted a review, later dismissed

2018-12-28 07:58 UTC, churkin requested changes

2018-12-28 07:58 UTC, churkin commented on js/ui/calendar/ui.calendar.js
> +    ZOOM_LEVEL_MONTH = "month",
```javascript
const zoolLevel = {
   MONTH: "month",
   YEAR: "year",
   ...
}
```

2018-12-28 07:58 UTC, churkin commented on js/ui/calendar/ui.calendar.js
> +        if(Math.abs(offset) <= 1) {
extract `Math.abs(offset)` to a var

2018-12-28 07:58 UTC, churkin commented on js/ui/calendar/ui.calendar.js
> +            dateBackward = new Date(currentDate),
`dateForward === dateBackward` ?

2018-12-28 14:07 UTC, mrjohn0011 commented
Close because of incorrect rebase. This PR will be recreated

2018-12-28 14:07 UTC, closed without merging