Parse dates formatted with escaped pattern chars
DevExpress/DevExtreme pull request #6595
Opened 2019-01-16 14:30 UTC by mrjohn0011

This PR fixes an issue with devextreme-intl.
When the user uses format `'dd' yyyy` and text `dd 2016`, the parser returned an invalid date.
After this changes, the dates with special LDML chars in the format will be parsed correctly

2019-01-16 14:32 UTC, nightskylark commented
LGTM

2019-01-16 15:05 UTC, churkin requested changes

2019-01-16 15:05 UTC, churkin commented on js/ui/date_box/ui.date_box.mask.parts.js
> +        let pattern = regExpInfo.patterns[i - 1].replace(/^'|'$/g, ""),
Why do you use global search?

2019-01-16 15:05 UTC, churkin commented on js/localization/ldml/date.parser.js
> +        if(pattern[0] === "'") {
```javascript
if(pattern[0] === "'") {
    return ""
} if (pattern[0] === "H") {
    return "h";
} else {
    return pattern[0];
}
```

2019-01-16 15:07 UTC, churkin approved these changes

2019-01-17 13:04 UTC, vconst approved these changes

2019-01-17 13:05 UTC, merged