Add possibility to customize inner overlay options for editors
DevExpress/DevExtreme pull request #6673
Opened 2019-01-25 10:09 UTC by mrjohn0011

This feature was requested from the dashboards team. There are no possibilities to set custom container option for overlays that are built-in in more complex widgets

2019-01-25 10:29 UTC, churkin commented
@TikhonovaTatyana Please check property names

2019-01-25 11:01 UTC, churkin requested changes

2019-01-25 11:01 UTC, churkin commented on js/ui/editor/editor.js
> +    _bindInnerWidgetOptions: function(innerWidget, optionsContainer) {
`_bindInternalWidgetOptions: function(widget, options) {`

2019-01-25 11:33 UTC, TikhonovaTatyana reviewed
@churkin I don't see any public options to be checked.

2019-01-25 11:55 UTC, churkin commented
@TikhonovaTatyana `popupOptions` and `validationOverlayOptions ` will be added to our internal API.
I think we should use `popup` or `overlay` in both cases. What do you think?

2019-01-25 12:51 UTC, TikhonovaTatyana submitted a review, later dismissed
Considering that we already have `dropDownOptions` in our public API, I think that current names are OK.
//cc @churkin

2019-01-25 14:32 UTC, churkin submitted a review, later dismissed

2019-01-25 14:35 UTC, DokaRus submitted a review, later dismissed

2019-01-28 09:00 UTC, DokaRus commented
It should be useful for @dimarudnev

2019-01-29 13:38 UTC, DokaRus approved these changes

2019-01-30 07:18 UTC, churkin approved these changes

2019-02-01 06:07 UTC, merged