Implement multi tag functionality in the dxTagBox
DevExpress/DevExtreme pull request #677
Opened 2017-07-10 09:28 UTC by mrjohn0011

2017-07-10 11:08 UTC, vconst requested changes

2017-07-10 11:08 UTC, vconst commented on js/localization/messages/en.json
> +        "dxTagBox-selected": "selected",
Why is not "{0} selected"? In the other languages, count parameter may be placed at the end, for example.

2017-07-10 11:08 UTC, vconst commented on js/localization/messages/en.json
> +        "dxTagBox-all-selected": "All selected",
Why is not "All selected ({0})"?

2017-07-10 11:08 UTC, vconst commented on js/localization/messages/ja.json
> +        "dxTagBox-selected": "",
if(otherLocalValue === "!TODO!") {
                assert.ok(true, name + " is marked for translation");
            } else {
                assert.ok(true, name + " is translated");
            }

2017-07-10 11:08 UTC, vconst commented on js/ui/tag_box.js
> +             * @type_function_param1_field6 allSelected:boolean
Where is cancel parameter?

2017-07-10 11:08 UTC, vconst commented on js/ui/tag_box.js
> +             * @type_function_param1_field6 allSelected:boolean
Where is text parameter?

2017-07-11 07:41 UTC, lukyanovas requested changes

2017-07-11 07:41 UTC, lukyanovas commented on js/ui/tag_box.js
> +        if(onMultiTagPreparing) {
use afterExecute(dxAction) functionality instead

2017-07-11 10:33 UTC, lukyanovas submitted a review, later dismissed

2017-07-12 13:32 UTC, vconst approved these changes

2017-07-12 13:39 UTC, vconst requested changes

2017-07-12 13:39 UTC, vconst commented on js/localization/messages/ja.json
> +        "dxTagBox-all-selected": "!TODO!",
dxTagBox-all-selected -> dxTagBox-allSelected

2017-07-12 13:39 UTC, vconst commented on js/localization/messages/ja.json
> +        "dxTagBox-more-selected": "!TODO!",
dxTagBox-more-selected -> dxTagBox-moreSelected

2017-07-12 13:53 UTC, RomanTsukanov submitted a review, later dismissed

2017-07-13 07:25 UTC, vconst submitted a review, later dismissed

2017-07-13 08:20 UTC, lukyanovas submitted a review, later dismissed

2017-07-13 11:49 UTC, vconst approved these changes

2017-07-13 12:21 UTC, merged