Increase month when day out of limit in the dxDateBox with masks (T710987)
DevExpress/DevExtreme pull request #6802
Opened 2019-02-05 15:29 UTC by mrjohn0011

2019-02-05 18:15 UTC, KsyushaM submitted a review, later dismissed

2019-02-06 11:00 UTC, churkin requested changes

2019-02-06 11:00 UTC, churkin commented on testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +            assert.equal(date.getDate(), 3, "setter sets day");
strictEqual

2019-02-06 11:00 UTC, churkin commented on js/ui/date_box/ui.date_box.mask.parts.js
> +    let dayLimits = getLimits("dM", date),
```javascript
const { min, max } = getLimits("dM", date);
const newDay = fitIntoRange(day, min, max);
```

2019-02-07 08:30 UTC, churkin requested changes

2019-02-07 08:30 UTC, churkin commented on testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +            assert.equal(date.getFullYear(), 2015, "setter sets year");
strictEqual

2019-02-07 08:30 UTC, churkin commented on testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +            assert.equal(this.$input.val(), "Mar, 31", "current month overflow should increase month");
strictEqual

2019-02-07 08:30 UTC, churkin commented on testing/tests/DevExpress.ui.widgets.editors/datebox.mask.tests.js
> +            assert.equal(this.$input.val(), "Mar, 05", "out-of-limit values should clear search value");
strictEqual

2019-02-07 10:47 UTC, churkin approved these changes

2019-02-07 11:09 UTC, merged