Numberbox should ignore backspace/delete key down when the caret in the start/end of input (T713045)
DevExpress/DevExtreme pull request #6807
Opened 2019-02-06 11:49 UTC by churkin

2019-02-06 12:29 UTC, DokaRus submitted a review, later dismissed

2019-02-06 12:48 UTC, mrjohn0011 requested changes
Replace and simplify the test

2019-02-06 12:48 UTC, mrjohn0011 commented on testing/tests/DevExpress.ui.widgets.editors/numberBoxParts/common.tests.js
> +QUnit.test("Should ignore backspace/delete key down when the caret in the start/end of input (T713045)", (assert) => {
This test should be placed to the `mask.tests.ks` file. In that file the test can be simplified

2019-02-07 11:00 UTC, mrjohn0011 approved these changes

2019-02-07 11:39 UTC, DokaRus approved these changes

2019-02-07 11:39 UTC, merged