Rename datebox's 'Done' button to 'OK' in UK, DE (T605588)
DevExpress/DevExtreme pull request #6926
Opened 2019-02-14 10:38 UTC by churkin

2019-02-14 10:50 UTC, RomanTsukanov submitted a review, later dismissed

2019-02-14 10:54 UTC, jsdmitry submitted a review, later dismissed

2019-02-14 12:21 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets/popup.tests.js
> +    assert.equal($popupBottom.text(), "OKCancel", "buttons order is correct");
We have internal shortcuts for toolbar button - `['done', 'clear', 'cancel']`.

What do you think about rename the 'done' shortcut to 'ok'?
You add a "done" button and check that its text is "OK". It's confusing a little.

2019-02-15 12:02 UTC, DokaRus submitted a review, later dismissed

2019-02-15 13:23 UTC, DokaRus submitted a review, later dismissed

2019-02-15 13:26 UTC, jsdmitry submitted a review, later dismissed

2019-02-15 15:22 UTC, San4es requested changes
Let's save 'Done' localization strings.

2019-02-15 15:43 UTC, nightskylark approved these changes

2019-02-15 16:17 UTC, San4es approved these changes
LGTM

2019-02-18 07:41 UTC, DokaRus approved these changes

2019-02-18 08:00 UTC, merged