Wait for dblClick before caret moving to support numberbox selection on double click for ie11(T698588)
DevExpress/DevExtreme pull request #6931
Opened 2019-02-14 11:51 UTC by alexander-kotov-dx

2019-02-20 12:10 UTC, churkin requested changes

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +var caretTimeoutDuration = browser.msie ? 300 : 0;
upper case

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +            this._caretTimeout = null;
remove

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +        if(this._caretTimeout) {
`this._caretTimeout && clearTimeout(this._caretTimeout);`

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +            that._caretTimeout = undefined;
`null`

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +            that._moveCaretToBoundary(MOVE_BACKWARD, e);
remove `e`

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +
```javascript
var shouldReloadCaretTimer = !!this._caretTimeout;
```

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +var caretTimeoutDuration = browser.msie ? 300 : 0;
```javascript
var doesBrowserClearSelectionIfCaretMovedAfterClick = browser.msie;
var caretTimeoutDuration = doesBrowserClearSelectionIfCaretMovedAfterClick  ? 300 : 0;
```

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
> +            if(this._caretTimeout) {
```javascript
this._clearCaretTimeout() {
   this._caretTimeout &&  clearTimeout(this._caretTimeout);
   this._caretTimeout = null;
}
```

2019-02-20 12:10 UTC, churkin commented on js/ui/number_box/number_box.mask.js
>                  if(browser.msie) {
extra condition

2019-02-26 08:03 UTC, DokaRus commented on js/ui/number_box/number_box.mask.js
> +        }, CARET_TIMEOUT_DURATION);
```suggestion
        function() {
          this._caretTimeout = null;
          this._moveCaretToBoundaryEventHandler(MOVE_BACKWARD, e);
        }.bind(this)
```

2019-02-26 08:03 UTC, DokaRus commented on js/ui/number_box/number_box.mask.js
> +                }, CARET_TIMEOUT_DURATION);
function() {).bind(this)
```suggestion
                function() {
                  this._caret(maskCaret.getCaretInBoundaries(this._caret(), this._getInputVal(), this._getFormatPattern()));
                ).bind(this)
```

2019-02-26 08:03 UTC, DokaRus commented on js/ui/number_box/number_box.mask.js
> +        this._caretTimeout = setTimeout(function() {
Note about tests: you should update clock after using KeyboardMock methods like `type`, `press` etc.

2019-02-28 12:57 UTC, churkin approved these changes

2019-03-01 13:44 UTC, DokaRus approved these changes

2019-03-04 08:52 UTC, merged