Fix Gauges doc for loadingIndicator (second attempt)
DevExpress/DevExtreme pull request #6968
Opened 2019-02-15 15:59 UTC by RomanTsukanov

2019-02-15 16:41 UTC, IlyaKhD requested changes

2019-02-15 16:41 UTC, IlyaKhD commented on js/viz/docs/docgauges.js
> +        * @type boolean
`@type` is unnecessary in this case

2019-02-18 13:29 UTC, RomanTsukanov commented on js/viz/docs/docgauges.js
> +        * @type boolean
Fixed

2019-02-19 08:08 UTC, IlyaKhD approved these changes

2019-02-19 08:53 UTC, merged