Set DateBox value before use Validator (T716192)
DevExpress/DevExtreme pull request #6982
Opened 2019-02-18 12:37 UTC by alexander-kotov-dx

2019-02-18 15:12 UTC, DokaRus commented on js/ui/date_box/ui.date_box.base.js
> +    _validateValueWithoutValidator(value) {
Can we rename it?

2019-02-19 08:55 UTC, DokaRus requested changes

2019-02-19 08:55 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets.editors/datebox.tests.js
> +    const keyboard = keyboardMock($dateBox.find("input"));
```suggestion
    const keyboard = keyboardMock($dateBox.find(`.${TEXTEDITOR_INPUT_CLASS }`));
```
Editor could have more than one input element

2019-02-19 09:34 UTC, mrjohn0011 submitted a review, later dismissed

2019-02-19 09:52 UTC, DokaRus submitted a review, later dismissed

2019-02-20 09:05 UTC, DokaRus approved these changes

2019-02-20 09:27 UTC, merged