Docs: Move common legend options to BaseLegendOptions object
DevExpress/DevExtreme pull request #7009
Opened 2019-02-21 10:52 UTC by roman-simionov

2019-02-21 11:14 UTC, RomanTsukanov submitted a review, later dismissed

2019-02-21 14:36 UTC, San4es commented
Let's check it on our meta-data tools **before merging it**.

2019-02-21 16:24 UTC, nikgalushko submitted a review, later dismissed

2019-02-21 17:16 UTC, IlyaKhD requested changes
Meta Data tools are failing to process these changes, will investigate it tomorrow

2019-02-27 17:19 UTC, IlyaKhD submitted a review, later dismissed

2019-02-28 09:13 UTC, San4es submitted a review, later dismissed
SMD is ok

2019-02-28 10:53 UTC, RomanTsukanov approved these changes

2019-02-28 11:04 UTC, merged