zh translation update
DevExpress/DevExtreme pull request #7369
Opened 2019-03-21 07:19 UTC by jocelyn220

2019-03-29 17:01 UTC, BingoRUS commented
@beginor as an initial contributor of the Chinese localization, could you please check these changes?

2019-03-29 22:39 UTC, beginor commented
OK， I am coming！

2019-03-29 23:07 UTC, beginor requested changes
I have add some comment, please do a double check.

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxCollectionWidget-noDataText": "没有可显示的数据",
for short, it should be "无数据"

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxFileUploader-invalidFileExtension": "档案类型错误",
"档案" should be "文件", "档案" is only used in traditional chinese 。

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxFileUploader-invalidMaxFileSize": "档案过大",
"档案" should be "文件", "档案" is only used in traditional chinese 。

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxFileUploader-invalidMinFileSize": "档案过小",
"档案" should be "文件", "档案" is only used in traditional chinese 。

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxDataGrid-groupContinuesMessage": "至下一页",
I think it is no need to change.

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxDataGrid-groupContinuedMessage": "回到上一页",
I think it is no need to change.

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxDataGrid-editingSaveRowChanges": "储存",
should be "保存" , "存储" is usually used in traditional chinese .

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxFilterBuilder-filterOperationIsBlank": "空白",
should be "空“

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxFilterBuilder-filterOperationIsNotBlank": "不为空白",
should be “不为空”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogColorCaption": "变更字体颜色",
should be “更改字体颜色”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogBackgroundCaption": "变更背景颜色",
should be "更改背景颜色"

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogLinkCaption": "添加连结",
should be “添加链接”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogLinkUrlField": "网址",
”链接地址“

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogLinkTextField": "文字",
“链接文字”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogLinkTargetField": "于新视窗中开启",
“在新窗口中打开”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogImageCaption": "添加影像",
“添加图片”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-dialogImageUrlField": "网址",
“图片地址”

2019-03-29 23:07 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxHtmlEditor-normalText": "一般文字"
”正文“

2019-04-01 17:41 UTC, BingoRUS commented on js/localization/messages/zh.json
> +    "dxCollectionWidget-noDataText": "没有可显示的数据",
so which variant is more preferable - "没有要显示的数据", "没有可显示的数据" or "无数据"?

2019-04-01 22:23 UTC, beginor commented on js/localization/messages/zh.json
> +    "dxCollectionWidget-noDataText": "没有可显示的数据",
The English version of `dxCollectionWidget-noDataText` is "No data to display", I think the best should be "没有要显示的数据" ， “无数据” is just for short

2019-04-02 10:08 UTC, BingoRUS commented on js/localization/messages/zh.json
> +    "dxCollectionWidget-noDataText": "没有可显示的数据",
okay, thank you!

2019-04-02 10:10 UTC, BingoRUS commented
@jocelyn220 I made some changes according to the initial contributor review and going to merge this PR tomorrow. Please let me know if you have any additions.

2019-04-02 12:54 UTC, BingoRUS approved these changes

2019-04-03 16:34 UTC, merged