Get rid of $.makeArray method
DevExpress/DevExtreme pull request #738
Opened 2017-07-13 14:05 UTC by dxvladislavvolkov

2017-07-19 08:08 UTC, ovchinnikov submitted a review, later dismissed

2017-07-20 08:27 UTC, vconst requested changes

2017-07-20 08:27 UTC, vconst commented on js/data/data_source/data_source.js
> +                        Array.prototype.push.call(dataArray, data);
Why is not
`dataArray.push(data);`
or
`dataArray = [data];`
?

2017-07-20 08:27 UTC, vconst commented on js/data/data_source/data_source.js
> +                    data = dataArray;
Why is not
`data = [data];`
?

2017-07-20 11:04 UTC, vconst approved these changes

2017-07-20 11:15 UTC, merged