Update adaptive detail row when new row is deleted in batch edit mode has been fixed (T533190)
DevExpress/DevExtreme pull request #749
Opened 2017-07-14 07:18 UTC by jsdmitry

… has been fixed

2017-07-17 08:15 UTC, Alyar666 commented on js/ui/data_grid/ui.data_grid.adaptivity.js
> +                _beforeUpdateItems: function(rowIndices, rowIndex, operation) {
rename _beforeUpdateItems -> _beforeEditRow

2017-07-17 08:19 UTC, Alyar666 commented on js/ui/data_grid/ui.data_grid.adaptivity.js
> +                    if(operation === "delete" && this.getEditMode() === DATAGRID_EDIT_MODE_BATCH) {
Create a new method - _beforeDeleteRow. Write this code there

2017-07-17 08:21 UTC, Alyar666 submitted a review, later dismissed
review

2017-07-19 08:58 UTC, vconst requested changes

2017-07-19 08:58 UTC, vconst commented on js/ui/data_grid/ui.data_grid.adaptivity.js
> +                        expandedRowIndex = gridCoreUtils.getIndexByKey(expandedKey, this._dataController.items());
I think that using getKeyByRowIndex and isAdaptiveDetailRowExpanded is better way then using private fields and utility method

2017-07-20 06:37 UTC, vconst approved these changes

2017-07-20 07:11 UTC, merged