Split accepted values enums for buttons option for different widget types
DevExpress/DevExtreme pull request #7923
Opened 2019-04-30 12:25 UTC by alexander-kotov-dx

2019-04-30 12:28 UTC, mrjohn0011 submitted a review, later dismissed

2019-04-30 12:32 UTC, KsyushaM submitted a review, later dismissed

2019-04-30 13:19 UTC, RomanTsukanov requested changes

2019-04-30 13:19 UTC, RomanTsukanov commented on js/ui/drop_down_editor/ui.drop_down_editor.js
> +            * @default undefined
```suggestion
            * @default undefined
            * @inheritdoc
```

2019-04-30 13:19 UTC, RomanTsukanov commented on js/ui/number_box/number_box.base.js
> +            * @default undefined
```suggestion
            * @default undefined
            * @inheritdoc
```

2019-05-06 16:03 UTC, IlyaKhD commented
LGTM

2019-05-07 07:51 UTC, RomanTsukanov approved these changes

2019-05-07 08:44 UTC, KsyushaM approved these changes

2019-05-07 08:53 UTC, merged