Add devextreme-internal-tools package to package.json
DevExpress/DevExtreme pull request #8003
Opened 2019-05-10 06:01 UTC by viterobk

2019-05-12 08:44 UTC, IlyaKhD submitted a review, later dismissed

2019-05-13 09:27 UTC, AlekseyMartynov commented on package.json
> +    "update-ts": "dx-tools declaration-validator & dx-tools ts-generator",
Single `&` is not cross-platform. It means background in POSIX.

2019-05-13 09:27 UTC, AlekseyMartynov requested changes
- Correct single `&`
- Resolve conflicts

2019-05-13 09:35 UTC, AlekseyMartynov commented
I think we need to describe the new commands in [README_DEVELOPERS](https://github.com/DevExpress/DevExtreme/blob/19_1/README_DEVELOPERS.md). 

Per @IlyaKhD 's 

> если забыл обновить ТС - Дрон упадет. Матюгнулся, обновил, подлил)

it's becoming a crucial part of the development process.

2019-05-13 09:38 UTC, IlyaKhD commented
> it's becoming a crucial part of the development process.

It's just the same thing as "I've forgotten to run unit tests locally and drone fails". Don't forget to run tests before creating a PR, don't forget to update TS when editing declarations - rules of the same kind.

2019-05-13 11:02 UTC, AlekseyMartynov commented
Unit tests are well-known among developers. Plus we have the 'Tests and CI' section in `README_DEVELOPERS`.

Automatic generation of TS declarations is our custom approach. It is important that a contributor has to commit a generated file. I think we should briefly describe it by adding a new block to the document.

2019-05-13 12:48 UTC, IlyaKhD commented
>I think we should briefly describe it by adding a new block to the document.

Agree

2019-05-15 13:21 UTC, AlekseyMartynov approved these changes

2019-05-15 13:39 UTC, BingoRUS approved these changes

2019-05-15 13:42 UTC, IlyaKhD approved these changes

2019-05-15 13:43 UTC, merged