dont lock numberbox with leading or trailing zeros (T734419)
DevExpress/DevExtreme pull request #8166
Opened 2019-05-27 07:01 UTC by gvrnmntdept

2019-05-27 07:56 UTC, DokaRus reviewed
Just a few remarks about the code style

2019-05-27 07:56 UTC, DokaRus commented on js/localization/number.js
> +        if(cleanedText === '.' || cleanedText === "") { return null; }
```suggestion
        if(cleanedText === '.' || cleanedText === "") {
            return null;
        }
```

2019-05-27 07:56 UTC, DokaRus commented on js/localization/number.js
> +        if(significantDigitsCount > 15) { return NaN; }
```suggestion
        if(significantDigitsCount > 15) {
            return NaN;
        }
```

2019-05-27 07:56 UTC, DokaRus commented on js/localization/number.js
> +            if(cleanedText.charAt(index) !== '0') {
```suggestion
            if(cleanedText.charAt(index) !== "0") {
```

2019-05-27 07:56 UTC, DokaRus commented on js/localization/number.js
> +            if(cleanedText.charAt(index) !== '0') {
```suggestion
            if(cleanedText.charAt(index) !== "0") {
```

2019-05-27 08:15 UTC, mrjohn0011 reviewed
It is OK for me, but i ask @vconst to review this changes. Please wait for his review

2019-05-27 08:23 UTC, DokaRus submitted a review, later dismissed

2019-05-28 07:17 UTC, vconst requested changes
New code contains duplicate and similar lines in two loops. Also, extract new logic into separate method/methods because the parse method becomes big.

2019-05-28 12:35 UTC, DokaRus submitted a review, later dismissed

2019-05-28 12:35 UTC, DokaRus commented on js/localization/number.js
> +        if(this._calcSignificantDigits(cleanedText) > 15) { return NaN; }
```suggestion
        if(this._calcSignificantDigits(cleanedText) > 15) {
            return NaN;
        }
```

2019-05-28 12:35 UTC, DokaRus commented on js/localization/number.js
> +        if(integer) { result += calcDigitsAfterLeadingZeros(integer.split("")); }
```suggestion
        if(integer) {
            result += calcDigitsAfterLeadingZeros(integer.split(""));
        }
```

2019-05-28 12:35 UTC, DokaRus commented on js/localization/number.js
> +        if(fractional) { result += calcDigitsAfterLeadingZeros(fractional.split("").reverse()); }
```suggestion
        if(fractional) {
            result += calcDigitsAfterLeadingZeros(fractional.split("").reverse());
        }
```

2019-05-29 09:05 UTC, DokaRus approved these changes

2019-05-29 11:14 UTC, vconst approved these changes
LGTM

2019-05-29 11:20 UTC, merged