Support popup auto resizing for dropDownBox with TreeView in Search mode (T724029)(WIP)
DevExpress/DevExtreme pull request #8340
Opened 2019-06-10 11:14 UTC by alexander-kotov-dx

2019-06-17 07:25 UTC, DokaRus requested changes

2019-06-17 07:25 UTC, DokaRus commented on js/ui/popup.js
> +                    currentHeightStrategyClass = heightStrategies.static;
You've already set this value to a variable at [R679](https://github.com/DevExpress/DevExtreme/pull/8340/files#diff-353a433c5241a480804acc2b08b8330fR679)

2019-06-17 07:25 UTC, DokaRus commented on js/ui/popup.js
> +                if(isIE11) {
Can you simplify it?

2019-06-17 07:25 UTC, DokaRus commented on js/ui/popup.js
> +        var currentHeightStrategyClass = heightStrategies.static;
Extract method

2019-06-17 07:25 UTC, DokaRus commented on js/ui/popup.js
> +var heightStrategies = { static: "", inherit: POPUP_CONTENT_INHERIT_HEIGHT_CLASS, flex: POPUP_CONTENT_FLEX_HEIGHT_CLASS };
Capitalize it like other constants

2019-06-17 07:25 UTC, DokaRus commented on js/ui/popup.js
> +        if(currentHeightStrategyClass === heightStrategies.static) {
Extract method `getCssStyles`?

2019-06-17 14:11 UTC, mrjohn0011 submitted a review, later dismissed

2019-06-17 14:34 UTC, DokaRus submitted a review, later dismissed

2019-06-18 10:05 UTC, DokaRus approved these changes

2019-06-18 10:07 UTC, mrjohn0011 approved these changes

2019-06-18 10:30 UTC, merged