Floating Action Button -  Add floatingActionButtonRepaint method
DevExpress/DevExtreme pull request #8438
Opened 2019-06-20 11:32 UTC by groshenkovamarina

2019-06-25 16:47 UTC, BingoRUS requested changes

2019-06-25 16:47 UTC, BingoRUS commented on js/ui/floating_action_button_repaint.js
> +import { repaint } from "./speed_dial_action/speed_dial_main_item";
I personally don't like the place where you put this file. Why not to move it to speed_dial_action folder and require it from there in widgets-base.js? Also, the file should be named `repaint_floating_action_button.js`.

2019-06-25 16:47 UTC, BingoRUS commented on js/ui/floating_action_button_repaint.js
> + * @name ui.floatingActionButtonRepaint
Function name should be `repaintFloatingActionButton`.

2019-06-25 16:47 UTC, BingoRUS commented on js/ui/floating_action_button_repaint.js
> +var floatingActionButtonRepaint = function() {
It's kinda redundant. Just export the `repaint` below.

2019-06-27 14:11 UTC, RomanTsukanov approved these changes

2019-06-27 18:54 UTC, BingoRUS approved these changes

2019-06-28 16:20 UTC, merged