Fix toolbar bugs related to header width recalculation (T752661, T752306, T752400)
DevExpress/DevExtreme pull request #8565
Opened 2019-06-28 10:22 UTC by viterobk

2019-07-01 07:31 UTC, babich-a requested changes

2019-07-01 07:31 UTC, babich-a commented on testing/tests/DevExpress.ui/themes.tests.js
> -    test("waitWebFont: function reject by timeout if the font is not loaded", (assert) => {
I suggest rewriting this test to make sure that promise will be resolved if the font is not loaded.

2019-07-01 07:31 UTC, babich-a commented on js/ui/toolbar/ui.toolbar.base.js
> +            this._waitParentAnimationFinished().then(function() {
We can use an arrow function. We do not need 'that' in this case. My suggestion is `Promise.all([this._waitParentAnimationFinished(),this._checkWebFontForLabelsLoaded()]).then(this._dimensionChanged.bind(this))`

2019-07-01 07:31 UTC, babich-a commented on js/ui/toolbar/ui.toolbar.base.js
> +                    if($(parent).data("dxAnimData")) {
If somebody rename 'dxAnimData' constant the trouble will happen. I suggest using https://js.devexpress.com/Documentation/ApiReference/Common/utils/fx/Methods/#isAnimatingelement method from 'fx' that do completely the same thing.

2019-07-01 07:31 UTC, babich-a commented on js/ui/toolbar/ui.toolbar.base.js
> +        return new Promise(function(resolve) {
Will modern syntax be better `... Promise(resolve => { ...` ?

2019-07-01 07:31 UTC, babich-a commented on js/ui/toolbar/ui.toolbar.base.js
> +        var $element = this.$element(),
const/let instead of var?

2019-07-01 08:36 UTC, babich-a approved these changes

2019-07-01 09:22 UTC, BingoRUS approved these changes

2019-07-01 09:23 UTC, merged

2019-07-23 08:17 UTC, hakimio commented
@viterobk 
Using the latest build (19.1.5-build-19191-0321) the issue doesn't seem to be fixed. 
Demo -> https://codesandbox.io/s/popup-editing-devextreme-data-grid-rzpy4
Click the edit button to open edit dialog.

2019-07-23 14:23 UTC, viterobk commented
Hello @hakimio 
Thank you for the feedback. We reproduced this issue and [fixed](https://github.com/DevExpress/DevExtreme/pull/8903) it.