dxSpeedDialAction - Fix component in onClick handler args
DevExpress/DevExtreme pull request #8668
Opened 2019-07-04 13:39 UTC by groshenkovamarina

2019-07-05 06:54 UTC, babich-a requested changes

2019-07-05 06:54 UTC, babich-a commented on js/ui/speed_dial_action/speed_dial_main_item.js
> +            component: this.option("actions").length === 1 ? this.option("actions")[0] : this
I suggest not to call this.option("actions") twice.

2019-07-05 06:54 UTC, babich-a commented on testing/tests/DevExpress.ui.widgets/floatingActionButton.tests.js
> +QUnit.module("check action buttons click args", (hooks) => {
Why do floatingActionButton.tests test dxSpeedDialAction widget?

2019-07-05 06:54 UTC, babich-a commented on js/ui/speed_dial_action/speed_dial_item.js
> +            this._clickAction(extend({ event: e, element: this.$element() }));
What 'extend' with one argument should do? All tests passed without it.

2019-07-05 10:24 UTC, groshenkovamarina commented on testing/tests/DevExpress.ui.widgets/floatingActionButton.tests.js
> +QUnit.module("check action buttons click args", (hooks) => {
Because dxSpeedDialAction widget - part of  FAB costruction

2019-07-05 11:08 UTC, babich-a commented on testing/tests/DevExpress.ui.widgets/floatingActionButton.tests.js
> +QUnit.module("check action buttons click args", (hooks) => {
What is 'FAB construstion' mean? We have module 'ui/speed_dial_action' and widget dxSpeedDialAction. It is impossible to find tests for 'speed_dial_action' by file name now. I think we have to have the same names here 'js/ui/speed_dial_action' and here 'testing/tests/DevExpress.ui.widgets/floatingActionButton'.

2019-07-08 13:30 UTC, groshenkovamarina commented on testing/tests/DevExpress.ui.widgets/floatingActionButton.tests.js
> +QUnit.module("check action buttons click args", (hooks) => {
Ок

2019-07-09 07:11 UTC, babich-a approved these changes

2019-07-12 11:21 UTC, merged