Add localization messages for Turkish (tr) locale.
DevExpress/DevExtreme pull request #8706
Opened 2019-07-06 12:29 UTC by galetis

I left default what I can't translate in English

2019-08-19 08:05 UTC, BingoRUS commented
Hello @galetis,
Will it help you to translate the remaining strings if I provide descriptions (in some cases with screenshots) of each of them?

2019-08-23 13:53 UTC, galetis commented
@BingoRUS I completed the remaining translates

2019-08-27 15:51 UTC, BingoRUS requested changes

2019-08-27 15:51 UTC, BingoRUS commented on js/localization/messages/tr.json
> +        "dxFilterBuilder-notAnd": "Değil",
Is it better to use this phrase here?
```suggestion
        "dxFilterBuilder-notAnd": "Değil Ve",
```

2019-08-27 15:51 UTC, BingoRUS commented on js/localization/messages/tr.json
> +        "dxScheduler-moreAppointments": "{0} data",
I think there is a typo:
```suggestion
        "dxScheduler-moreAppointments": "{0} daha",
```

2019-08-27 15:51 UTC, BingoRUS commented on js/localization/messages/tr.json
> +        "dxPivotGrid-sortRowBySummary": "Sort \"{0}\" by This Row",
The `dxPivotGrid-sortColumnBySummary` and `dxPivotGrid-sortRowBySummary` messages look untranslated. Can you add right messages here please?

2019-08-28 16:32 UTC, BingoRUS approved these changes
@galetis Thanks for your contribution. Turkish localization will be available with the next DevExtreme updates: 19.2.3, 19.1.6 and 18.2.11.

2019-08-28 16:32 UTC, merged