TreeView, List - If the JAWS screen reader is used, keyboard navigation doesn't work (T747286)
DevExpress/DevExtreme pull request #8811
Opened 2019-07-16 06:18 UTC by EugeniyKiyashko

The reader doesn't pronounce the item text when a search bar is enabled

2019-07-16 18:12 UTC, jsdmitry submitted a review, later dismissed

2019-07-24 11:57 UTC, DokaRus requested changes

2019-07-24 11:57 UTC, DokaRus commented on js/ui/widget/ui.search_box_mixin.js
> +            "role": undefined,
```suggestion
            "role": null,
```

2019-07-24 11:57 UTC, DokaRus commented on js/ui/widget/ui.search_box_mixin.js
> +            "activedescendant": undefined
```suggestion
            "activedescendant": null
```

2019-07-24 11:57 UTC, DokaRus commented on js/ui/widget/ui.search_box_mixin.js
> +        domUtils.toggleAttr($target, "tabIndex");
Pull 19.1 branch. I removed this method some time ago.
Use `$.attr()` instead of it

2019-07-25 09:57 UTC, DokaRus approved these changes
LGTM

2019-07-25 11:26 UTC, jsdmitry approved these changes

2019-07-25 17:07 UTC, merged