Make overlay wrapper full screen and transparent when shading is disabled (T758340)
DevExpress/DevExtreme pull request #8888
Opened 2019-07-22 14:58 UTC by mrjohn0011

2019-07-25 09:50 UTC, DokaRus requested changes
Should we update or remove `_renderShadingDimensions` from [Popover](https://github.com/mrjohn0011/DevExtreme/blob/overlay_shading/js/ui/popover.js#L539)?

2019-07-25 09:50 UTC, DokaRus commented on js/ui/overlay/ui.overlay.js
> +            var isEvent = !!(position.of && position.of.type === "positionEvent");
> position.of.type === "positionEvent"

There's no such thing. You can adopt logic from [animation/position](https://github.com/DevExpress/DevExtreme/blob/19_2/js/animation/position.js#L328)

2019-07-25 09:50 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets/overlay.tests.js
> +    test("wrapper should have 100% width and height when shading is disabled", (assert) => {
Add the `shading` option change test at runtime. And check the `pointer-events` value

2019-07-25 14:17 UTC, DokaRus commented on styles/widgets/common/list.less
> -    table-layout: fixed;
it's gonna cause a problem with the badge

2019-08-09 07:44 UTC, DokaRus approved these changes

2019-08-09 13:30 UTC, merged

2019-08-09 13:44 UTC, jsdmitry approved these changes