Add doccomments for cellInfo in grid cell templates
DevExpress/DevExtreme pull request #9024
Opened 2019-07-30 11:33 UTC by KiriosK

2019-07-31 11:47 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +            * @type_function_param2_field10 rowType:string
Add doc comment for row field:  "row:dxTreeListRow"

2019-07-31 11:58 UTC, vconst requested changes

2019-07-31 11:58 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +             * @type_function_param2_field10 rowType:string
Add doc comment for row field:  "row:dxDataGridRow"
Add doc comment for watch field

2019-07-31 11:58 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +             * @type_function_param2_field10 rowType:string
Add doc comment for row field:  "row:dxTreeListRow"
Add doc comment for watch field

2019-07-31 11:58 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +             * @type_function_param2_field11 watch:function
Add doc comment for row field: "row:dxDataGridRow"

2019-07-31 11:58 UTC, vconst commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +             * @type_function_param2_field8 summaryItems:Array<any>
Add doc comment for row field: "row:dxDataGridRow"

2019-08-07 11:01 UTC, viterobk commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +             * @type_function_param2_field1 setValue(newValue, newText):any
`@type_function_param2_field1 setValue:function`

2019-08-07 11:02 UTC, viterobk commented on js/ui/grid_core/ui.grid_core.columns_controller.js
> +             * @type_function_param2_field1 setValue(newValue, newText):any
`@type_function_param2_field1 setValue:function`
The function signature can be shown in the field's description.

2019-08-07 18:25 UTC, viterobk approved these changes

2019-08-08 08:16 UTC, RomanTsukanov approved these changes

2019-08-08 08:38 UTC, vconst approved these changes

2019-08-08 08:40 UTC, merged