DataGrid: Fix edit command cell had dx-hidden-cell class if it's unfixed (T803784)
DevExpress/DevExtreme pull request #9116
Opened 2019-08-06 12:54 UTC by jtoming830

2019-08-06 13:13 UTC, vconst requested changes

2019-08-06 13:13 UTC, vconst commented on js/ui/grid_core/ui.grid_core.column_fixing.js
> +            isEmptyCell = column.fixed || (column.command && !isUnfixedButtonColumn);
This is wrong expression. The correct version:

isEmptyCell = column.fixed || (column.command && column.fixed !== false);

2019-08-07 11:59 UTC, vconst approved these changes

2019-08-07 13:37 UTC, Alyar666 approved these changes

2019-08-07 13:38 UTC, merged