File Manager - Add option for customizing root folder name
DevExpress/DevExtreme pull request #9204
Opened 2019-08-09 14:46 UTC by Staziz

2019-08-12 15:58 UTC, maxerokh approved these changes

2019-08-13 07:02 UTC, maxerokh requested changes

2019-08-13 07:02 UTC, maxerokh commented on js/ui/file_manager/file_items_controller.js
> +        if(text === "") {
Why are you using the condition? I think, you may assign value of `text` to the variable without conditions.

2019-08-13 07:02 UTC, maxerokh commented on js/ui/file_manager/ui.file_manager.js
> +            rootFolderText: messageLocalization.format("dxFileManager-defaultRootFolder"),
@RomanTsukanov What do you think about the naming?

2019-08-13 07:02 UTC, maxerokh commented on testing/tests/DevExpress.ui.widgets/fileManagerParts/navigation.tests.js
> +        var target = treeViewNode[0].children[0];
Use `let` or `const` structures instead of `var`.

2019-08-13 07:02 UTC, maxerokh commented on testing/tests/DevExpress.ui.widgets/fileManagerParts/navigation.tests.js
> +        var treeViewNode = $(document).find(".dx-treeview-node");
Use the FileManager test wrapper to get treeView's node

2019-08-13 07:02 UTC, maxerokh commented on testing/tests/DevExpress.ui.widgets/fileManagerParts/navigation.tests.js
> +        assert.ok(target.innerText.indexOf("Files") === 0, "Default is correct");
To check equivalence of strings use the `assert.equal` method

2019-08-13 07:11 UTC, Staziz commented on js/ui/file_manager/file_items_controller.js
> +        if(text === "") {
What if the text would be undefined?

2019-08-13 07:39 UTC, maxerokh commented on js/ui/file_manager/file_items_controller.js
> +        if(text === "") {
In this case, you can write
`root.name = text || ""`

2019-08-13 09:37 UTC, Staziz commented
Moved text getting function to wrapper, changed _createRootDirectory() appearance a bit, without changing logic

2019-08-13 10:10 UTC, Staziz commented
getFolderNodeText function now return some string in any case

2019-08-13 12:15 UTC, Staziz commented
Now options and constants are named in a proper way

2019-08-13 13:22 UTC, maxerokh approved these changes

2019-08-13 13:25 UTC, merged