Implement resetOption method
DevExpress/DevExtreme pull request #9297
Opened 2019-08-15 15:34 UTC by dxvladislavvolkov

2019-08-16 08:00 UTC, nightskylark requested changes

2019-08-16 08:00 UTC, nightskylark commented on testing/tests/DevExpress.core/component.tests.js
> +    });
Does the `resetOption` method support resetting the second-level options like `instance.resetOption('opt5.subopt1')`?

2019-08-16 08:00 UTC, nightskylark commented on js/core/utils/option.js
> +import coreDataUtils from "./data";
We should not move any extracted modules to the `utils` folder, The `utils` means that this methods do not consider any context. It should be only simple methods with straight in-out logic and withot any coherence. I think, it's better to rename this module and place it to the `core` folder.

2019-08-16 08:00 UTC, nightskylark commented on js/core/utils/option.js
> +    if(this._optionValuesEqual(name, previousValue, value)) {
Should this method be always called with the widget instance as a context? If so, It definitely needs to be refactored.

2019-08-16 08:00 UTC, nightskylark commented on js/core/dom_component.js
> +        var width = this._computeOptionValue("width", element);
Why? I did not find any conflicts.

2019-08-16 08:00 UTC, nightskylark commented on js/core/utils/option.js
> +import coreDataUtils from "./data";
It's great that you extract the code but it looks like the work is not finished yet. Let's discuss it personally.

2019-09-02 07:49 UTC, nightskylark commented on js/core/option_manager.js
> +        this._deprecatedOptionsSuppressed;
```suggestion
        this._deprecatedOptionsSuppressed = false;
```

2019-09-02 07:57 UTC, nightskylark commented on js/core/component.js
> +        ++this._logDeprecatedWarningCount;
This code was written for testing only and needs to be removed.

2019-09-05 07:45 UTC, nightskylark commented on js/core/component.js
> +
Redundant line

2019-09-05 08:01 UTC, nightskylark commented on js/core/component.js
> +        this._optionManager = {};
What is it for?

2019-09-20 14:56 UTC, nightskylark requested changes

2019-09-20 14:56 UTC, nightskylark commented on js/core/option_manager.js
> +    onLogWarning(callBack) {
It looks like this method and internal callbacks should be renamed. This module know nothing about logging warnings. It just noticed about the deprecated option was processed.

2019-09-20 14:56 UTC, nightskylark commented on js/core/option_manager.js
> +    _valuesEqual(name, oldValue, newValue) {
It looks like first argument `name` is not used

2019-09-20 14:56 UTC, nightskylark commented on js/integration/angular/component_registrator.js
> +                if(this._component._optionManager._valuesEqual(optionPath, oldValue, newValue) && this._ngLocker.locked(optionPath)) {
So much underscores. Maybe this method should be extracted as an utility?

2019-09-20 14:56 UTC, nightskylark commented on js/core/component.js
> +    _setOptionWithoutNotify: function(name, value) {
I suppose this renaming and adding another method wtih the old name could confuse our collegues. Maybe it's better to find another names for the new methods or use the `silent` flag as argument?

2019-09-24 13:19 UTC, ovchinnikov commented on testing/tests/DevExpress.core/component.tests.js
> +    });
I suggest to check "items[1].subOption" case as well

2019-09-27 12:46 UTC, nightskylark requested changes

2019-09-27 12:46 UTC, nightskylark commented on js/core/component.js
> +            this._initialOptions = {};
Needs to be removed. Empty object will be overwritten in next line.

2019-09-27 12:46 UTC, nightskylark commented on js/core/component.js
> +            const rulesOptions = this._getOptionByRules(this._getOptionSilent("defaultOptionsRules"));
Why do you use `this._getOptionSilent` and `_optionManager._setSilent` at the same time. It looks like component's methods should be used everywhere

2019-09-27 12:46 UTC, nightskylark commented on js/core/component.js
> +    _getOptionSilent: function(name) {
Maybe it should be `_getOptionByStealth`? I think, pairy methods should be named the same way.

2019-09-27 12:46 UTC, nightskylark commented on js/core/option_manager.js
> +    _logWarningIfDeprecated(option) {
Why you renamed the callback but left the `log...` name for the method? I suggest something like `notifyDeprecated`.

2019-09-27 12:46 UTC, nightskylark commented on js/core/utils/compare.js
> +const valuesEqual = function(oldValue, newValue) {
I suggest to move this method to `data` utility file. The `compare` filename looks too mysterious without a context.

2019-09-27 12:46 UTC, nightskylark commented on js/core/utils/compare.js
> +        return (1 / oldValue) === (1 / newValue);
Maybe we need to extract some variable or method to explain negative zero situation. I think this code could rise a questions for anyone who will see it.

2019-09-27 12:46 UTC, nightskylark commented on js/core/component.js
> +        }
Why don't we call `_setOptionsByDevice` here?

2019-09-27 12:46 UTC, nightskylark commented on js/core/component.js
> +    resetOption: function(name) {
The doctags for `resetOption` method should be added here.

2019-10-01 10:59 UTC, IlyaKhD requested changes

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +import CallBacks from "./utils/callbacks";
```suggestion
import createCallBack from "./utils/callbacks";
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +    setValue(options, value) {
Consider reordering:
`getValue`
`setValue`
`getSilent`
`setSilent`

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +    setSilent(options, value) {
```suggestion
    setValueSilently(options, value) {
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +    getSilent(name) {
```suggestion
    getValueSilently(name) {
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +        return this._getValue(this._options, normalizedName);
No need to extract a variable
```suggestion
        return this._getValue(this._options, this._normalizeName(name));
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +        let name = options;
I propose avoiding argument reassigning if possible.

```
_convertToObj(option, value) {
    if(typeof option !== "string")
        return option;

    const result = {};
    result[name] = value;
    return result;
}
````

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +        options = this._ensureObject(options, value);
As I got it - the `options` argument can be either a `string` or a an `object`. Is this really required? Can't we use a stricter signature  (e.g. accepting `object`-s only)

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/utils/compare.js
> +exports.valuesEqual = valuesEqual;
```suggestion
exports.equals= equals;
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +            delete fieldObject[fieldName];
No need to have a variable
```suggestion
            delete fieldObject[this._getFieldName(name)];
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +        const splitNames = fullName.split('.');
```suggestion
        return fullName.substr(0, fullName.lastIndexOf('.'));
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +        if(name) {
```suggestion
        if(!name) return;
```

2019-10-01 10:59 UTC, IlyaKhD commented on js/core/option_manager.js
> +        if(name) {
```suggestion
        if(!name) return name;
```

2019-10-04 12:18 UTC, nightskylark submitted a review, later dismissed

2019-10-08 09:58 UTC, IlyaKhD requested changes

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/component.js
> +        for(let path of fullPath) {
```suggestion
        for(const path of optionName.split(".")) {
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/component.js
> +        this._optionManager.setValueSilently(options);
No need to reassign the attribute:
```suggestion
        this._optionManager.setValueSilently(this._convertToObj(options, value));
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/component.js
> +    _convertToObj(options, value) {
Better make this a static function outside the class (no need to use `this` context)

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/component.js
> +        this._optionManager.setValue(option);
No need to use a variable

```suggestion
        this._optionManager.setValue(this._convertToObj(name, defaultValue));
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/component.js
> +    _convertToObj(options, value) {
What about renaming it to smth like `normalizeOptions` or `normalizeOptionsObj` ?

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/option_manager.js
> +        const splitNames = fullName.split('.');
```suggestion
         return fullName.substr(fullName.lastIndexOf('.') + 1);
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/option_manager.js
> +        const alias = this._normalizeName(name);
As for me `alias` has a different meaning from `normalize`. I propose to use only one word i.e. rename variable to `normalizedName` or function to `getAlias`

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/option_manager.js
> +        if(deprecate) {
No need to have a variable

```diff
-	        const alias = deprecate.alias;

-            if(alias ) {
+            if(deprecate.alias) {
-                name = alias;
+                name = deprecate.alias;
            }
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/utils/data.js
> +const isArraysEqualByValue = function(array1, array2, deep) {
```suggestion
const arraysEqualByValue = function(array1, array2, depth) {
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/utils/data.js
> +const isObjectsEqualByValue = function(object1, object2, deep) {
```suggestion
const objectsEqualByValue = function(object1, object2, depth) {
```

2019-10-08 09:58 UTC, IlyaKhD commented on js/core/utils/data.js
> +const maxEqualityDeep = 3;
```suggestion
const maxEqualityDepth = 3;
```

2019-10-08 11:42 UTC, IlyaKhD submitted a review, later dismissed

2019-10-09 07:52 UTC, ovchinnikov submitted a review, later dismissed

2019-10-09 13:53 UTC, nightskylark approved these changes

2019-10-09 14:28 UTC, merged