DataGrid: Add promise support for setCellValue
DevExpress/DevExtreme pull request #9340
Opened 2019-08-19 15:26 UTC by KiriosK

2019-08-20 11:37 UTC, AntonSermyazhko submitted a review, later dismissed

2019-08-21 08:05 UTC, vconst requested changes

2019-08-21 08:05 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.tests.js
> +QUnit.module('Promises in editing and event handlers', {
Use double quotes instead of single quotes in new code

2019-08-21 08:05 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.tests.js
> +                asyncLoadEnabled: false,
This option is not necessary

2019-08-21 08:05 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/editing.tests.js
> +    var editCell = function(rowIndex, columnIndex, text) {
This method duplicated in different tests. Move it to beforeEach

2019-08-21 08:05 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    that._dataController.dataErrorOccurred.fire(arg, $popupContent);
This two lines are used in two places. So, move they to separate method.

2019-08-21 08:05 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    var error = arg instanceof Error ? arg : new Error(arg && String(arg) || "Unknown error");
This line is duplicated. Try to refactor it. The createFailureHandler function from _saveEditDataCore method can be reused.

2019-08-21 14:33 UTC, closed without merging