Improve the Draggable component
DevExpress/DevExtreme pull request #9507
Opened 2019-08-28 18:54 UTC by Alyar666

2019-08-29 15:27 UTC, vconst requested changes

2019-08-29 15:27 UTC, vconst commented on js/ui/draggable.js
> +    _isValidateElement: function(event, $element) {
_isValidateElement => _isValidElement | _validateElement

2019-08-29 15:27 UTC, vconst commented on js/ui/draggable.js
> +            isHandleElement = handle && $(event.originalEvent.target).is(handle);
is -> closest?

2019-08-29 15:27 UTC, vconst commented on styles/widgets/common/draggable.less
> +.dx-draggable-dragging {
Check this class

2019-08-29 15:27 UTC, vconst commented on testing/tests/DevExpress.ui.widgets/draggable.tests.js
> +    assert.strictEqual($("body").children("#myDragElement").length, 1, "there is a cloned element");
check that dx-draggable-clone class is added

2019-08-29 15:27 UTC, vconst commented on testing/tests/DevExpress.ui.widgets/draggable.tests.js
> +    this.checkPosition(0, 50, assert);
add description

2019-08-29 15:27 UTC, vconst commented on testing/tests/DevExpress.ui.widgets/draggable.tests.js
> +    this.checkPosition(10, 60, assert);
add description

2019-09-02 07:18 UTC, vconst approved these changes

2019-09-02 08:51 UTC, jtoming830 approved these changes

2019-09-02 09:03 UTC, merged