DataGrid: Add promise support to onInitNewRow
DevExpress/DevExtreme pull request #9548
Opened 2019-09-03 08:27 UTC by jtoming830

2019-09-03 11:00 UTC, vconst requested changes
Also, the addRow method is still long. Can we split it to several parts?

2019-09-03 11:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    .fail((arg) => this._fireDataErrorOccurred(arg));
Add createFailureHandler here

2019-09-03 11:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    return;
Duplicated code with return, Move it to separate method.

2019-09-03 11:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                that._setInsertKey(insertKey, insertIndex);
You can initialize pageIndex and rowIndex in this method also, Also, I think that name _fillInsertKey will be better because this method add different fields to insertKey object

2019-09-03 11:00 UTC, vconst commented on js/ui/grid_core/ui.grid_core.editing.js
> +                    insertKey.parentKey = parentKey;
Why does this code need? The parentKey is already assigned to insertKey before _initNewRow.

2019-09-05 06:32 UTC, vconst submitted a review, later dismissed

2019-09-05 08:09 UTC, AntonSermyazhko submitted a review, later dismissed

2019-09-05 08:09 UTC, AntonSermyazhko commented on js/ui/grid_core/ui.grid_core.editing.js
> +                rowIndex: (parentRowIndex >= 0 ? parentRowIndex + 1 : (rowsView ? rowsView.getTopVisibleItemIndex(true) : 0))
rowIndex asignment is too complex. Too many operations for ternary operators.

2019-09-05 08:31 UTC, AntonSermyazhko approved these changes

2019-09-05 08:34 UTC, vconst approved these changes

2019-09-05 08:46 UTC, merged