PivotGrid: Fix virtual scrolling did not work if there is no data (T810822)
DevExpress/DevExtreme pull request #9563
Opened 2019-09-03 15:26 UTC by jtoming830

2019-09-04 06:54 UTC, vconst requested changes

2019-09-04 06:54 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.pivotGrid/pivotGrid.tests.js
> +    var done = assert.async();
Async test is not good test. So, it will be better to check hasScroll and check data area scrollable options.

2019-09-05 10:13 UTC, vconst submitted a review, later dismissed

2019-09-05 14:31 UTC, vconst approved these changes

2019-09-05 14:54 UTC, roman-simionov approved these changes

2019-09-05 14:55 UTC, merged