dxOverlay: make it possible to change 'container' using defaultProps (T811495)
DevExpress/DevExtreme pull request #9605
Opened 2019-09-06 13:29 UTC by AryamnovEugeniy

2019-09-06 15:16 UTC, DokaRus requested changes

2019-09-06 15:16 UTC, DokaRus commented on js/ui/overlay/ui.overlay.js
> +        if(options.container === undefined) {
L20:
```js
-    noop = require("../../core/utils/common").noop,
+    commonUtils = require("../../core/utils/common"),
+    ensureDefined = commonUtils.ensureDefined,
+    noop = commonUtils.noop,
```

L463:
```js
-    if(options.container === undefined) {
-        this._initContainer(this.option('container'));
-    } else {
-        this._initContainer(options.container);
-    }
+    var container = ensureDefined(options.container, this.option("container"));
+    this._initContainer(container);
```

2019-09-09 19:29 UTC, DokaRus commented on testing/tests/DevExpress.ui.widgets/overlay.tests.js
> +        const overlay = new TestOverlay('#overlay');
```suggestion
        const overlay = new TestOverlay("#overlay");
```

2019-09-10 06:46 UTC, DokaRus submitted a review, later dismissed

2019-09-10 08:29 UTC, alexander-kotov-dx approved these changes

2019-09-10 08:57 UTC, DokaRus approved these changes

2019-09-10 09:07 UTC, merged