DataGrid - focused row style is incorrect on hover in multiple selection mode
DevExpress/DevExtreme pull request #9637
Opened 2019-09-10 06:10 UTC by igormalzew

2019-09-10 08:29 UTC, AntonSermyazhko submitted a review, later dismissed

2019-09-10 10:04 UTC, vconst requested changes
Material theme has the same problem

2019-09-10 13:14 UTC, AntonSermyazhko approved these changes

2019-09-11 07:40 UTC, vconst approved these changes

2019-09-11 07:42 UTC, merged