[WIP] TextBox: the onInput callback is not raised if the mask option is set (T814440)
DevExpress/DevExtreme pull request #9699
Opened 2019-09-13 12:25 UTC by churkin

2019-09-17 12:00 UTC, mrjohn0011 submitted a review, later dismissed

2019-09-17 13:40 UTC, San4es requested changes

2019-09-17 13:40 UTC, San4es commented on js/ui/text_box/ui.text_editor.mask.js
> +        const riseInputEvent = () => {
rise -> raise

2019-09-17 13:40 UTC, San4es commented on js/ui/text_box/ui.text_editor.mask.strategy.default.js
> +            return new Promise((resolve) => {
We need to import the `Promise` polyfill. See: https://github.com/DevExpress/DevExtreme/blob/3f6e5b98c8c9e6192581a2ed56b3e081adb79bc0/js/ui/map/provider.dynamic.js#L1

2019-09-18 08:21 UTC, San4es approved these changes
LGTM

2019-09-18 08:22 UTC, merged