Draggable: Implement autoscroll + docs
DevExpress/DevExtreme pull request #9728
Opened 2019-09-16 14:28 UTC by jtoming830

2019-09-16 14:39 UTC, RomanTsukanov submitted a review, later dismissed

2019-09-17 08:01 UTC, vconst requested changes

2019-09-17 08:01 UTC, vconst commented on js/ui/draggable.js
> +            this._limits = {
_limits  -> _limitProps

2019-09-17 08:01 UTC, vconst commented on js/ui/draggable.js
> +                max: "left",
max -> "min" or "start"
min -> "max" or "end"

2019-09-17 08:20 UTC, vconst submitted a review, later dismissed

2019-09-17 14:44 UTC, vconst approved these changes

2019-09-17 15:03 UTC, Alyar666 approved these changes

2019-09-17 15:06 UTC, merged