DataGrid - The cellValue method does not work when it is invoked immediately after setting an edit form item's option (T817880)
DevExpress/DevExtreme pull request #9984
Opened 2019-10-02 08:15 UTC by igormalzew

2019-10-02 09:25 UTC, AntonSermyazhko submitted a review, later dismissed

2019-10-02 09:25 UTC, vconst requested changes

2019-10-02 09:25 UTC, vconst commented on testing/tests/DevExpress.ui.widgets.dataGrid/dataGrid.tests.js
> +        setTimeout(function() {
Can we remove several setTimeout in this test?

2019-10-03 06:56 UTC, vconst approved these changes

2019-10-03 08:16 UTC, merged